## Import Statements and Read in Files

In [1]:
# Import Statements
import pandas as pd
import numpy as np

import geopy
from geopy.distance import geodesic

In [11]:
missing_36 = pd.read_csv('C:/Users/grace/OneDrive/Desktop/GMU/DAEN690/std_uasLoc_noAir_noNav.csv')

In [12]:
missing_36

,REMARKS,UAS_LOC,IDENT,LONGITUDE,LATITUDE,NAME_TXT
0,Phoenix PD advised a concerned citizen notifie...,['4NM W of RWY'],RWY,NaN,NaN,NaN
1,Aircraft observed a UAS passing off the left s...,['5 NM NNW of WASA'],WASA,NaN,NaN,NaN
2,Aircraft observed a gray UAS off the left side...,['6 NM SSE of PHOG'],PHOG,NaN,NaN,NaN
3,Aircraft observed a black UAS off the while E ...,['5NM W of RWY'],RWY,NaN,NaN,NaN
4,"Aircraft observed a UAS at same altitude of 7,...",['7 NM SE of FTG'],FTG,NaN,NaN,NaN
5,Aircraft observed a UAS off the left side whil...,['1 NM NE of XXX'],XXX,NaN,NaN,NaN
6,Aircraft observed a blue and white UAS over th...,['5 NM S of RWY'],RWY,NaN,NaN,NaN
7,"Aircraft observed a small, circular UAS while ...",['15NM SE of OUC'],OUC,NaN,NaN,NaN
8,Aircraft observed a quad-copter UAS at 10000 f...,['10 NM S of DEM'],DEM,NaN,NaN,NaN
9,Aircraft observed a white quad-copter UAS at 1...,['12 NM NE of KCLR'],KCLR,NaN,NaN,NaN
10,Aircraft observed a UAS 200 feet below while S...,['1NM NW of TJIG'],TJIG,NaN,NaN,NaN
11,Aircraft observed a UAS pass 50 feet above whi...,['2 NM NW of PABE'],PABE,NaN,NaN,NaN
12,Aircraft observed a UAS off the left side whil...,['10 NM SW of HUB'],HUB,NaN,NaN,NaN
13,Aircraft observed a UAS off the right side whi...,['2 NM NW of HEME'],HEME,NaN,NaN,NaN
14,Aircraft observed a UAS while heading 340 at 6...,['5 NM E of NCT'],NCT,NaN,NaN,NaN
15,Aircraft observed a UAS 2 NM E of BURDY inters...,['2 NM E of BURD'],BURD,NaN,NaN,NaN
16,Aircraft observed a UAS off the R side while N...,['5 NM S of HSN'],HSN,NaN,NaN,NaN
17,Aircraft observed a UAS 1 NM SW of RWY 26L app...,['1 NM SW of RWY'],RWY,NaN,NaN,NaN
18,Aircraft observed a UAS off the left side whil...,['1 NM W of RWY'],RWY,NaN,NaN,NaN
19,Aircraft observed a UAS off the right side whi...,['3 NM W of UOA'],UOA,NaN,NaN,NaN
20,Aircraft observed a silver three foot diameter...,['2 NM ENE of LIV'],LIV,NaN,NaN,NaN
21,0340 INITIAL/CLOSEOUT: Law Enforcement Aircraf...,['5 NM NW of RWY'],RWY,NaN,NaN,NaN
22,Aircraft observed an orange UAS while E bound ...,['7 NM W of TJSJ'],TJSJ,NaN,NaN,NaN
23,Aircraft observed a UAS off the left side whil...,['2 NM W of RWY'],RWY,NaN,NaN,NaN
24,Aircraft observed a UAS overhead while N bound...,['2 NM S of RWY'],RWY,NaN,NaN,NaN
25,Aircraft observed a black UAS 100 feet above a...,['9 NM E of CEDE'],CEDE,NaN,NaN,NaN
26,Aircraft observed a UAS off the right side whi...,['1 NM NE of RWY'],RWY,NaN,NaN,NaN
27,Aircraft observed a black and gray UAS while E...,['3 NM NW of TJSJ'],TJSJ,NaN,NaN,NaN
28,Aircraft observed a silver quadcopter UAS off ...,['7NM SE of RIS'],RIS,NaN,NaN,NaN
29,"Aircraft observed a UAS while NW bound at 14,0...",['20 NM NW of CQO'],CQO,NaN,NaN,NaN
30,"Aircraft reported a UAS with red lights at 2,3...",['6 NM S of RWY'],RWY,NaN,NaN,NaN
31,Aircraft reported a UAS 200 feet above their A...,['1NM NNEof RWY'],RWY,NaN,NaN,NaN
32,Aircraft reported a reflective black UAS off i...,['3 NM N of BEQ'],BEQ,NaN,NaN,NaN
33,Aircraft reported a quad copter UAS while 3NM ...,['3NM SW of RWY'],RWY,NaN,NaN,NaN
34,Aircraft reported a small UAS 4 NM SW of RWY19...,['4 NM SW of RWY'],RWY,NaN,NaN,NaN
35,"Aircraft reported a blue UAS, while NE bound a...",['1 NM NE of RWY'],RWY,NaN,NaN,NaN

In [13]:
one = missing_36[missing_36['IDENT'] != 'PABE']
two = one[one['IDENT'] !=  'TJSJ']
three = two[two['IDENT'] !=  'TJIG']
four = three[three['IDENT'] != 'KCLR']
missing_30 = four[four['IDENT'] != 'PHOG']

In [14]:
len(missing_30)

30

In [17]:
missing_30 = missing_30.reset_index()

In [18]:
missing_30

,index,REMARKS,UAS_LOC,IDENT,LONGITUDE,LATITUDE,NAME_TXT
0,0,Phoenix PD advised a concerned citizen notifie...,['4NM W of RWY'],RWY,NaN,NaN,NaN
1,1,Aircraft observed a UAS passing off the left s...,['5 NM NNW of WASA'],WASA,NaN,NaN,NaN
2,3,Aircraft observed a black UAS off the while E ...,['5NM W of RWY'],RWY,NaN,NaN,NaN
3,4,"Aircraft observed a UAS at same altitude of 7,...",['7 NM SE of FTG'],FTG,NaN,NaN,NaN
4,5,Aircraft observed a UAS off the left side whil...,['1 NM NE of XXX'],XXX,NaN,NaN,NaN
5,6,Aircraft observed a blue and white UAS over th...,['5 NM S of RWY'],RWY,NaN,NaN,NaN
6,7,"Aircraft observed a small, circular UAS while ...",['15NM SE of OUC'],OUC,NaN,NaN,NaN
7,8,Aircraft observed a quad-copter UAS at 10000 f...,['10 NM S of DEM'],DEM,NaN,NaN,NaN
8,12,Aircraft observed a UAS off the left side whil...,['10 NM SW of HUB'],HUB,NaN,NaN,NaN
9,13,Aircraft observed a UAS off the right side whi...,['2 NM NW of HEME'],HEME,NaN,NaN,NaN
10,14,Aircraft observed a UAS while heading 340 at 6...,['5 NM E of NCT'],NCT,NaN,NaN,NaN
11,15,Aircraft observed a UAS 2 NM E of BURDY inters...,['2 NM E of BURD'],BURD,NaN,NaN,NaN
12,16,Aircraft observed a UAS off the R side while N...,['5 NM S of HSN'],HSN,NaN,NaN,NaN
13,17,Aircraft observed a UAS 1 NM SW of RWY 26L app...,['1 NM SW of RWY'],RWY,NaN,NaN,NaN
14,18,Aircraft observed a UAS off the left side whil...,['1 NM W of RWY'],RWY,NaN,NaN,NaN
15,19,Aircraft observed a UAS off the right side whi...,['3 NM W of UOA'],UOA,NaN,NaN,NaN
16,20,Aircraft observed a silver three foot diameter...,['2 NM ENE of LIV'],LIV,NaN,NaN,NaN
17,21,0340 INITIAL/CLOSEOUT: Law Enforcement Aircraf...,['5 NM NW of RWY'],RWY,NaN,NaN,NaN
18,23,Aircraft observed a UAS off the left side whil...,['2 NM W of RWY'],RWY,NaN,NaN,NaN
19,24,Aircraft observed a UAS overhead while N bound...,['2 NM S of RWY'],RWY,NaN,NaN,NaN
20,25,Aircraft observed a black UAS 100 feet above a...,['9 NM E of CEDE'],CEDE,NaN,NaN,NaN
21,26,Aircraft observed a UAS off the right side whi...,['1 NM NE of RWY'],RWY,NaN,NaN,NaN
22,28,Aircraft observed a silver quadcopter UAS off ...,['7NM SE of RIS'],RIS,NaN,NaN,NaN
23,29,"Aircraft observed a UAS while NW bound at 14,0...",['20 NM NW of CQO'],CQO,NaN,NaN,NaN
24,30,"Aircraft reported a UAS with red lights at 2,3...",['6 NM S of RWY'],RWY,NaN,NaN,NaN
25,31,Aircraft reported a UAS 200 feet above their A...,['1NM NNEof RWY'],RWY,NaN,NaN,NaN
26,32,Aircraft reported a reflective black UAS off i...,['3 NM N of BEQ'],BEQ,NaN,NaN,NaN
27,33,Aircraft reported a quad copter UAS while 3NM ...,['3NM SW of RWY'],RWY,NaN,NaN,NaN
28,34,Aircraft reported a small UAS 4 NM SW of RWY19...,['4 NM SW of RWY'],RWY,NaN,NaN,NaN
29,35,"Aircraft reported a blue UAS, while NE bound a...",['1 NM NE of RWY'],RWY,NaN,NaN,NaN

In [19]:
# Read in Incidents_Cleaned_Standard.csv
faa_standard = pd.read_csv('C:/Users/grace/OneDrive/Desktop/GMU/DAEN690/Incidents_Cleaned_Standard.csv')
faa_standard

,dateonly,timeonly,DATE,POD,PRIMARYCODE,SECONDARYCODES,REPORTINGFACILITY,REMARKS,FACILITY.CEDAR,UTCTIME24.CEDAR,...,UASLAT.CEDAR,UASFORMATION.CEDAR,CLOSESTPROXIMITY.CEDAR,UASWEIGHTGT55.CEDAR,UASDIM.CEDAR,UASFWROTOR.CEDAR,PILOTREPORTEDNMAC.CEDAR,TCASRA.CEDAR,SUMMARY.CEDAR,QAFINDINGS.CEDAR
0,1/1/2018,10:46,2018-01-01T10:46Z,DEN,UAS,NaN,CLE,Aircraft observed alarge orange UAS with flash...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1/1/2018,14:37,2018-01-01T14:37Z,DEN,UAS,NaN,SLC,"Aircraft observed a UAS while at 5,000 feet 11...",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1/1/2018,14:39,2018-01-01T14:39Z,DEN,UAS,NaN,SLC,"Aircraft observed a UAS while at 5,000 feet 11...",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1/13/2018,12:04,2018-01-13T12:04Z,DEN,UAS,NaN,SJC,Aircraft observed a UAS 100 feet above the Air...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1/15/2018,8:52,2018-01-15T08:52Z,DEN,UAS,NaN,POC,Aircraft observed a UAS operating 400 feet bel...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5186,7/31/2020,20:47,2020-07-31T20:47Z,DEN,UAS,NaN,ZAB,Aircraft reported a 50' diameter white balloon...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5187,1/29/2021,17:50,2021-01-29T17:50Z,DEN,UAS,NaN,M03,Aircraft observed a white UAS while S bound at...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5188,4/6/2021,18:07,2021-04-06T18:07Z,DEN,UAS,NaN,ZAB,Aircraft reported a UAS sensor hit while N bou...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5189,4/20/2021,18:39,2021-04-20T18:39Z,DEN,UAS,NOTIFICATION-NONE,PRC,From MOR: Aircraft reported a NMAC with a flat...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5190,6/9/2021,2:01,2021-06-09T02:01Z,DEN,UNIDENTIFIED AERIAL PHENOMENON,"MOR, UAS",ZLA,Aircraft reported an unidentified aerial pheno...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
missing_30_ALLROWS = pd.merge(missing_30, faa_standard, on='REMARKS', how='left')

In [21]:
missing_30_ALLROWS

,index,REMARKS,UAS_LOC,IDENT,LONGITUDE,LATITUDE,NAME_TXT,dateonly,timeonly,DATE,...,UASLAT.CEDAR,UASFORMATION.CEDAR,CLOSESTPROXIMITY.CEDAR,UASWEIGHTGT55.CEDAR,UASDIM.CEDAR,UASFWROTOR.CEDAR,PILOTREPORTEDNMAC.CEDAR,TCASRA.CEDAR,SUMMARY.CEDAR,QAFINDINGS.CEDAR
0,0,Phoenix PD advised a concerned citizen notifie...,['4NM W of RWY'],RWY,NaN,NaN,NaN,3/28/2018,18:42,2018-03-28T18:42Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Aircraft observed a UAS passing off the left s...,['5 NM NNW of WASA'],WASA,NaN,NaN,NaN,7/22/2019,19:57,2019-07-22T19:57Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,Aircraft observed a black UAS off the while E ...,['5NM W of RWY'],RWY,NaN,NaN,NaN,9/21/2019,18:12,2019-09-21T18:12Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,"Aircraft observed a UAS at same altitude of 7,...",['7 NM SE of FTG'],FTG,NaN,NaN,NaN,10/8/2019,16:10,2019-10-08T16:10Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,Aircraft observed a UAS off the left side whil...,['1 NM NE of XXX'],XXX,NaN,NaN,NaN,10/13/2019,21:26,2019-10-13T21:26Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,6,Aircraft observed a blue and white UAS over th...,['5 NM S of RWY'],RWY,NaN,NaN,NaN,10/13/2019,21:45,2019-10-13T21:45Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,7,"Aircraft observed a small, circular UAS while ...",['15NM SE of OUC'],OUC,NaN,NaN,NaN,11/6/2019,17:17,2019-11-06T17:17Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,8,Aircraft observed a quad-copter UAS at 10000 f...,['10 NM S of DEM'],DEM,NaN,NaN,NaN,11/30/2019,15:25,2019-11-30T15:25Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,12,Aircraft observed a UAS off the left side whil...,['10 NM SW of HUB'],HUB,NaN,NaN,NaN,5/29/2020,14:38,2020-05-29T14:38Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,13,Aircraft observed a UAS off the right side whi...,['2 NM NW of HEME'],HEME,NaN,NaN,NaN,7/5/2020,22:59,2020-07-05T22:59Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,14,Aircraft observed a UAS while heading 340 at 6...,['5 NM E of NCT'],NCT,NaN,NaN,NaN,7/11/2020,18:48,2020-07-11T18:48Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,15,Aircraft observed a UAS 2 NM E of BURDY inters...,['2 NM E of BURD'],BURD,NaN,NaN,NaN,7/25/2020,15:39,2020-07-25T15:39Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,16,Aircraft observed a UAS off the R side while N...,['5 NM S of HSN'],HSN,NaN,NaN,NaN,9/13/2020,19:44,2020-09-13T19:44Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,17,Aircraft observed a UAS 1 NM SW of RWY 26L app...,['1 NM SW of RWY'],RWY,NaN,NaN,NaN,9/29/2020,15:48,2020-09-29T15:48Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,18,Aircraft observed a UAS off the left side whil...,['1 NM W of RWY'],RWY,NaN,NaN,NaN,10/24/2020,1:05,2020-10-24T01:05Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,19,Aircraft observed a UAS off the right side whi...,['3 NM W of UOA'],UOA,NaN,NaN,NaN,3/18/2021,1:24,2021-03-18T01:24Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,20,Aircraft observed a silver three foot diameter...,['2 NM ENE of LIV'],LIV,NaN,NaN,NaN,4/19/2021,23:30,2021-04-19T23:30Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,21,0340 INITIAL/CLOSEOUT: Law Enforcement Aircraf...,['5 NM NW of RWY'],RWY,NaN,NaN,NaN,4/25/2021,5:03,2021-04-25T05:03Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,23,Aircraft observed a UAS off the left side whil...,['2 NM W of RWY'],RWY,NaN,NaN,NaN,6/11/2021,20:12,2021-06-11T20:12Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,24,Aircraft observed a UAS overhead while N bound...,['2 NM S of RWY'],RWY,NaN,NaN,NaN,6/14/2021,22:50,2021-06-14T22:50Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,25,Aircraft observed a black UAS 100 feet above a...,['9 NM E of CEDE'],CEDE,NaN,NaN,NaN,7/5/2021,23:11,2021-07-05T23:11Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,26,Aircraft observed a UAS off the right side whi...,['1 NM NE of RWY'],RWY,NaN,NaN,NaN,7/8/2021,22:14,2021-07-08T22:14Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,28,Aircraft observed a silver quadcopter UAS off ...,['7NM SE of RIS'],RIS,NaN,NaN,NaN,8/14/2021,16:23,2021-08-14T16:23Z,...,NaN,NaN,Closest Proximity (feet): NA,No,UAS Dimensions (feet): 1,Rotor Craft,No,No,N469KM SOUTHWEST BOUND TO OJC ENCOUNTERED USA ...,QA reviewed. No NMAC filed.
23,29,"Aircraft observed a UAS while NW bound at 14,0...",['20 NM NW of CQO'],CQO,NaN,NaN,NaN,8/16/2021,16:07,2021-08-16T16:07Z,...,NaN,NaN,Closest Proximity (feet): 500,No,UAS Dimensions (feet): NA,NaN,No,No,"UAS Activity Report,\r\nEDV5338, CRJ2/L depart...","Facility summary, weather and falcon bookmark ..."
24,30,"Aircraft reported a UAS with red lights at 2,3...",['6 NM S of RWY'],RWY,NaN,NaN,NaN,2/8/2018,3:54,2018-02-08T03:54Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,31,Aircraft reported a UAS 200 feet above their A...,['1NM NNEof RWY'],RWY,NaN,NaN,NaN,2/9/2018,1:02,2018-02-09T01:02Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,32,Aircraft reported a reflective black UAS off i...,['3 NM N of BEQ'],BEQ,NaN,NaN,NaN,3/23/2018,4:28,2018-03-23T04:28Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,33,Aircraft reported a quad copter UAS while 3NM ...,['3NM SW of RWY'],RWY,NaN,NaN,NaN,5/6/2018,4:04,2018-05-06T04:04Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,34,Aircraft reported a small UAS 4 NM SW of RWY19...,['4 NM SW of RWY'],RWY,NaN,NaN,NaN,3/2/2019,6:57,2019-03-02T06:57Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,35,"Aircraft reported a blue UAS, while NE bound a...",['1 NM NE of RWY'],RWY,NaN,NaN,NaN,1/19/2020,18:52,2020-01-19T18:52Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
# Export to .csv file
missing_30_ALLROWS.to_csv('std_missing_30_ALLROWS.csv', index = False)