## This notebook explores 412 records that were kicked back from Lex's R code. 
### The output of this notebook is:
#### 1. 263 Lat/Long calculated for FAA Airport Identifier
#### 2. 1  Lat/Long calculated for NAVAID
#### 3. 1 Designated Point (back to Lex)
#### 4. 147 Records (back to Lex)

In [1]:
# Import needed Libraries
import pandas as pd
import numpy as np
import geopy
from geopy.distance import geodesic

In [77]:
# Read in csv file
nonstd = pd.read_csv('C:/Users/Olga/Desktop/GMU/DAEN690/LEGO/Output_All_Points_Non-Standard_2057Remaining.csv')
nonstd

,REMARKS,dateonly,timeonly,DATE,CALLSIGN,POD,PRIMARYCODE,SECONDARYCODES,REPORTINGFACILITY,MORID.CEDAR,...,ACALTITUDE.CEDAR,ACHEADING.CEDAR,RELATIVECLOCKPOSITION.CEDAR,UASLONG.CEDAR,UASLAT.CEDAR,SUMMARY.CEDAR,QAFINDINGS.CEDAR,DATASET,UASLOCATION,RWYLOCATION
0,ATCT personnel reported observing a large UAS ...,1/4/2018,10:50,2018-01-04T10:50Z,NaN,DEN,UAS,NaN,SHV,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT(?),1 NM SW of SHV,NaN
1,Reported a UAS 400 feet below off the left sid...,1/15/2018,7:35,2018-01-15T07:35Z,N6522,DEN,UAS,NaN,POC,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT(?),1.5 NM NW of POC,NaN
2,Reported sighting a UAS below the aircraft whi...,1/21/2018,6:00,2018-01-21T06:00Z,RAKE06,DEN,UAS,NaN,PHX,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT(?),4.2 NM N of PHX,NaN
3,Pilot observed a 3 foot diameter Quad-copter o...,1/22/2018,1:26,2018-01-22T01:26Z,N31NW,DEN,UAS,NaN,A80,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT(?),24 NM NE of A80,NaN
4,Reported observing a white UAS operating 2 NM ...,1/26/2018,23:31,2018-01-26T23:31Z,NKS832,DEN,UAS,NaN,MCO,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT(?),2 NM S of MCO,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
407,RVS ATCT directly observes and has received mu...,5/1/2021,18:31,2021-05-01T18:31Z,NaN,DEN,UAS,MOR,RVS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT(?),1 NM SE of RVS,NaN
408,Joint Base Pearl Harbor-Hickam Command Post re...,5/13/2021,23:30,2021-05-13T23:30Z,NaN,DEN,UAS,NaN,HQ DEN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,3 NM NW HNL,NaN
409,Local pilot provided in-person report of a sin...,6/11/2021,21:38,2021-06-11T21:38Z,NaN,DEN,UAS,MOR,TKA,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT(?),1 NM W of TKA,NaN
410,1820 EDT / 2220 UTC 6/27/2021\r\nN78ER C172 wa...,6/27/2021,22:07,2021-06-27T22:07Z,N78ER,JATOC,UAS,NaN,BWI,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT(?),10 NM SW of BWI,NaN
411,1448 EDT / 1848 UTC 06/29/2021\r\nN5088L obse...,6/29/2021,18:29,2021-06-29T18:29Z,N5088L,JATOC,UAS,NaN,ALB,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT(?),1 NM W of ALB,NaN

In [4]:
# Find all records that reference airports (in this case the records labeled as NAVAID also reference airports after checking)
nonstd_air = nonstd[(nonstd['DATASET'] == 'AIRPORT') | (nonstd['DATASET'] == 'NAVAID')]
nonstd_air

,REMARKS,dateonly,timeonly,DATE,CALLSIGN,POD,PRIMARYCODE,SECONDARYCODES,REPORTINGFACILITY,MORID.CEDAR,...,ACALTITUDE.CEDAR,ACHEADING.CEDAR,RELATIVECLOCKPOSITION.CEDAR,UASLONG.CEDAR,UASLAT.CEDAR,SUMMARY.CEDAR,QAFINDINGS.CEDAR,DATASET,UASLOCATION,RWYLOCATION
15,Aircraft type SF50. Rreported a UAS off the ri...,2/15/2018,4:29,2018-02-15T04:29Z,N223WY,DEN,UAS,NaN,DLH,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,4 NM NW DLH,NaN
16,Reported a black quad-copter operating at 500 ...,2/15/2018,22:34,2018-02-15T22:34Z,N792AM,DEN,UAS,NaN,MAF,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,2.1 NM S MAF,NaN
21,Reported a UAS off the right wing while W boun...,2/22/2018,5:55,2018-02-22T05:55Z,N363JG,NCRCC,UAS,NaN,LAX,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,14 NM E LAX,NaN
27,Wern ROC advised aircraft reported a UAS headi...,3/15/2018,11:08,2018-03-15T11:08Z,FDX749,DEN,UAS,NaN,WOC,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,7 NM ENE LAX,NaN
28,DCA-1. Pilot reported a black and red quad cop...,3/17/2018,22:05,2018-03-17T22:05Z,NH7,NCRCC,UAS,MOR,DCA,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,7 NM NW DCA,NaN
37,Reported a red UAS off the left side while NE ...,3/31/2018,23:55,2018-03-31T23:55Z,JBU1572,DEN,UAS,NaN,N90,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,5 NM SSE LGA,NaN
71,"Reported a UAS off the right side at 5,200 fee...",5/14/2018,0:47,2018-05-14T00:47Z,N97075,DEN,UAS,NaN,SLC,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,3 NM S SLC,NaN
72,"Reported a white and orange object, unable to ...",5/14/2018,23:29,2018-05-14T23:29Z,AAL2459,DEN,UAS,NaN,WOC,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,15 NM SE MKE,NaN
78,"Aircraft passed a black UAS, 4 rotor type, 300...",5/20/2018,2:41,2018-05-20T02:41Z,N301TS,DEN,UAS,NaN,BOI,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,9 NM NNW BOI,NaN
114,"observed a blue quad copter, approximately 500...",7/8/2018,22:52,2018-07-08T22:52Z,N558PG,DEN,UAS,NaN,PCT,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,5 NM ENE MRB,NaN
117,"PIC reported a UAS at 1,000FT 1.5 NM NE DXR ov...",7/14/2018,23:26,2018-07-14T23:26Z,N70GX,DEN,UAS,NaN,DXR,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,1.5 NM NE DXR,NaN
124,"PIC reported a UAS while 2 NM NE FDK at 1,500F...",7/20/2018,2:36,2018-07-20T02:36Z,N5938Y,DEN,UAS,NaN,FDK,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,2 NM NE FDK,NaN
127,PIC reported white UAS 3FT in diameter quad co...,7/21/2018,23:08,2018-07-21T23:08Z,ENY3474,DEN,UAS,NaN,ZAU,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,5 NM W ORD,NaN
137,PIC reported a silver UAS passed 10FT off left...,7/28/2018,21:48,2018-07-28T21:48Z,DCM6145,DEN,UAS,NaN,D21,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NAVAID,25 NM NE DTW,NaN
145,"PIC reported a silver UAS 1,000FT below Aircra...",8/9/2018,21:15,2018-08-09T21:15Z,JBU1422,DEN,UAS,NaN,FLL,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,8 NM W FLL,NaN
147,PIC reported a black quadcopter UAS 100FT abov...,8/14/2018,6:29,2018-08-14T06:29Z,CAP4262,DEN,UAS,NaN,AUS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,2 NM NE AUS,NaN
148,PIC reported a gray and black UAS 2 NM SE DTW ...,8/14/2018,23:00,2018-08-14T23:00Z,DAL1633,DEN,UAS,NaN,DTW,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,2 NM SE DTW,NaN
149,PIC reported a red UAS with a camera attached ...,8/14/2018,23:46,2018-08-14T23:46Z,DAL1327,DEN,UAS,NaN,LAX,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,22 NM E LAX,NaN
150,PIC reported a black UAS approximately 3FT in ...,8/16/2018,2:04,2018-08-16T02:04Z,DAL2734,DEN,UAS,NaN,A80,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,15 NM E ATL,NaN
151,PIC reported UAS off left side at same altitud...,8/19/2018,19:12,2018-08-19T19:12Z,ENV4083,DEN,UAS,NaN,CLT,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,1.25 NM N CLT,NaN
164,PIC reported UAS at 12 o'clock position at sam...,8/28/2018,3:59,2018-08-28T03:59Z,N8647E,DEN,UAS,NaN,PHX,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,2 NM E PHX,NaN
165,PIC reported UAS at 9 o'clock position at same...,8/28/2018,4:14,2018-08-28T04:14Z,XSR507,DEN,UAS,NaN,DAL,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,4 NM NW DAL,NaN
170,"PIC reported a UAS pass 2,000FT below while WN...",9/2/2018,22:10,2018-09-02T22:10Z,ASQ4236,DEN,UAS,NaN,STL,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,5 NM SW STL,NaN
180,PIC reported a blue helicopter type UAS 20FT o...,9/12/2018,22:28,2018-09-12T22:28Z,N5938U,DEN,UAS,NaN,C90,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,6 NM NE PWK,NaN
187,"PIC reported a UAS while ESE bound at 1,600FT ...",9/21/2018,3:57,2018-09-21T03:57Z,RPA4532,DEN,UAS,NaN,JFK,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,10 NM NW JFK,NaN
188,PIC reported a UAS at 12 o'clock 400FT below w...,9/22/2018,0:52,2018-09-22T00:52Z,AAL1702,DEN,UAS,NaN,P50,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,6 NM E PHX,NaN
189,"PIC reported a white UAS at 11,000FT while NNW...",9/22/2018,23:06,2018-09-22T23:06Z,N703CD,DEN,UAS,NaN,WOC,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,20 NM S DEN,NaN
190,"PIC reported a black quad-copter at 1,000FT wh...",9/23/2018,0:55,2018-09-23T00:55Z,N5766J,DEN,UAS,NaN,BUR,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,10 NM S BUR,NaN
202,Pilot reported a black UAS 500 feet below airc...,10/1/2018,4:47,2018-10-01T04:47Z,EDV3452,DEN,UAS,NaN,N90,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,7 NM SW LGA,NaN
203,Pilot reported a UAS operating 600 feet to 800...,10/2/2018,23:52,2018-10-02T23:52Z,N479ER,DEN,UAS,NaN,SGJ,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,1.5 NM NW SGJ,NaN
225,"PIC reported a UAS above while WSW bound at 7,...",10/17/2018,3:04,2018-10-17T03:04Z,WJA1100,DEN,UAS,NaN,LAX,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,30 NM NE LAX,NaN
226,"The PIC reporteda black quadcopter UAS at 3,50...",10/18/2018,5:59,2018-10-18T05:59Z,N6919J,DEN,UAS,PAGED,PDK,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,10 NM N PDK,NaN
228,"PIC observed a UAS at 6,000FT while S bound at...",10/19/2018,1:07,2018-10-19T01:07Z,N191CA,DEN,UAS,NaN,SLC,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,1.5 NM NE SLC,NaN
236,PIC reported a grey quadcopter UAS 200FT above...,10/22/2018,17:57,2018-10-22T17:57Z,EDV5436,DEN,UAS,NaN,N90,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,5 NM NE JFK,NaN
239,PIC reported a black UAS operating at 300FT 0....,10/24/2018,20:56,2018-10-24T20:56Z,N3DN,DEN,UAS,NaN,MCO,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,0.5 NM NE ORL,NaN
249,PIC reported a white phantom quad-copter UAS o...,10/31/2018,2:49,2018-10-31T02:49Z,DAL1956,DEN,UAS,NaN,MIA,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,2 NM NW MIA,NaN
260,PIC reported a quadcopter UAS while ESE bound ...,11/15/2018,22:32,2018-11-15T22:32Z,N914AC,DEN,UAS,NaN,ZLC,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,30 NM SSW SLC,NaN
265,PIC reported a dark green UAS at the 11 o'cloc...,11/22/2018,22:55,2018-11-22T22:55Z,N56425,DEN,UAS,NaN,I90,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,10 NM WSW IAH,NaN
269,Reported a UAS left side of aircraft at same a...,12/4/2018,3:46,2018-12-04T03:46Z,AAL2148,CONR,UAS,NaN,LGA,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,3 NM NE LGA,NaN
285,Aircraft reported UAS off the leftat same alti...,1/25/2019,22:31,2019-01-25T22:31Z,AAL499,DEN,UAS,NaN,P50,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,10 NM WNW PHX,NaN
287,PIC reported a white rotorcraft from the 12 o'...,1/28/2019,2:55,2019-01-28T02:55Z,N196MC,DEN,UAS,NaN,P50,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,12 NM E PHX,NaN
288,PIC reported a UAS at it's 12 o'clock position...,1/29/2019,0:03,2019-01-29T00:03Z,JIA5379,DEN,UAS,NaN,PHL,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,8.5 NM NE PHL,NaN
299,Report of a black and red quad copter UAS at 6...,2/19/2019,1:15,2019-02-19T01:15Z,N66DD,DEN,UAS,NaN,LAX,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,2 NM E LAX,NaN
333,"Reported a near miss with a whiteUAS at 2,600f...",4/25/2019,1:58,2019-04-25T01:58Z,N107TX,DEN,UAS,NaN,FWA,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,6 NM E SMD,NaN
344,"Reported a UAS while W bound at 10,000 feet 27...",5/17/2019,2:19,2019-05-17T02:19Z,UAL1869,DEN,UAS,NaN,DEN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,27 NM N DEN,NaN
367,Reported a sliver UAS at 10 o'clock and half a...,6/21/2019,2:34,2019-06-21T02:34Z,AAL1021,DEN,UAS,NaN,F11,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,27 NM N MCO,NaN
390,Airport employee reported a UAS operating at a...,2/14/2020,20:45,2020-02-14T20:45Z,NaN,DEN,UAS,NaN,MER,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,1 NM S MER,NaN
402,Security Forces picked up a UAS on scanner fre...,11/24/2020,20:19,2020-11-24T20:19Z,NaN,DEN,UAS,NaN,MGE,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,.5 NM NE MGE,NaN
408,Joint Base Pearl Harbor-Hickam Command Post re...,5/13/2021,23:30,2021-05-13T23:30Z,NaN,DEN,UAS,NaN,HQ DEN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,3 NM NW HNL,NaN

In [5]:
# Extract all IDENTs from UASLOCATION column
uas_loc = nonstd_air['UASLOCATION'].tolist()
uas_airport = []

for i in range(len(uas_loc)):
    airport = uas_loc[i].split(' ')[-1]
    
    if len(airport) <= 4:
        uas_airport.append(airport)
    else:
        trim_air = airport[-3:]
        uas_airport.append(trim_air)
        
uas_airport_df = pd.DataFrame()
uas_airport_df['IDENT'] = uas_airport
uas_airport_df

   IDENT
0    DLH
1    MAF
2    LAX
3    LAX
4    DCA
5    LGA
6    SLC
7    MKE
8    BOI
9    MRB
10   DXR
11   FDK
12   ORD
13   DTW
14   FLL
15   AUS
16   DTW
17   LAX
18   ATL
19   CLT
20   PHX
21   DAL
22   STL
23   PWK
24   JFK
25   PHX
26   DEN
27   BUR
28   LGA
29   SGJ
30   LAX
31   PDK
32   SLC
33   JFK
34   ORL
35   MIA
36   SLC
37   IAH
38   LGA
39   PHX
40   PHX
41   PHL
42   LAX
43   SMD
44   DEN
45   MCO
46   MER
47   MGE
48   HNL

In [6]:
# Read in the airports dataset
airports = pd.read_csv('C:/Users/Olga/Desktop/GMU/DAEN690/LEGO/airports_cleaned.csv')

In [7]:
# Merge IDENTs with airport dataset
uas_air_loc= pd.merge(uas_airport_df, airports, on='IDENT', how='left')
uas_air_loc

   IDENT                               NAME   LATITUDE   LONGITUDE ICAO_ID
0    DLH                        Duluth Intl  46.842070  -92.193237    KDLH
1    MAF    Midland Intl Air and Space Port  31.942528 -102.201917    KMAF
2    LAX                   Los Angeles Intl  33.942496 -118.408049    KLAX
3    LAX                   Los Angeles Intl  33.942496 -118.408049    KLAX
4    DCA       Ronald Reagan Washington Ntl  38.851444  -77.037722    KDCA
5    LGA                          Laguardia  40.777250  -73.872611    KLGA
6    SLC                Salt Lake City Intl  40.788388 -111.977773    KSLC
7    MKE              General Mitchell Intl  42.946932  -87.897064    KMKE
8    BOI           Boise Air Trml/Gowen Fld  43.564361 -116.222861    KBOI
9    MRB       Eastern Wv Rgnl/Shepherd Fld  39.402357  -77.982999    KMRB
10   DXR                       Danbury Muni  41.371528  -73.482194    KDXR
11   FDK                     Frederick Muni  39.417568  -77.374297    KFDK
12   ORD                Chicago O'hare Intl  41.976629  -87.907253    KORD
13   DTW         Detroit Metro Wayne County  42.212444  -83.353389    KDTW
14   FLL     Fort Lauderdale/Hollywood Intl  26.071667  -80.149694    KFLL
15   AUS              Austin-Bergstrom Intl  30.194527  -97.669876    KAUS
16   DTW         Detroit Metro Wayne County  42.212444  -83.353389    KDTW
17   LAX                   Los Angeles Intl  33.942496 -118.408049    KLAX
18   ATL  Hartsfield - Jackson Atlanta Intl  33.636700  -84.427864    KATL
19   CLT             Charlotte/Douglas Intl  35.213750  -80.949056    KCLT
20   PHX            Phoenix Sky Harbor Intl  33.434278 -112.011583    KPHX
21   DAL                    Dallas Love Fld  32.845945  -96.850877    KDAL
22   STL              St Louis Lambert Intl  38.748697  -90.370029    KSTL
23   PWK                       Chicago Exec  42.114279  -87.901541    KPWK
24   JFK                John F Kennedy Intl  40.639928  -73.778693    KJFK
25   PHX            Phoenix Sky Harbor Intl  33.434278 -112.011583    KPHX
26   DEN                        Denver Intl  39.861667 -104.673167    KDEN
27   BUR                           Bob Hope  34.200694 -118.358667    KBUR
28   LGA                          Laguardia  40.777250  -73.872611    KLGA
29   SGJ             Northeast Florida Rgnl  29.959252  -81.339732    KSGJ
30   LAX                   Los Angeles Intl  33.942496 -118.408049    KLAX
31   PDK                   Dekalb-Peachtree  33.876002  -84.302031    KPDK
32   SLC                Salt Lake City Intl  40.788388 -111.977773    KSLC
33   JFK                John F Kennedy Intl  40.639928  -73.778693    KJFK
34   ORL                               Exec  28.545462  -81.332930    KORL
35   MIA                         Miami Intl  25.795361  -80.290116    KMIA
36   SLC                Salt Lake City Intl  40.788388 -111.977773    KSLC
37   IAH        George Bush Intcntl/Houston  29.984435  -95.341442    KIAH
38   LGA                          Laguardia  40.777250  -73.872611    KLGA
39   PHX            Phoenix Sky Harbor Intl  33.434278 -112.011583    KPHX
40   PHX            Phoenix Sky Harbor Intl  33.434278 -112.011583    KPHX
41   PHL                  Philadelphia Intl  39.872084  -75.240663    KPHL
42   LAX                   Los Angeles Intl  33.942496 -118.408049    KLAX
43   SMD                          Smith Fld  41.143361  -85.152778    KSMD
44   DEN                        Denver Intl  39.861667 -104.673167    KDEN
45   MCO                       Orlando Intl  28.429389  -81.309000    KMCO
46   MER                             Castle  37.380484 -120.568186    KMER
47   MGE                        Dobbins ARB  33.914442  -84.514247    KMGE
48   HNL               Daniel K Inouye Intl  21.317817 -157.920227    PHNL

In [8]:
# Add needed columns for further use
add_col = nonstd_air['REMARKS'].tolist()
uas_air_loc['REMARKS'] = add_col
add_col1 = nonstd_air['UASLOCATION'].tolist()
uas_air_loc['UASLOCATION'] = add_col1
uas_air_loc

,IDENT,NAME,LATITUDE,LONGITUDE,ICAO_ID,REMARKS,UASLOCATION
0,DLH,Duluth Intl,46.842070,-92.193237,KDLH,Aircraft type SF50. Rreported a UAS off the ri...,4 NM NW DLH
1,MAF,Midland Intl Air and Space Port,31.942528,-102.201917,KMAF,Reported a black quad-copter operating at 500 ...,2.1 NM S MAF
2,LAX,Los Angeles Intl,33.942496,-118.408049,KLAX,Reported a UAS off the right wing while W boun...,14 NM E LAX
3,LAX,Los Angeles Intl,33.942496,-118.408049,KLAX,Wern ROC advised aircraft reported a UAS headi...,7 NM ENE LAX
4,DCA,Ronald Reagan Washington Ntl,38.851444,-77.037722,KDCA,DCA-1. Pilot reported a black and red quad cop...,7 NM NW DCA
5,LGA,Laguardia,40.777250,-73.872611,KLGA,Reported a red UAS off the left side while NE ...,5 NM SSE LGA
6,SLC,Salt Lake City Intl,40.788388,-111.977773,KSLC,"Reported a UAS off the right side at 5,200 fee...",3 NM S SLC
7,MKE,General Mitchell Intl,42.946932,-87.897064,KMKE,"Reported a white and orange object, unable to ...",15 NM SE MKE
8,BOI,Boise Air Trml/Gowen Fld,43.564361,-116.222861,KBOI,"Aircraft passed a black UAS, 4 rotor type, 300...",9 NM NNW BOI
9,MRB,Eastern Wv Rgnl/Shepherd Fld,39.402357,-77.982999,KMRB,"observed a blue quad copter, approximately 500...",5 NM ENE MRB
10,DXR,Danbury Muni,41.371528,-73.482194,KDXR,"PIC reported a UAS at 1,000FT 1.5 NM NE DXR ov...",1.5 NM NE DXR
11,FDK,Frederick Muni,39.417568,-77.374297,KFDK,"PIC reported a UAS while 2 NM NE FDK at 1,500F...",2 NM NE FDK
12,ORD,Chicago O'hare Intl,41.976629,-87.907253,KORD,PIC reported white UAS 3FT in diameter quad co...,5 NM W ORD
13,DTW,Detroit Metro Wayne County,42.212444,-83.353389,KDTW,PIC reported a silver UAS passed 10FT off left...,25 NM NE DTW
14,FLL,Fort Lauderdale/Hollywood Intl,26.071667,-80.149694,KFLL,"PIC reported a silver UAS 1,000FT below Aircra...",8 NM W FLL
15,AUS,Austin-Bergstrom Intl,30.194527,-97.669876,KAUS,PIC reported a black quadcopter UAS 100FT abov...,2 NM NE AUS
16,DTW,Detroit Metro Wayne County,42.212444,-83.353389,KDTW,PIC reported a gray and black UAS 2 NM SE DTW ...,2 NM SE DTW
17,LAX,Los Angeles Intl,33.942496,-118.408049,KLAX,PIC reported a red UAS with a camera attached ...,22 NM E LAX
18,ATL,Hartsfield - Jackson Atlanta Intl,33.636700,-84.427864,KATL,PIC reported a black UAS approximately 3FT in ...,15 NM E ATL
19,CLT,Charlotte/Douglas Intl,35.213750,-80.949056,KCLT,PIC reported UAS off left side at same altitud...,1.25 NM N CLT
20,PHX,Phoenix Sky Harbor Intl,33.434278,-112.011583,KPHX,PIC reported UAS at 12 o'clock position at sam...,2 NM E PHX
21,DAL,Dallas Love Fld,32.845945,-96.850877,KDAL,PIC reported UAS at 9 o'clock position at same...,4 NM NW DAL
22,STL,St Louis Lambert Intl,38.748697,-90.370029,KSTL,"PIC reported a UAS pass 2,000FT below while WN...",5 NM SW STL
23,PWK,Chicago Exec,42.114279,-87.901541,KPWK,PIC reported a blue helicopter type UAS 20FT o...,6 NM NE PWK
24,JFK,John F Kennedy Intl,40.639928,-73.778693,KJFK,"PIC reported a UAS while ESE bound at 1,600FT ...",10 NM NW JFK
25,PHX,Phoenix Sky Harbor Intl,33.434278,-112.011583,KPHX,PIC reported a UAS at 12 o'clock 400FT below w...,6 NM E PHX
26,DEN,Denver Intl,39.861667,-104.673167,KDEN,"PIC reported a white UAS at 11,000FT while NNW...",20 NM S DEN
27,BUR,Bob Hope,34.200694,-118.358667,KBUR,"PIC reported a black quad-copter at 1,000FT wh...",10 NM S BUR
28,LGA,Laguardia,40.777250,-73.872611,KLGA,Pilot reported a black UAS 500 feet below airc...,7 NM SW LGA
29,SGJ,Northeast Florida Rgnl,29.959252,-81.339732,KSGJ,Pilot reported a UAS operating 600 feet to 800...,1.5 NM NW SGJ
30,LAX,Los Angeles Intl,33.942496,-118.408049,KLAX,"PIC reported a UAS above while WSW bound at 7,...",30 NM NE LAX
31,PDK,Dekalb-Peachtree,33.876002,-84.302031,KPDK,"The PIC reporteda black quadcopter UAS at 3,50...",10 NM N PDK
32,SLC,Salt Lake City Intl,40.788388,-111.977773,KSLC,"PIC observed a UAS at 6,000FT while S bound at...",1.5 NM NE SLC
33,JFK,John F Kennedy Intl,40.639928,-73.778693,KJFK,PIC reported a grey quadcopter UAS 200FT above...,5 NM NE JFK
34,ORL,Exec,28.545462,-81.332930,KORL,PIC reported a black UAS operating at 300FT 0....,0.5 NM NE ORL
35,MIA,Miami Intl,25.795361,-80.290116,KMIA,PIC reported a white phantom quad-copter UAS o...,2 NM NW MIA
36,SLC,Salt Lake City Intl,40.788388,-111.977773,KSLC,PIC reported a quadcopter UAS while ESE bound ...,30 NM SSW SLC
37,IAH,George Bush Intcntl/Houston,29.984435,-95.341442,KIAH,PIC reported a dark green UAS at the 11 o'cloc...,10 NM WSW IAH
38,LGA,Laguardia,40.777250,-73.872611,KLGA,Reported a UAS left side of aircraft at same a...,3 NM NE LGA
39,PHX,Phoenix Sky Harbor Intl,33.434278,-112.011583,KPHX,Aircraft reported UAS off the leftat same alti...,10 NM WNW PHX
40,PHX,Phoenix Sky Harbor Intl,33.434278,-112.011583,KPHX,PIC reported a white rotorcraft from the 12 o'...,12 NM E PHX
41,PHL,Philadelphia Intl,39.872084,-75.240663,KPHL,PIC reported a UAS at it's 12 o'clock position...,8.5 NM NE PHL
42,LAX,Los Angeles Intl,33.942496,-118.408049,KLAX,Report of a black and red quad copter UAS at 6...,2 NM E LAX
43,SMD,Smith Fld,41.143361,-85.152778,KSMD,"Reported a near miss with a whiteUAS at 2,600f...",6 NM E SMD
44,DEN,Denver Intl,39.861667,-104.673167,KDEN,"Reported a UAS while W bound at 10,000 feet 27...",27 NM N DEN
45,MCO,Orlando Intl,28.429389,-81.309000,KMCO,Reported a sliver UAS at 10 o'clock and half a...,27 NM N MCO
46,MER,Castle,37.380484,-120.568186,KMER,Airport employee reported a UAS operating at a...,1 NM S MER
47,MGE,Dobbins ARB,33.914442,-84.514247,KMGE,Security Forces picked up a UAS on scanner fre...,.5 NM NE MGE
48,HNL,Daniel K Inouye Intl,21.317817,-157.920227,PHNL,Joint Base Pearl Harbor-Hickam Command Post re...,3 NM NW HNL

In [9]:
# Create Dictionary of Bearings and their Degree values
bearing_deg = {
    'N' : 0,
    'NNE' : 23,
    'NE' : 45,
    'ENE' : 68,
    'E' : 90,
    'ESE' : 113,
    'SE' : 135,
    'SSE' : 158,
    'S' : 180,
    'SSW' : 203,
    'SW' : 225,
    'WSW' : 248,
    'W' : 270,
    'WNW' : 293,
    'NW' : 315,
    'NNW' : 338
}

# Seperate UAS_LOC column into the Distances and Bearing Abbreviations
uas_loc = uas_air_loc['UASLOCATION']
distances = []
bearings = []

for i in range(len(uas_loc)):
    split = uas_loc[i].split(' ')[0:3]
    
    if 'NM' in split[0]: #if there is no space between the distance and NM (i.e. 3NM)
        distance_nm = split[0][0:len(split[0]) - 2]
        bearing_abrev = split[1].replace('of', '')
        
    else: 
        distance_nm = split[0]
        bearing_abrev = split[2].replace('of', '')
    
    distances.append(distance_nm[0:])
    bearings.append(bearing_abrev)

# Create new dataframe for UAS locations
new_df = pd.DataFrame(uas_air_loc['REMARKS'])
new_df['UAS_LOC'] = uas_air_loc['UASLOCATION']
new_df['IDENT'] = uas_air_loc['IDENT']
new_df['Distance'] = distances
new_df['Bearing'] = bearings

new_df

,REMARKS,UAS_LOC,IDENT,Distance,Bearing
0,Aircraft type SF50. Rreported a UAS off the ri...,4 NM NW DLH,DLH,4,NW
1,Reported a black quad-copter operating at 500 ...,2.1 NM S MAF,MAF,2.1,S
2,Reported a UAS off the right wing while W boun...,14 NM E LAX,LAX,14,E
3,Wern ROC advised aircraft reported a UAS headi...,7 NM ENE LAX,LAX,7,ENE
4,DCA-1. Pilot reported a black and red quad cop...,7 NM NW DCA,DCA,7,NW
5,Reported a red UAS off the left side while NE ...,5 NM SSE LGA,LGA,5,SSE
6,"Reported a UAS off the right side at 5,200 fee...",3 NM S SLC,SLC,3,S
7,"Reported a white and orange object, unable to ...",15 NM SE MKE,MKE,15,SE
8,"Aircraft passed a black UAS, 4 rotor type, 300...",9 NM NNW BOI,BOI,9,NNW
9,"observed a blue quad copter, approximately 500...",5 NM ENE MRB,MRB,5,ENE
10,"PIC reported a UAS at 1,000FT 1.5 NM NE DXR ov...",1.5 NM NE DXR,DXR,1.5,NE
11,"PIC reported a UAS while 2 NM NE FDK at 1,500F...",2 NM NE FDK,FDK,2,NE
12,PIC reported white UAS 3FT in diameter quad co...,5 NM W ORD,ORD,5,W
13,PIC reported a silver UAS passed 10FT off left...,25 NM NE DTW,DTW,25,NE
14,"PIC reported a silver UAS 1,000FT below Aircra...",8 NM W FLL,FLL,8,W
15,PIC reported a black quadcopter UAS 100FT abov...,2 NM NE AUS,AUS,2,NE
16,PIC reported a gray and black UAS 2 NM SE DTW ...,2 NM SE DTW,DTW,2,SE
17,PIC reported a red UAS with a camera attached ...,22 NM E LAX,LAX,22,E
18,PIC reported a black UAS approximately 3FT in ...,15 NM E ATL,ATL,15,E
19,PIC reported UAS off left side at same altitud...,1.25 NM N CLT,CLT,1.25,N
20,PIC reported UAS at 12 o'clock position at sam...,2 NM E PHX,PHX,2,E
21,PIC reported UAS at 9 o'clock position at same...,4 NM NW DAL,DAL,4,NW
22,"PIC reported a UAS pass 2,000FT below while WN...",5 NM SW STL,STL,5,SW
23,PIC reported a blue helicopter type UAS 20FT o...,6 NM NE PWK,PWK,6,NE
24,"PIC reported a UAS while ESE bound at 1,600FT ...",10 NM NW JFK,JFK,10,NW
25,PIC reported a UAS at 12 o'clock 400FT below w...,6 NM E PHX,PHX,6,E
26,"PIC reported a white UAS at 11,000FT while NNW...",20 NM S DEN,DEN,20,S
27,"PIC reported a black quad-copter at 1,000FT wh...",10 NM S BUR,BUR,10,S
28,Pilot reported a black UAS 500 feet below airc...,7 NM SW LGA,LGA,7,SW
29,Pilot reported a UAS operating 600 feet to 800...,1.5 NM NW SGJ,SGJ,1.5,NW
30,"PIC reported a UAS above while WSW bound at 7,...",30 NM NE LAX,LAX,30,NE
31,"The PIC reporteda black quadcopter UAS at 3,50...",10 NM N PDK,PDK,10,N
32,"PIC observed a UAS at 6,000FT while S bound at...",1.5 NM NE SLC,SLC,1.5,NE
33,PIC reported a grey quadcopter UAS 200FT above...,5 NM NE JFK,JFK,5,NE
34,PIC reported a black UAS operating at 300FT 0....,0.5 NM NE ORL,ORL,0.5,NE
35,PIC reported a white phantom quad-copter UAS o...,2 NM NW MIA,MIA,2,NW
36,PIC reported a quadcopter UAS while ESE bound ...,30 NM SSW SLC,SLC,30,SSW
37,PIC reported a dark green UAS at the 11 o'cloc...,10 NM WSW IAH,IAH,10,WSW
38,Reported a UAS left side of aircraft at same a...,3 NM NE LGA,LGA,3,NE
39,Aircraft reported UAS off the leftat same alti...,10 NM WNW PHX,PHX,10,WNW
40,PIC reported a white rotorcraft from the 12 o'...,12 NM E PHX,PHX,12,E
41,PIC reported a UAS at it's 12 o'clock position...,8.5 NM NE PHL,PHL,8.5,NE
42,Report of a black and red quad copter UAS at 6...,2 NM E LAX,LAX,2,E
43,"Reported a near miss with a whiteUAS at 2,600f...",6 NM E SMD,SMD,6,E
44,"Reported a UAS while W bound at 10,000 feet 27...",27 NM N DEN,DEN,27,N
45,Reported a sliver UAS at 10 o'clock and half a...,27 NM N MCO,MCO,27,N
46,Airport employee reported a UAS operating at a...,1 NM S MER,MER,1,S
47,Security Forces picked up a UAS on scanner fre...,.5 NM NE MGE,MGE,.5,NE
48,Joint Base Pearl Harbor-Hickam Command Post re...,3 NM NW HNL,HNL,3,NW

In [26]:
# Convert distances from NM to KM
new_df['Distance'] = pd.to_numeric(new_df['Distance'],errors = 'coerce')
dist_kilo = []

for i in range(len(new_df)):
    distanceKilo = new_df['Distance'][i] * 1.852 # converting NM to kilometers
    dist_kilo.append(distanceKilo)

bearDegree = pd.DataFrame(new_df['Bearing'])
bearDegree = bearDegree.replace({'Bearing': bearing_deg})

new_df['Distance_Kilometers'] = dist_kilo
new_df['Bearing_Degrees'] = bearDegree
new_df['Airport_Latitude'] = uas_air_loc['LATITUDE']
new_df['Airport_Longitude'] = uas_air_loc['LONGITUDE']
new_df

,REMARKS,UAS_LOC,IDENT,Distance,Bearing,Distance_Kilometers,Bearing_Degrees,Airport_Latitude,Airport_Longitude
0,Aircraft type SF50. Rreported a UAS off the ri...,4 NM NW DLH,DLH,4.00,NW,7.4080,315,46.842070,-92.193237
1,Reported a black quad-copter operating at 500 ...,2.1 NM S MAF,MAF,2.10,S,3.8892,180,31.942528,-102.201917
2,Reported a UAS off the right wing while W boun...,14 NM E LAX,LAX,14.00,E,25.9280,90,33.942496,-118.408049
3,Wern ROC advised aircraft reported a UAS headi...,7 NM ENE LAX,LAX,7.00,ENE,12.9640,68,33.942496,-118.408049
4,DCA-1. Pilot reported a black and red quad cop...,7 NM NW DCA,DCA,7.00,NW,12.9640,315,38.851444,-77.037722
5,Reported a red UAS off the left side while NE ...,5 NM SSE LGA,LGA,5.00,SSE,9.2600,158,40.777250,-73.872611
6,"Reported a UAS off the right side at 5,200 fee...",3 NM S SLC,SLC,3.00,S,5.5560,180,40.788388,-111.977773
7,"Reported a white and orange object, unable to ...",15 NM SE MKE,MKE,15.00,SE,27.7800,135,42.946932,-87.897064
8,"Aircraft passed a black UAS, 4 rotor type, 300...",9 NM NNW BOI,BOI,9.00,NNW,16.6680,338,43.564361,-116.222861
9,"observed a blue quad copter, approximately 500...",5 NM ENE MRB,MRB,5.00,ENE,9.2600,68,39.402357,-77.982999
10,"PIC reported a UAS at 1,000FT 1.5 NM NE DXR ov...",1.5 NM NE DXR,DXR,1.50,NE,2.7780,45,41.371528,-73.482194
11,"PIC reported a UAS while 2 NM NE FDK at 1,500F...",2 NM NE FDK,FDK,2.00,NE,3.7040,45,39.417568,-77.374297
12,PIC reported white UAS 3FT in diameter quad co...,5 NM W ORD,ORD,5.00,W,9.2600,270,41.976629,-87.907253
13,PIC reported a silver UAS passed 10FT off left...,25 NM NE DTW,DTW,25.00,NE,46.3000,45,42.212444,-83.353389
14,"PIC reported a silver UAS 1,000FT below Aircra...",8 NM W FLL,FLL,8.00,W,14.8160,270,26.071667,-80.149694
15,PIC reported a black quadcopter UAS 100FT abov...,2 NM NE AUS,AUS,2.00,NE,3.7040,45,30.194527,-97.669876
16,PIC reported a gray and black UAS 2 NM SE DTW ...,2 NM SE DTW,DTW,2.00,SE,3.7040,135,42.212444,-83.353389
17,PIC reported a red UAS with a camera attached ...,22 NM E LAX,LAX,22.00,E,40.7440,90,33.942496,-118.408049
18,PIC reported a black UAS approximately 3FT in ...,15 NM E ATL,ATL,15.00,E,27.7800,90,33.636700,-84.427864
19,PIC reported UAS off left side at same altitud...,1.25 NM N CLT,CLT,1.25,N,2.3150,0,35.213750,-80.949056
20,PIC reported UAS at 12 o'clock position at sam...,2 NM E PHX,PHX,2.00,E,3.7040,90,33.434278,-112.011583
21,PIC reported UAS at 9 o'clock position at same...,4 NM NW DAL,DAL,4.00,NW,7.4080,315,32.845945,-96.850877
22,"PIC reported a UAS pass 2,000FT below while WN...",5 NM SW STL,STL,5.00,SW,9.2600,225,38.748697,-90.370029
23,PIC reported a blue helicopter type UAS 20FT o...,6 NM NE PWK,PWK,6.00,NE,11.1120,45,42.114279,-87.901541
24,"PIC reported a UAS while ESE bound at 1,600FT ...",10 NM NW JFK,JFK,10.00,NW,18.5200,315,40.639928,-73.778693
25,PIC reported a UAS at 12 o'clock 400FT below w...,6 NM E PHX,PHX,6.00,E,11.1120,90,33.434278,-112.011583
26,"PIC reported a white UAS at 11,000FT while NNW...",20 NM S DEN,DEN,20.00,S,37.0400,180,39.861667,-104.673167
27,"PIC reported a black quad-copter at 1,000FT wh...",10 NM S BUR,BUR,10.00,S,18.5200,180,34.200694,-118.358667
28,Pilot reported a black UAS 500 feet below airc...,7 NM SW LGA,LGA,7.00,SW,12.9640,225,40.777250,-73.872611
29,Pilot reported a UAS operating 600 feet to 800...,1.5 NM NW SGJ,SGJ,1.50,NW,2.7780,315,29.959252,-81.339732
30,"PIC reported a UAS above while WSW bound at 7,...",30 NM NE LAX,LAX,30.00,NE,55.5600,45,33.942496,-118.408049
31,"The PIC reporteda black quadcopter UAS at 3,50...",10 NM N PDK,PDK,10.00,N,18.5200,0,33.876002,-84.302031
32,"PIC observed a UAS at 6,000FT while S bound at...",1.5 NM NE SLC,SLC,1.50,NE,2.7780,45,40.788388,-111.977773
33,PIC reported a grey quadcopter UAS 200FT above...,5 NM NE JFK,JFK,5.00,NE,9.2600,45,40.639928,-73.778693
34,PIC reported a black UAS operating at 300FT 0....,0.5 NM NE ORL,ORL,0.50,NE,0.9260,45,28.545462,-81.332930
35,PIC reported a white phantom quad-copter UAS o...,2 NM NW MIA,MIA,2.00,NW,3.7040,315,25.795361,-80.290116
36,PIC reported a quadcopter UAS while ESE bound ...,30 NM SSW SLC,SLC,30.00,SSW,55.5600,203,40.788388,-111.977773
37,PIC reported a dark green UAS at the 11 o'cloc...,10 NM WSW IAH,IAH,10.00,WSW,18.5200,248,29.984435,-95.341442
38,Reported a UAS left side of aircraft at same a...,3 NM NE LGA,LGA,3.00,NE,5.5560,45,40.777250,-73.872611
39,Aircraft reported UAS off the leftat same alti...,10 NM WNW PHX,PHX,10.00,WNW,18.5200,293,33.434278,-112.011583
40,PIC reported a white rotorcraft from the 12 o'...,12 NM E PHX,PHX,12.00,E,22.2240,90,33.434278,-112.011583
41,PIC reported a UAS at it's 12 o'clock position...,8.5 NM NE PHL,PHL,8.50,NE,15.7420,45,39.872084,-75.240663
42,Report of a black and red quad copter UAS at 6...,2 NM E LAX,LAX,2.00,E,3.7040,90,33.942496,-118.408049
43,"Reported a near miss with a whiteUAS at 2,600f...",6 NM E SMD,SMD,6.00,E,11.1120,90,41.143361,-85.152778
44,"Reported a UAS while W bound at 10,000 feet 27...",27 NM N DEN,DEN,27.00,N,50.0040,0,39.861667,-104.673167
45,Reported a sliver UAS at 10 o'clock and half a...,27 NM N MCO,MCO,27.00,N,50.0040,0,28.429389,-81.309000
46,Airport employee reported a UAS operating at a...,1 NM S MER,MER,1.00,S,1.8520,180,37.380484,-120.568186
47,Security Forces picked up a UAS on scanner fre...,.5 NM NE MGE,MGE,0.50,NE,0.9260,45,33.914442,-84.514247
48,Joint Base Pearl Harbor-Hickam Command Post re...,3 NM NW HNL,HNL,3.00,NW,5.5560,315,21.317817,-157.920227

In [27]:
# Drop and rename columns
new_df2 = pd.merge(new_df, airports, on='IDENT', how='left')
new_df2 = new_df2.drop(['Airport_Latitude', 'Airport_Longitude'], 1)
new_df2 = new_df2.rename({'LONGITUDE': 'Airport_Longitude', 'LATITUDE': 'Airport_Latitude'}, axis=1)
new_df2

,REMARKS,UAS_LOC,IDENT,Distance,Bearing,Distance_Kilometers,Bearing_Degrees,NAME,Airport_Latitude,Airport_Longitude,ICAO_ID
0,Aircraft type SF50. Rreported a UAS off the ri...,4 NM NW DLH,DLH,4.00,NW,7.4080,315,Duluth Intl,46.842070,-92.193237,KDLH
1,Reported a black quad-copter operating at 500 ...,2.1 NM S MAF,MAF,2.10,S,3.8892,180,Midland Intl Air and Space Port,31.942528,-102.201917,KMAF
2,Reported a UAS off the right wing while W boun...,14 NM E LAX,LAX,14.00,E,25.9280,90,Los Angeles Intl,33.942496,-118.408049,KLAX
3,Wern ROC advised aircraft reported a UAS headi...,7 NM ENE LAX,LAX,7.00,ENE,12.9640,68,Los Angeles Intl,33.942496,-118.408049,KLAX
4,DCA-1. Pilot reported a black and red quad cop...,7 NM NW DCA,DCA,7.00,NW,12.9640,315,Ronald Reagan Washington Ntl,38.851444,-77.037722,KDCA
5,Reported a red UAS off the left side while NE ...,5 NM SSE LGA,LGA,5.00,SSE,9.2600,158,Laguardia,40.777250,-73.872611,KLGA
6,"Reported a UAS off the right side at 5,200 fee...",3 NM S SLC,SLC,3.00,S,5.5560,180,Salt Lake City Intl,40.788388,-111.977773,KSLC
7,"Reported a white and orange object, unable to ...",15 NM SE MKE,MKE,15.00,SE,27.7800,135,General Mitchell Intl,42.946932,-87.897064,KMKE
8,"Aircraft passed a black UAS, 4 rotor type, 300...",9 NM NNW BOI,BOI,9.00,NNW,16.6680,338,Boise Air Trml/Gowen Fld,43.564361,-116.222861,KBOI
9,"observed a blue quad copter, approximately 500...",5 NM ENE MRB,MRB,5.00,ENE,9.2600,68,Eastern Wv Rgnl/Shepherd Fld,39.402357,-77.982999,KMRB
10,"PIC reported a UAS at 1,000FT 1.5 NM NE DXR ov...",1.5 NM NE DXR,DXR,1.50,NE,2.7780,45,Danbury Muni,41.371528,-73.482194,KDXR
11,"PIC reported a UAS while 2 NM NE FDK at 1,500F...",2 NM NE FDK,FDK,2.00,NE,3.7040,45,Frederick Muni,39.417568,-77.374297,KFDK
12,PIC reported white UAS 3FT in diameter quad co...,5 NM W ORD,ORD,5.00,W,9.2600,270,Chicago O'hare Intl,41.976629,-87.907253,KORD
13,PIC reported a silver UAS passed 10FT off left...,25 NM NE DTW,DTW,25.00,NE,46.3000,45,Detroit Metro Wayne County,42.212444,-83.353389,KDTW
14,"PIC reported a silver UAS 1,000FT below Aircra...",8 NM W FLL,FLL,8.00,W,14.8160,270,Fort Lauderdale/Hollywood Intl,26.071667,-80.149694,KFLL
15,PIC reported a black quadcopter UAS 100FT abov...,2 NM NE AUS,AUS,2.00,NE,3.7040,45,Austin-Bergstrom Intl,30.194527,-97.669876,KAUS
16,PIC reported a gray and black UAS 2 NM SE DTW ...,2 NM SE DTW,DTW,2.00,SE,3.7040,135,Detroit Metro Wayne County,42.212444,-83.353389,KDTW
17,PIC reported a red UAS with a camera attached ...,22 NM E LAX,LAX,22.00,E,40.7440,90,Los Angeles Intl,33.942496,-118.408049,KLAX
18,PIC reported a black UAS approximately 3FT in ...,15 NM E ATL,ATL,15.00,E,27.7800,90,Hartsfield - Jackson Atlanta Intl,33.636700,-84.427864,KATL
19,PIC reported UAS off left side at same altitud...,1.25 NM N CLT,CLT,1.25,N,2.3150,0,Charlotte/Douglas Intl,35.213750,-80.949056,KCLT
20,PIC reported UAS at 12 o'clock position at sam...,2 NM E PHX,PHX,2.00,E,3.7040,90,Phoenix Sky Harbor Intl,33.434278,-112.011583,KPHX
21,PIC reported UAS at 9 o'clock position at same...,4 NM NW DAL,DAL,4.00,NW,7.4080,315,Dallas Love Fld,32.845945,-96.850877,KDAL
22,"PIC reported a UAS pass 2,000FT below while WN...",5 NM SW STL,STL,5.00,SW,9.2600,225,St Louis Lambert Intl,38.748697,-90.370029,KSTL
23,PIC reported a blue helicopter type UAS 20FT o...,6 NM NE PWK,PWK,6.00,NE,11.1120,45,Chicago Exec,42.114279,-87.901541,KPWK
24,"PIC reported a UAS while ESE bound at 1,600FT ...",10 NM NW JFK,JFK,10.00,NW,18.5200,315,John F Kennedy Intl,40.639928,-73.778693,KJFK
25,PIC reported a UAS at 12 o'clock 400FT below w...,6 NM E PHX,PHX,6.00,E,11.1120,90,Phoenix Sky Harbor Intl,33.434278,-112.011583,KPHX
26,"PIC reported a white UAS at 11,000FT while NNW...",20 NM S DEN,DEN,20.00,S,37.0400,180,Denver Intl,39.861667,-104.673167,KDEN
27,"PIC reported a black quad-copter at 1,000FT wh...",10 NM S BUR,BUR,10.00,S,18.5200,180,Bob Hope,34.200694,-118.358667,KBUR
28,Pilot reported a black UAS 500 feet below airc...,7 NM SW LGA,LGA,7.00,SW,12.9640,225,Laguardia,40.777250,-73.872611,KLGA
29,Pilot reported a UAS operating 600 feet to 800...,1.5 NM NW SGJ,SGJ,1.50,NW,2.7780,315,Northeast Florida Rgnl,29.959252,-81.339732,KSGJ
30,"PIC reported a UAS above while WSW bound at 7,...",30 NM NE LAX,LAX,30.00,NE,55.5600,45,Los Angeles Intl,33.942496,-118.408049,KLAX
31,"The PIC reporteda black quadcopter UAS at 3,50...",10 NM N PDK,PDK,10.00,N,18.5200,0,Dekalb-Peachtree,33.876002,-84.302031,KPDK
32,"PIC observed a UAS at 6,000FT while S bound at...",1.5 NM NE SLC,SLC,1.50,NE,2.7780,45,Salt Lake City Intl,40.788388,-111.977773,KSLC
33,PIC reported a grey quadcopter UAS 200FT above...,5 NM NE JFK,JFK,5.00,NE,9.2600,45,John F Kennedy Intl,40.639928,-73.778693,KJFK
34,PIC reported a black UAS operating at 300FT 0....,0.5 NM NE ORL,ORL,0.50,NE,0.9260,45,Exec,28.545462,-81.332930,KORL
35,PIC reported a white phantom quad-copter UAS o...,2 NM NW MIA,MIA,2.00,NW,3.7040,315,Miami Intl,25.795361,-80.290116,KMIA
36,PIC reported a quadcopter UAS while ESE bound ...,30 NM SSW SLC,SLC,30.00,SSW,55.5600,203,Salt Lake City Intl,40.788388,-111.977773,KSLC
37,PIC reported a dark green UAS at the 11 o'cloc...,10 NM WSW IAH,IAH,10.00,WSW,18.5200,248,George Bush Intcntl/Houston,29.984435,-95.341442,KIAH
38,Reported a UAS left side of aircraft at same a...,3 NM NE LGA,LGA,3.00,NE,5.5560,45,Laguardia,40.777250,-73.872611,KLGA
39,Aircraft reported UAS off the leftat same alti...,10 NM WNW PHX,PHX,10.00,WNW,18.5200,293,Phoenix Sky Harbor Intl,33.434278,-112.011583,KPHX
40,PIC reported a white rotorcraft from the 12 o'...,12 NM E PHX,PHX,12.00,E,22.2240,90,Phoenix Sky Harbor Intl,33.434278,-112.011583,KPHX
41,PIC reported a UAS at it's 12 o'clock position...,8.5 NM NE PHL,PHL,8.50,NE,15.7420,45,Philadelphia Intl,39.872084,-75.240663,KPHL
42,Report of a black and red quad copter UAS at 6...,2 NM E LAX,LAX,2.00,E,3.7040,90,Los Angeles Intl,33.942496,-118.408049,KLAX
43,"Reported a near miss with a whiteUAS at 2,600f...",6 NM E SMD,SMD,6.00,E,11.1120,90,Smith Fld,41.143361,-85.152778,KSMD
44,"Reported a UAS while W bound at 10,000 feet 27...",27 NM N DEN,DEN,27.00,N,50.0040,0,Denver Intl,39.861667,-104.673167,KDEN
45,Reported a sliver UAS at 10 o'clock and half a...,27 NM N MCO,MCO,27.00,N,50.0040,0,Orlando Intl,28.429389,-81.309000,KMCO
46,Airport employee reported a UAS operating at a...,1 NM S MER,MER,1.00,S,1.8520,180,Castle,37.380484,-120.568186,KMER
47,Security Forces picked up a UAS on scanner fre...,.5 NM NE MGE,MGE,0.50,NE,0.9260,45,Dobbins ARB,33.914442,-84.514247,KMGE
48,Joint Base Pearl Harbor-Hickam Command Post re...,3 NM NW HNL,HNL,3.00,NW,5.5560,315,Daniel K Inouye Intl,21.317817,-157.920227,PHNL

In [28]:
# Calculate UAS lat and long
uas_lat = []
uas_long = []

for i in range(len(new_df)):
    lat_airport = pd.to_numeric(new_df2['Airport_Latitude'][i])
    long_airport = pd.to_numeric(new_df2['Airport_Longitude'][i])
    b = pd.to_numeric(new_df['Bearing_Degrees'][i])
    d = pd.to_numeric(new_df['Distance_Kilometers'][i])
    
    origin = geopy.Point(lat_airport, long_airport)
    destination = geodesic(kilometers=d).destination(origin,b)
    
    lat2, lon2, = destination.latitude, destination.longitude
    
    uas_lat.append(lat2)
    uas_long.append(lon2)

# Append UAS Lat/Long information to DataFrame
new_df2['UAS_Latitude'] = uas_lat
new_df2['UAS_Longitude'] = uas_long
new_df2

,REMARKS,UAS_LOC,IDENT,Distance,Bearing,Distance_Kilometers,Bearing_Degrees,NAME,Airport_Latitude,Airport_Longitude,ICAO_ID,UAS_Latitude,UAS_Longitude
0,Aircraft type SF50. Rreported a UAS off the ri...,4 NM NW DLH,DLH,4.00,NW,7.4080,315,Duluth Intl,46.842070,-92.193237,KDLH,46.889169,-92.261969
1,Reported a black quad-copter operating at 500 ...,2.1 NM S MAF,MAF,2.10,S,3.8892,180,Midland Intl Air and Space Port,31.942528,-102.201917,KMAF,31.907454,-102.201917
2,Reported a UAS off the right wing while W boun...,14 NM E LAX,LAX,14.00,E,25.9280,90,Los Angeles Intl,33.942496,-118.408049,KLAX,33.942177,-118.127586
3,Wern ROC advised aircraft reported a UAS headi...,7 NM ENE LAX,LAX,7.00,ENE,12.9640,68,Los Angeles Intl,33.942496,-118.408049,KLAX,33.986210,-118.277961
4,DCA-1. Pilot reported a black and red quad cop...,7 NM NW DCA,DCA,7.00,NW,12.9640,315,Ronald Reagan Washington Ntl,38.851444,-77.037722,KDCA,38.933972,-77.143445
5,Reported a red UAS off the left side while NE ...,5 NM SSE LGA,LGA,5.00,SSE,9.2600,158,Laguardia,40.777250,-73.872611,KLGA,40.699928,-73.831567
6,"Reported a UAS off the right side at 5,200 fee...",3 NM S SLC,SLC,3.00,S,5.5560,180,Salt Lake City Intl,40.788388,-111.977773,KSLC,40.738356,-111.977773
7,"Reported a white and orange object, unable to ...",15 NM SE MKE,MKE,15.00,SE,27.7800,135,General Mitchell Intl,42.946932,-87.897064,KMKE,42.769855,-87.657056
8,"Aircraft passed a black UAS, 4 rotor type, 300...",9 NM NNW BOI,BOI,9.00,NNW,16.6680,338,Boise Air Trml/Gowen Fld,43.564361,-116.222861,KBOI,43.703431,-116.300325
9,"observed a blue quad copter, approximately 500...",5 NM ENE MRB,MRB,5.00,ENE,9.2600,68,Eastern Wv Rgnl/Shepherd Fld,39.402357,-77.982999,KMRB,39.433558,-77.883276
10,"PIC reported a UAS at 1,000FT 1.5 NM NE DXR ov...",1.5 NM NE DXR,DXR,1.50,NE,2.7780,45,Danbury Muni,41.371528,-73.482194,KDXR,41.389212,-73.458708
11,"PIC reported a UAS while 2 NM NE FDK at 1,500F...",2 NM NE FDK,FDK,2.00,NE,3.7040,45,Frederick Muni,39.417568,-77.374297,KFDK,39.441155,-77.343873
12,PIC reported white UAS 3FT in diameter quad co...,5 NM W ORD,ORD,5.00,W,9.2600,270,Chicago O'hare Intl,41.976629,-87.907253,KORD,41.976575,-88.018979
13,PIC reported a silver UAS passed 10FT off left...,25 NM NE DTW,DTW,25.00,NE,46.3000,45,Detroit Metro Wayne County,42.212444,-83.353389,KDTW,42.506488,-82.955058
14,"PIC reported a silver UAS 1,000FT below Aircra...",8 NM W FLL,FLL,8.00,W,14.8160,270,Fort Lauderdale/Hollywood Intl,26.071667,-80.149694,KFLL,26.071591,-80.297770
15,PIC reported a black quadcopter UAS 100FT abov...,2 NM NE AUS,AUS,2.00,NE,3.7040,45,Austin-Bergstrom Intl,30.194527,-97.669876,KAUS,30.218151,-97.642671
16,PIC reported a gray and black UAS 2 NM SE DTW ...,2 NM SE DTW,DTW,2.00,SE,3.7040,135,Detroit Metro Wayne County,42.212444,-83.353389,KDTW,42.188861,-83.321682
17,PIC reported a red UAS with a camera attached ...,22 NM E LAX,LAX,22.00,E,40.7440,90,Los Angeles Intl,33.942496,-118.408049,KLAX,33.941708,-117.967323
18,PIC reported a black UAS approximately 3FT in ...,15 NM E ATL,ATL,15.00,E,27.7800,90,Hartsfield - Jackson Atlanta Intl,33.636700,-84.427864,KATL,33.636337,-84.128435
19,PIC reported UAS off left side at same altitud...,1.25 NM N CLT,CLT,1.25,N,2.3150,0,Charlotte/Douglas Intl,35.213750,-80.949056,KCLT,35.234616,-80.949056
20,PIC reported UAS at 12 o'clock position at sam...,2 NM E PHX,PHX,2.00,E,3.7040,90,Phoenix Sky Harbor Intl,33.434278,-112.011583,KPHX,33.434271,-111.971752
21,PIC reported UAS at 9 o'clock position at same...,4 NM NW DAL,DAL,4.00,NW,7.4080,315,Dallas Love Fld,32.845945,-96.850877,KDAL,32.893165,-96.906861
22,"PIC reported a UAS pass 2,000FT below while WN...",5 NM SW STL,STL,5.00,SW,9.2600,225,St Louis Lambert Intl,38.748697,-90.370029,KSTL,38.689689,-90.445288
23,PIC reported a blue helicopter type UAS 20FT o...,6 NM NE PWK,PWK,6.00,NE,11.1120,45,Chicago Exec,42.114279,-87.901541,KPWK,42.184979,-87.806427
24,"PIC reported a UAS while ESE bound at 1,600FT ...",10 NM NW JFK,JFK,10.00,NW,18.5200,315,John F Kennedy Intl,40.639928,-73.778693,KJFK,40.757751,-73.933776
25,PIC reported a UAS at 12 o'clock 400FT below w...,6 NM E PHX,PHX,6.00,E,11.1120,90,Phoenix Sky Harbor Intl,33.434278,-112.011583,KPHX,33.434220,-111.892090
26,"PIC reported a white UAS at 11,000FT while NNW...",20 NM S DEN,DEN,20.00,S,37.0400,180,Denver Intl,39.861667,-104.673167,KDEN,39.528059,-104.673167
27,"PIC reported a black quad-copter at 1,000FT wh...",10 NM S BUR,BUR,10.00,S,18.5200,180,Bob Hope,34.200694,-118.358667,KBUR,34.033734,-118.358667
28,Pilot reported a black UAS 500 feet below airc...,7 NM SW LGA,LGA,7.00,SW,12.9640,225,Laguardia,40.777250,-73.872611,KLGA,40.694650,-73.981067
29,Pilot reported a UAS operating 600 feet to 800...,1.5 NM NW SGJ,SGJ,1.50,NW,2.7780,315,Northeast Florida Rgnl,29.959252,-81.339732,KSGJ,29.976971,-81.360087
30,"PIC reported a UAS above while WSW bound at 7,...",30 NM NE LAX,LAX,30.00,NE,55.5600,45,Los Angeles Intl,33.942496,-118.408049,KLAX,34.295934,-117.981312
31,"The PIC reporteda black quadcopter UAS at 3,50...",10 NM N PDK,PDK,10.00,N,18.5200,0,Dekalb-Peachtree,33.876002,-84.302031,KPDK,34.042967,-84.302031
32,"PIC observed a UAS at 6,000FT while S bound at...",1.5 NM NE SLC,SLC,1.50,NE,2.7780,45,Salt Lake City Intl,40.788388,-111.977773,KSLC,40.806074,-111.954494
33,PIC reported a grey quadcopter UAS 200FT above...,5 NM NE JFK,JFK,5.00,NE,9.2600,45,John F Kennedy Intl,40.639928,-73.778693,KJFK,40.698866,-73.701219
34,PIC reported a black UAS operating at 300FT 0....,0.5 NM NE ORL,ORL,0.50,NE,0.9260,45,Exec,28.545462,-81.332930,KORL,28.551370,-81.326239
35,PIC reported a white phantom quad-copter UAS o...,2 NM NW MIA,MIA,2.00,NW,3.7040,315,Miami Intl,25.795361,-80.290116,KMIA,25.819000,-80.316236
36,PIC reported a quadcopter UAS while ESE bound ...,30 NM SSW SLC,SLC,30.00,SSW,55.5600,203,Salt Lake City Intl,40.788388,-111.977773,KSLC,40.327542,-112.233218
37,PIC reported a dark green UAS at the 11 o'cloc...,10 NM WSW IAH,IAH,10.00,WSW,18.5200,248,George Bush Intcntl/Houston,29.984435,-95.341442,KIAH,29.921730,-95.519271
38,Reported a UAS left side of aircraft at same a...,3 NM NE LGA,LGA,3.00,NE,5.5560,45,Laguardia,40.777250,-73.872611,KLGA,40.812618,-73.826048
39,Aircraft reported UAS off the leftat same alti...,10 NM WNW PHX,PHX,10.00,WNW,18.5200,293,Phoenix Sky Harbor Intl,33.434278,-112.011583,KPHX,33.499386,-112.195044
40,PIC reported a white rotorcraft from the 12 o'...,12 NM E PHX,PHX,12.00,E,22.2240,90,Phoenix Sky Harbor Intl,33.434278,-112.011583,KPHX,33.434048,-111.772597
41,PIC reported a UAS at it's 12 o'clock position...,8.5 NM NE PHL,PHL,8.50,NE,15.7420,45,Philadelphia Intl,39.872084,-75.240663,KPHL,39.972263,-75.110364
42,Report of a black and red quad copter UAS at 6...,2 NM E LAX,LAX,2.00,E,3.7040,90,Los Angeles Intl,33.942496,-118.408049,KLAX,33.942490,-118.367982
43,"Reported a near miss with a whiteUAS at 2,600f...",6 NM E SMD,SMD,6.00,E,11.1120,90,Smith Fld,41.143361,-85.152778,KSMD,41.143285,-85.020418
44,"Reported a UAS while W bound at 10,000 feet 27...",27 NM N DEN,DEN,27.00,N,50.0040,0,Denver Intl,39.861667,-104.673167,KDEN,40.312006,-104.673167
45,Reported a sliver UAS at 10 o'clock and half a...,27 NM N MCO,MCO,27.00,N,50.0040,0,Orlando Intl,28.429389,-81.309000,KMCO,28.880566,-81.309000
46,Airport employee reported a UAS operating at a...,1 NM S MER,MER,1.00,S,1.8520,180,Castle,37.380484,-120.568186,KMER,37.363797,-120.568186
47,Security Forces picked up a UAS on scanner fre...,.5 NM NE MGE,MGE,0.50,NE,0.9260,45,Dobbins ARB,33.914442,-84.514247,KMGE,33.920345,-84.507166
48,Joint Base Pearl Harbor-Hickam Command Post re...,3 NM NW HNL,HNL,3.00,NW,5.5560,315,Daniel K Inouye Intl,21.317817,-157.920227,PHNL,21.353296,-157.958104

In [30]:
# Export dataframe to csv file
new_df2 = new_df2.drop(['Distance','Bearing','Distance_Kilometers','Bearing_Degrees','ICAO_ID'], 1)
new_df2 = new_df2.rename({'Airport_Longitude': 'Origin_Longitude', 'Airport_Latitude': 'Origin_Latitude'}, axis=1)
new_df2 = pd.merge(new_df2, nonstd, on='REMARKS', how='left')
new_df2.to_csv('COMPLETED-Non-std-49Airports.csv', index = False)

In [ ]:
############################################################################################################################

In [78]:
# Check the remaining records that may reference airports
nonstd1 = nonstd[nonstd['DATASET'] == 'AIRPORT(?)']
nonstd1

,REMARKS,dateonly,timeonly,DATE,CALLSIGN,POD,PRIMARYCODE,SECONDARYCODES,REPORTINGFACILITY,MORID.CEDAR,...,ACALTITUDE.CEDAR,ACHEADING.CEDAR,RELATIVECLOCKPOSITION.CEDAR,UASLONG.CEDAR,UASLAT.CEDAR,SUMMARY.CEDAR,QAFINDINGS.CEDAR,DATASET,UASLOCATION,RWYLOCATION
0,ATCT personnel reported observing a large UAS ...,1/4/2018,10:50,2018-01-04T10:50Z,NaN,DEN,UAS,NaN,SHV,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT(?),1 NM SW of SHV,NaN
1,Reported a UAS 400 feet below off the left sid...,1/15/2018,7:35,2018-01-15T07:35Z,N6522,DEN,UAS,NaN,POC,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT(?),1.5 NM NW of POC,NaN
2,Reported sighting a UAS below the aircraft whi...,1/21/2018,6:00,2018-01-21T06:00Z,RAKE06,DEN,UAS,NaN,PHX,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT(?),4.2 NM N of PHX,NaN
3,Pilot observed a 3 foot diameter Quad-copter o...,1/22/2018,1:26,2018-01-22T01:26Z,N31NW,DEN,UAS,NaN,A80,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT(?),24 NM NE of A80,NaN
4,Reported observing a white UAS operating 2 NM ...,1/26/2018,23:31,2018-01-26T23:31Z,NKS832,DEN,UAS,NaN,MCO,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT(?),2 NM S of MCO,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
406,Massachusetts State Police notified the tower ...,4/27/2021,21:30,2021-04-27T21:30Z,NaN,DEN,UAS,NaN,BED,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT(?),1 NM S of BED,NaN
407,RVS ATCT directly observes and has received mu...,5/1/2021,18:31,2021-05-01T18:31Z,NaN,DEN,UAS,MOR,RVS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT(?),1 NM SE of RVS,NaN
409,Local pilot provided in-person report of a sin...,6/11/2021,21:38,2021-06-11T21:38Z,NaN,DEN,UAS,MOR,TKA,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT(?),1 NM W of TKA,NaN
410,1820 EDT / 2220 UTC 6/27/2021\r\nN78ER C172 wa...,6/27/2021,22:07,2021-06-27T22:07Z,N78ER,JATOC,UAS,NaN,BWI,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT(?),10 NM SW of BWI,NaN
411,1448 EDT / 1848 UTC 06/29/2021\r\nN5088L obse...,6/29/2021,18:29,2021-06-29T18:29Z,N5088L,JATOC,UAS,NaN,ALB,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT(?),1 NM W of ALB,NaN

In [79]:
# Export these records to csv file
nonstd1.to_csv('362Exploratory.csv', index = False)

In [80]:
nonstd1 = pd.read_csv('C:/Users/Olga/Desktop/GMU/DAEN690/LEGO/362Exploratory.csv')
nonstd1

,REMARKS,dateonly,timeonly,DATE,CALLSIGN,POD,PRIMARYCODE,SECONDARYCODES,REPORTINGFACILITY,MORID.CEDAR,...,ACALTITUDE.CEDAR,ACHEADING.CEDAR,RELATIVECLOCKPOSITION.CEDAR,UASLONG.CEDAR,UASLAT.CEDAR,SUMMARY.CEDAR,QAFINDINGS.CEDAR,DATASET,UASLOCATION,RWYLOCATION
0,ATCT personnel reported observing a large UAS ...,1/4/2018,10:50,2018-01-04T10:50Z,NaN,DEN,UAS,NaN,SHV,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT(?),1 NM SW of SHV,NaN
1,Reported a UAS 400 feet below off the left sid...,1/15/2018,7:35,2018-01-15T07:35Z,N6522,DEN,UAS,NaN,POC,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT(?),1.5 NM NW of POC,NaN
2,Reported sighting a UAS below the aircraft whi...,1/21/2018,6:00,2018-01-21T06:00Z,RAKE06,DEN,UAS,NaN,PHX,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT(?),4.2 NM N of PHX,NaN
3,Pilot observed a 3 foot diameter Quad-copter o...,1/22/2018,1:26,2018-01-22T01:26Z,N31NW,DEN,UAS,NaN,A80,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT(?),24 NM NE of A80,NaN
4,Reported observing a white UAS operating 2 NM ...,1/26/2018,23:31,2018-01-26T23:31Z,NKS832,DEN,UAS,NaN,MCO,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT(?),2 NM S of MCO,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
357,Massachusetts State Police notified the tower ...,4/27/2021,21:30,2021-04-27T21:30Z,NaN,DEN,UAS,NaN,BED,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT(?),1 NM S of BED,NaN
358,RVS ATCT directly observes and has received mu...,5/1/2021,18:31,2021-05-01T18:31Z,NaN,DEN,UAS,MOR,RVS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT(?),1 NM SE of RVS,NaN
359,Local pilot provided in-person report of a sin...,6/11/2021,21:38,2021-06-11T21:38Z,NaN,DEN,UAS,MOR,TKA,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT(?),1 NM W of TKA,NaN
360,1820 EDT / 2220 UTC 6/27/2021\r\nN78ER C172 wa...,6/27/2021,22:07,2021-06-27T22:07Z,N78ER,JATOC,UAS,NaN,BWI,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT(?),10 NM SW of BWI,NaN
361,1448 EDT / 1848 UTC 06/29/2021\r\nN5088L obse...,6/29/2021,18:29,2021-06-29T18:29Z,N5088L,JATOC,UAS,NaN,ALB,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT(?),1 NM W of ALB,NaN

In [81]:
# Extract IDENTs from UASLOCATION columns
uas_loc = nonstd1['UASLOCATION'].tolist()
uas_airport = []

for i in range(len(uas_loc)):
    airport = uas_loc[i].split(' ')[-1]
    
    if len(airport) <= 4:
        uas_airport.append(airport)
    else:
        trim_air = airport[-3:]
        uas_airport.append(trim_air)

uas_airport_df = pd.DataFrame()
uas_airport_df['IDENT'] = uas_airport
uas_airport_df

    IDENT
0     SHV
1     POC
2     PHX
3     A80
4     MCO
..    ...
357   BED
358   RVS
359   TKA
360   BWI
361   ALB

[362 rows x 1 columns]

In [82]:
# Merge dataframe with airports dataset
uas_airport_loc= pd.merge(uas_airport_df, airports, on='IDENT', how='left')
uas_airport_loc

,IDENT,NAME,LATITUDE,LONGITUDE,ICAO_ID
0,SHV,Shreveport Rgnl,32.446528,-93.826028,KSHV
1,POC,Brackett Fld,34.091667,-117.781778,KPOC
2,PHX,Phoenix Sky Harbor Intl,33.434278,-112.011583,KPHX
3,A80,NaN,NaN,NaN,NaN
4,MCO,Orlando Intl,28.429389,-81.309000,KMCO
...,...,...,...,...,...
357,BED,Laurence G Hanscom Fld,42.469944,-71.289000,KBED
358,RVS,Richard Lloyd Jones Jr,36.039584,-95.984595,KRVS
359,TKA,Talkeetna,62.321372,-150.092718,PATK
360,BWI,Baltimore/Washington Intl Thurgood Marshall,39.175728,-76.668991,KBWI
361,ALB,Albany Intl,42.749116,-73.801980,KALB

In [83]:
# Add needed columns
add_col1 = nonstd1['REMARKS'].tolist()
uas_airport_loc['REMARKS'] = add_col1
add_col2 = nonstd1['UASLOCATION'].tolist()
uas_airport_loc['UASLOCATION'] = add_col2
uas_airport_loc

,IDENT,NAME,LATITUDE,LONGITUDE,ICAO_ID,REMARKS,UASLOCATION
0,SHV,Shreveport Rgnl,32.446528,-93.826028,KSHV,ATCT personnel reported observing a large UAS ...,1 NM SW of SHV
1,POC,Brackett Fld,34.091667,-117.781778,KPOC,Reported a UAS 400 feet below off the left sid...,1.5 NM NW of POC
2,PHX,Phoenix Sky Harbor Intl,33.434278,-112.011583,KPHX,Reported sighting a UAS below the aircraft whi...,4.2 NM N of PHX
3,A80,NaN,NaN,NaN,NaN,Pilot observed a 3 foot diameter Quad-copter o...,24 NM NE of A80
4,MCO,Orlando Intl,28.429389,-81.309000,KMCO,Reported observing a white UAS operating 2 NM ...,2 NM S of MCO
...,...,...,...,...,...,...,...
357,BED,Laurence G Hanscom Fld,42.469944,-71.289000,KBED,Massachusetts State Police notified the tower ...,1 NM S of BED
358,RVS,Richard Lloyd Jones Jr,36.039584,-95.984595,KRVS,RVS ATCT directly observes and has received mu...,1 NM SE of RVS
359,TKA,Talkeetna,62.321372,-150.092718,PATK,Local pilot provided in-person report of a sin...,1 NM W of TKA
360,BWI,Baltimore/Washington Intl Thurgood Marshall,39.175728,-76.668991,KBWI,1820 EDT / 2220 UTC 6/27/2021\r\nN78ER C172 wa...,10 NM SW of BWI
361,ALB,Albany Intl,42.749116,-73.801980,KALB,1448 EDT / 1848 UTC 06/29/2021\r\nN5088L obse...,1 NM W of ALB

In [84]:
# Check records which reference airports
uas_airport_loc1 = uas_airport_loc[uas_airport_loc['NAME'].notnull()]
uas_airport_loc1

,IDENT,NAME,LATITUDE,LONGITUDE,ICAO_ID,REMARKS,UASLOCATION
0,SHV,Shreveport Rgnl,32.446528,-93.826028,KSHV,ATCT personnel reported observing a large UAS ...,1 NM SW of SHV
1,POC,Brackett Fld,34.091667,-117.781778,KPOC,Reported a UAS 400 feet below off the left sid...,1.5 NM NW of POC
2,PHX,Phoenix Sky Harbor Intl,33.434278,-112.011583,KPHX,Reported sighting a UAS below the aircraft whi...,4.2 NM N of PHX
4,MCO,Orlando Intl,28.429389,-81.309000,KMCO,Reported observing a white UAS operating 2 NM ...,2 NM S of MCO
6,LGA,Laguardia,40.777250,-73.872611,KLGA,Reported a red quad-copter UAS 4 NM E of LGA a...,4 NM E of LGA
...,...,...,...,...,...,...,...
357,BED,Laurence G Hanscom Fld,42.469944,-71.289000,KBED,Massachusetts State Police notified the tower ...,1 NM S of BED
358,RVS,Richard Lloyd Jones Jr,36.039584,-95.984595,KRVS,RVS ATCT directly observes and has received mu...,1 NM SE of RVS
359,TKA,Talkeetna,62.321372,-150.092718,PATK,Local pilot provided in-person report of a sin...,1 NM W of TKA
360,BWI,Baltimore/Washington Intl Thurgood Marshall,39.175728,-76.668991,KBWI,1820 EDT / 2220 UTC 6/27/2021\r\nN78ER C172 wa...,10 NM SW of BWI
361,ALB,Albany Intl,42.749116,-73.801980,KALB,1448 EDT / 1848 UTC 06/29/2021\r\nN5088L obse...,1 NM W of ALB

In [86]:
# Export these records to csv file
uas_airport_loc1.to_csv('214Airports.csv', index = False)

In [87]:
# Read in and modify UASLOCATION column to match
uas_airport_loc1 = pd.read_csv('C:/Users/Olga/Desktop/GMU/DAEN690/LEGO/214Airports.csv')
uas_airport_loc1['UASLOCATION'] = uas_airport_loc1['UASLOCATION'].str.upper()
uas_airport_loc1

,IDENT,NAME,LATITUDE,LONGITUDE,ICAO_ID,REMARKS,UASLOCATION
0,SHV,Shreveport Rgnl,32.446528,-93.826028,KSHV,ATCT personnel reported observing a large UAS ...,1 NM SW OF SHV
1,POC,Brackett Fld,34.091667,-117.781778,KPOC,Reported a UAS 400 feet below off the left sid...,1.5 NM NW OF POC
2,PHX,Phoenix Sky Harbor Intl,33.434278,-112.011583,KPHX,Reported sighting a UAS below the aircraft whi...,4.2 NM N OF PHX
3,MCO,Orlando Intl,28.429389,-81.309000,KMCO,Reported observing a white UAS operating 2 NM ...,2 NM S OF MCO
4,LGA,Laguardia,40.777250,-73.872611,KLGA,Reported a red quad-copter UAS 4 NM E of LGA a...,4 NM E OF LGA
...,...,...,...,...,...,...,...
209,BED,Laurence G Hanscom Fld,42.469944,-71.289000,KBED,Massachusetts State Police notified the tower ...,1 NM S OF BED
210,RVS,Richard Lloyd Jones Jr,36.039584,-95.984595,KRVS,RVS ATCT directly observes and has received mu...,1 NM SE OF RVS
211,TKA,Talkeetna,62.321372,-150.092718,PATK,Local pilot provided in-person report of a sin...,1 NM W OF TKA
212,BWI,Baltimore/Washington Intl Thurgood Marshall,39.175728,-76.668991,KBWI,1820 EDT / 2220 UTC 6/27/2021\r\nN78ER C172 wa...,10 NM SW OF BWI
213,ALB,Albany Intl,42.749116,-73.801980,KALB,1448 EDT / 1848 UTC 06/29/2021\r\nN5088L obse...,1 NM W OF ALB

In [88]:
# Find Bearing and distance and separate them in two columns
uas_loc = uas_airport_loc1['UASLOCATION']
distances = []
bearings = []

for i in range(len(uas_loc)):
    split = uas_loc[i].split(' ')[0:3]

    if 'NM' in split[0]: #if there is no space between the distance and NM (i.e. 3NM)
        distance_nm = split[0][0:len(split[0]) - 2]
        bearing_abrev = split[1].replace('of', '')
        
    else: 
        distance_nm = split[0]
        bearing_abrev = split[2].replace('of', '')
    
    distances.append(distance_nm[0:])
    bearings.append(bearing_abrev)

# Create new dataframe to save the new info
new_df = pd.DataFrame(uas_airport_loc1['REMARKS'])
new_df['UAS_LOC'] = uas_airport_loc1['UASLOCATION']
new_df['IDENT'] = uas_airport_loc1['IDENT']
new_df['Distance'] = distances
new_df['Bearing'] = bearings

new_df

,REMARKS,UAS_LOC,IDENT,Distance,Bearing
0,ATCT personnel reported observing a large UAS ...,1 NM SW OF SHV,SHV,1,SW
1,Reported a UAS 400 feet below off the left sid...,1.5 NM NW OF POC,POC,1.5,NW
2,Reported sighting a UAS below the aircraft whi...,4.2 NM N OF PHX,PHX,4.2,N
3,Reported observing a white UAS operating 2 NM ...,2 NM S OF MCO,MCO,2,S
4,Reported a red quad-copter UAS 4 NM E of LGA a...,4 NM E OF LGA,LGA,4,E
...,...,...,...,...,...
209,Massachusetts State Police notified the tower ...,1 NM S OF BED,BED,1,S
210,RVS ATCT directly observes and has received mu...,1 NM SE OF RVS,RVS,1,SE
211,Local pilot provided in-person report of a sin...,1 NM W OF TKA,TKA,1,W
212,1820 EDT / 2220 UTC 6/27/2021\r\nN78ER C172 wa...,10 NM SW OF BWI,BWI,10,SW
213,1448 EDT / 1848 UTC 06/29/2021\r\nN5088L obse...,1 NM W OF ALB,ALB,1,W

In [93]:
# Convert distnaces from NM to KM and convert bearing abbreviation to degrees
new_df['Distance'] = pd.to_numeric(new_df['Distance'],errors = 'coerce')
dist_kilo = []

for i in range(len(new_df)):
    distanceKilo = new_df['Distance'][i] * 1.852 # converting NM to kilometers
    dist_kilo.append(distanceKilo)

bearDegree = pd.DataFrame(new_df['Bearing'])
bearDegree = bearDegree.replace({'Bearing': bearing_deg})

new_df['Distance_Kilometers'] = dist_kilo
new_df['Bearing_Degrees'] = bearDegree
new_df['Airport_Latitude'] = uas_airport_loc1['LATITUDE']
new_df['Airport_Longitude'] = uas_airport_loc1['LONGITUDE']

new_df2 = pd.merge(new_df, airports, on='IDENT', how='left')
new_df2 = new_df2.drop(['Airport_Latitude', 'Airport_Longitude'], 1)
new_df2 = new_df2.rename({'LONGITUDE': 'Airport_Longitude', 'LATITUDE': 'Airport_Latitude'}, axis=1)
new_df2

,REMARKS,UAS_LOC,IDENT,Distance,Bearing,Distance_Kilometers,Bearing_Degrees,NAME,Airport_Latitude,Airport_Longitude,ICAO_ID
0,ATCT personnel reported observing a large UAS ...,1 NM SW OF SHV,SHV,1.0,SW,1.8520,225,Shreveport Rgnl,32.446528,-93.826028,KSHV
1,Reported a UAS 400 feet below off the left sid...,1.5 NM NW OF POC,POC,1.5,NW,2.7780,315,Brackett Fld,34.091667,-117.781778,KPOC
2,Reported sighting a UAS below the aircraft whi...,4.2 NM N OF PHX,PHX,4.2,N,7.7784,0,Phoenix Sky Harbor Intl,33.434278,-112.011583,KPHX
3,Reported observing a white UAS operating 2 NM ...,2 NM S OF MCO,MCO,2.0,S,3.7040,180,Orlando Intl,28.429389,-81.309000,KMCO
4,Reported a red quad-copter UAS 4 NM E of LGA a...,4 NM E OF LGA,LGA,4.0,E,7.4080,90,Laguardia,40.777250,-73.872611,KLGA
...,...,...,...,...,...,...,...,...,...,...,...
209,Massachusetts State Police notified the tower ...,1 NM S OF BED,BED,1.0,S,1.8520,180,Laurence G Hanscom Fld,42.469944,-71.289000,KBED
210,RVS ATCT directly observes and has received mu...,1 NM SE OF RVS,RVS,1.0,SE,1.8520,135,Richard Lloyd Jones Jr,36.039584,-95.984595,KRVS
211,Local pilot provided in-person report of a sin...,1 NM W OF TKA,TKA,1.0,W,1.8520,270,Talkeetna,62.321372,-150.092718,PATK
212,1820 EDT / 2220 UTC 6/27/2021\r\nN78ER C172 wa...,10 NM SW OF BWI,BWI,10.0,SW,18.5200,225,Baltimore/Washington Intl Thurgood Marshall,39.175728,-76.668991,KBWI
213,1448 EDT / 1848 UTC 06/29/2021\r\nN5088L obse...,1 NM W OF ALB,ALB,1.0,W,1.8520,270,Albany Intl,42.749116,-73.801980,KALB

In [94]:
# Calculate UAS lat/long
uas_lat = []
uas_long = []

for i in range(len(new_df)):
    lat_airport = pd.to_numeric(new_df2['Airport_Latitude'][i],errors='ignore')
    long_airport = pd.to_numeric(new_df2['Airport_Longitude'][i],errors='ignore')
    b = pd.to_numeric(new_df['Bearing_Degrees'][i],errors='ignore')
    d = pd.to_numeric(new_df['Distance_Kilometers'][i],errors='ignore')
    
    origin = geopy.Point(lat_airport, long_airport)
    
    destination = geodesic(kilometers=d).destination(origin,b)
    
    lat2, lon2, = destination.latitude, destination.longitude
    
    uas_lat.append(lat2)
    uas_long.append(lon2)


# Append UAS Lat/Long information to DataFrame
new_df2['UAS_Latitude'] = uas_lat
new_df2['UAS_Longitude'] = uas_long
new_df2

,REMARKS,UAS_LOC,IDENT,Distance,Bearing,Distance_Kilometers,Bearing_Degrees,NAME,Airport_Latitude,Airport_Longitude,ICAO_ID,UAS_Latitude,UAS_Longitude
0,ATCT personnel reported observing a large UAS ...,1 NM SW OF SHV,SHV,1.0,SW,1.8520,225,Shreveport Rgnl,32.446528,-93.826028,KSHV,32.434718,-93.839953
1,Reported a UAS 400 feet below off the left sid...,1.5 NM NW OF POC,POC,1.5,NW,2.7780,315,Brackett Fld,34.091667,-117.781778,KPOC,34.109374,-117.803068
2,Reported sighting a UAS below the aircraft whi...,4.2 NM N OF PHX,PHX,4.2,N,7.7784,0,Phoenix Sky Harbor Intl,33.434278,-112.011583,KPHX,33.504409,-112.011583
3,Reported observing a white UAS operating 2 NM ...,2 NM S OF MCO,MCO,2.0,S,3.7040,180,Orlando Intl,28.429389,-81.309000,KMCO,28.395967,-81.309000
4,Reported a red quad-copter UAS 4 NM E of LGA a...,4 NM E OF LGA,LGA,4.0,E,7.4080,90,Laguardia,40.777250,-73.872611,KLGA,40.777217,-73.784857
...,...,...,...,...,...,...,...,...,...,...,...,...,...
209,Massachusetts State Police notified the tower ...,1 NM S OF BED,BED,1.0,S,1.8520,180,Laurence G Hanscom Fld,42.469944,-71.289000,KBED,42.453272,-71.289000
210,RVS ATCT directly observes and has received mu...,1 NM SE OF RVS,RVS,1.0,SE,1.8520,135,Richard Lloyd Jones Jr,36.039584,-95.984595,KRVS,36.027781,-95.970066
211,Local pilot provided in-person report of a sin...,1 NM W OF TKA,TKA,1.0,W,1.8520,270,Talkeetna,62.321372,-150.092718,PATK,62.321367,-150.128440
212,1820 EDT / 2220 UTC 6/27/2021\r\nN78ER C172 wa...,10 NM SW OF BWI,BWI,10.0,SW,18.5200,225,Baltimore/Washington Intl Thurgood Marshall,39.175728,-76.668991,KBWI,39.057670,-76.820287
213,1448 EDT / 1848 UTC 06/29/2021\r\nN5088L obse...,1 NM W OF ALB,ALB,1.0,W,1.8520,270,Albany Intl,42.749116,-73.801980,KALB,42.749114,-73.824601

In [95]:
# Export dataframe to csv file
new_df2 = new_df2.drop(['Distance','Bearing','Distance_Kilometers','Bearing_Degrees','ICAO_ID'], 1)
new_df2 = new_df2.rename({'Airport_Longitude': 'Origin_Longitude', 'Airport_Latitude': 'Origin_Latitude'}, axis=1)
new_df2 = pd.merge(new_df2, nonstd, on='REMARKS', how='left')
new_df2.to_csv('COMPLETED-Non-std-214Airports.csv', index = False)

In [ ]:
###############################################################################################################

In [96]:
# Check the remaining values if reference NAVAID
uas_nav_loc = uas_airport_loc[uas_airport_loc['NAME'].isnull()]
uas_nav_loc = uas_nav_loc.drop(['NAME', 'LATITUDE', 'LONGITUDE', 'ICAO_ID'], axis=1)
uas_nav_loc

,IDENT,REMARKS,UASLOCATION
3,A80,Pilot observed a 3 foot diameter Quad-copter o...,24 NM NE of A80
5,NCT,"Reported observing a UAS 1,000 to 2,000 feet b...",18 NM SE of NCT
11,P50,"Reported observing a UAS while at 3,500 feet, ...",3 NM NE of P50
12,S46,"Observed a UAS at 5,000 feet, 13 NM SE of Seat...",13 NM SE of S46
18,F11,Reported observing a UAS with red and green li...,17 NM ESE of F11
...,...,...,...
342,WOC,A concerned citizen reported two large UAS ove...,5 NM W of WOC
343,WOC,Aircraft observed two UAS passing underneath w...,17 NM SW of WOC
344,PCT,Aircraft (VM374) observed a UAS while E bound ...,5 NM S of PCT
347,USSS,USSS notified NCRCC a UAS had been detected at...,2.5 NM NW of USSS
348,PCT,"N347PD, CJ4, observed a UAS 1/2 NM W of ANP at...",1/2 NM W of PCT

In [97]:
# Read in NAVAID dataset
navaid = pd.read_csv('C:/Users/Olga/Desktop/GMU/DAEN690/LEGO/NAVAID_Cleaned.csv')
navaid

       LONGITUDE   LATITUDE IDENT        NAME_TXT
0    -176.676024  51.871896   ADK   MOUNT MOFFETT
1    -151.744257  68.136626   AKP  ANAKTUVUK PASS
2    -149.960164  61.167868   TED       ANCHORAGE
3    -149.769204  61.255004   EDF       ELMENDORF
4    -159.597931  61.590169   ANI           ANIAK
...          ...        ...   ...             ...
1669 -156.788152  71.273426   BRW          BARROW
1670 -156.781302  71.282300   VIR     BROWERVILLE
1671  -75.164524  43.026523   UCA           UTICA
1672  -90.434470  40.937351   GBG       GALESBURG
1673 -104.804750  47.133380   GDV        GLENDIVE

[1674 rows x 4 columns]

In [98]:
# Merge dataframe with NAVAID dataset
join_uas_nav = pd.merge(uas_nav_loc, navaid, on='IDENT', how='left')
join_uas_nav

,IDENT,REMARKS,UASLOCATION,LONGITUDE,LATITUDE,NAME_TXT
0,A80,Pilot observed a 3 foot diameter Quad-copter o...,24 NM NE of A80,NaN,NaN,NaN
1,NCT,"Reported observing a UAS 1,000 to 2,000 feet b...",18 NM SE of NCT,NaN,NaN,NaN
2,P50,"Reported observing a UAS while at 3,500 feet, ...",3 NM NE of P50,NaN,NaN,NaN
3,S46,"Observed a UAS at 5,000 feet, 13 NM SE of Seat...",13 NM SE of S46,NaN,NaN,NaN
4,F11,Reported observing a UAS with red and green li...,17 NM ESE of F11,NaN,NaN,NaN
...,...,...,...,...,...,...
143,WOC,A concerned citizen reported two large UAS ove...,5 NM W of WOC,NaN,NaN,NaN
144,WOC,Aircraft observed two UAS passing underneath w...,17 NM SW of WOC,NaN,NaN,NaN
145,PCT,Aircraft (VM374) observed a UAS while E bound ...,5 NM S of PCT,NaN,NaN,NaN
146,USSS,USSS notified NCRCC a UAS had been detected at...,2.5 NM NW of USSS,NaN,NaN,NaN
147,PCT,"N347PD, CJ4, observed a UAS 1/2 NM W of ANP at...",1/2 NM W of PCT,NaN,NaN,NaN

In [99]:
# Check non null records
nav_loc = join_uas_nav[join_uas_nav['NAME_TXT'].notnull()]
nav_loc

,IDENT,REMARKS,UASLOCATION,LONGITUDE,LATITUDE,NAME_TXT
138,ZHU,PIC reported a black UAS 200 feet below their ...,3 NM N of ZHU,-73.346935,45.564084,HAUTS-BOIS

In [101]:
# Only one record references NAVAID
final_df2 = pd.merge(nav_loc, nonstd1, on='REMARKS', how='left')
final_df2

,IDENT,REMARKS,UASLOCATION_x,LONGITUDE,LATITUDE,NAME_TXT,dateonly,timeonly,DATE,CALLSIGN,...,ACALTITUDE.CEDAR,ACHEADING.CEDAR,RELATIVECLOCKPOSITION.CEDAR,UASLONG.CEDAR,UASLAT.CEDAR,SUMMARY.CEDAR,QAFINDINGS.CEDAR,DATASET,UASLOCATION_y,RWYLOCATION
0,ZHU,PIC reported a black UAS 200 feet below their ...,3 NM N of ZHU,-73.346935,45.564084,HAUTS-BOIS,7/10/2019,4:18,2019-07-10T04:18Z,ASQ4217,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT(?),3 NM N of ZHU,NaN

In [109]:
# add UASLOCATION to nav_loc
add_col3 = final_df2['UASLOCATION_y'].tolist()
nav_loc['UASLOCATION'] = add_col3
nav_loc

,IDENT,REMARKS,UASLOCATION,LONGITUDE,LATITUDE,NAME_TXT
0,ZHU,PIC reported a black UAS 200 feet below their ...,3 NM N of ZHU,-73.346935,45.564084,HAUTS-BOIS

In [110]:
# Export dataframe to csv file
nav_loc.to_csv('1NAVAID.csv', index = False)

nav_loc = pd.read_csv('C:/Users/Olga/Desktop/GMU/DAEN690/LEGO/1NAVAID.csv')

In [111]:
# Find bearing and distance and separate them in two columns
uas_loc = nav_loc['UASLOCATION']
distances = []
bearings = []

for i in range(len(uas_loc)):
    split = uas_loc[i].split(' ')[0:3]
    
    if 'NM' in split[0]: #if there is no space between the distance and NM (i.e. 3NM)
        distance_nm = split[0][0:len(split[0]) - 2]
        bearing_abrev = split[1].replace('of', '')
        
    else: 
        distance_nm = split[0]
        bearing_abrev = split[2].replace('of', '')
    
    distances.append(float(distance_nm))
    bearings.append(bearing_abrev)
    

# Create DataFrame to store UAS Location Information
new_df = pd.DataFrame(nav_loc['REMARKS'])
new_df['UASLOCATION'] = nav_loc['UASLOCATION']
new_df['IDENT'] = nav_loc['IDENT']
new_df['Distance'] = distances
new_df['Bearing'] = bearings
new_df['NAME_TXT'] = nav_loc['NAME_TXT']

new_df

,REMARKS,UASLOCATION,IDENT,Distance,Bearing,NAME_TXT
0,PIC reported a black UAS 200 feet below their ...,3 NM N of ZHU,ZHU,3.0,N,HAUTS-BOIS

In [112]:
# Convert distance from NM to KM and bearing to degrees
dist_kilo = []

for i in range(len(new_df)):
    distanceKilo = new_df['Distance'][i] * 1.852 # converting NM to kilometers
    dist_kilo.append(distanceKilo)

bearDegree = pd.DataFrame(new_df['Bearing'])
bearDegree = bearDegree.replace({'Bearing': bearing_deg})

new_df['Distance_Kilometers'] = dist_kilo
new_df['Bearing_Degrees'] = bearDegree
new_df['NAVAID_Latitude'] = nav_loc['LATITUDE']
new_df['NAVAID_Longitude'] = nav_loc['LONGITUDE']
new_df['NAME_TXT'] = nav_loc['NAME_TXT']

new_df

,REMARKS,UASLOCATION,IDENT,Distance,Bearing,NAME_TXT,Distance_Kilometers,Bearing_Degrees,NAVAID_Latitude,NAVAID_Longitude
0,PIC reported a black UAS 200 feet below their ...,3 NM N of ZHU,ZHU,3.0,N,HAUTS-BOIS,5.556,0,45.564084,-73.346935

In [113]:
# Calculate UAS lat/long
uas_lat = []
uas_long = []


for i in range(len(new_df)):
    lat_nav = pd.to_numeric(new_df['NAVAID_Latitude'][i])
    long_nav = pd.to_numeric(new_df['NAVAID_Longitude'][i])
    b = pd.to_numeric(new_df['Bearing_Degrees'][i])
    d = pd.to_numeric(new_df['Distance_Kilometers'][i])
    
    origin = geopy.Point(lat_nav, long_nav)
    destination = geodesic(kilometers=d).destination(origin,b)
    
    lat2, lon2, = destination.latitude, destination.longitude
    
    uas_lat.append(lat2)
    uas_long.append(lon2)
    
# Append UAS Lat/Long information to DataFrame
new_df['UAS_Latitude'] = uas_lat
new_df['UAS_Longitude'] = uas_long


new_df

,REMARKS,UASLOCATION,IDENT,Distance,Bearing,NAME_TXT,Distance_Kilometers,Bearing_Degrees,NAVAID_Latitude,NAVAID_Longitude,UAS_Latitude,UAS_Longitude
0,PIC reported a black UAS 200 feet below their ...,3 NM N of ZHU,ZHU,3.0,N,HAUTS-BOIS,5.556,0,45.564084,-73.346935,45.614074,-73.346935

In [114]:
# Export to csv file
new_df = new_df.drop(['Distance','Bearing','Distance_Kilometers','Bearing_Degrees'], 1)
new_df = new_df.rename({'NAVAID_Longitude': 'Origin_Longitude', 'NAVAID_Latitude': 'Origin_Latitude', 'NAME_TXT': 'NAME'}, axis=1)
new_df = pd.merge(new_df, nonstd, on='REMARKS', how='left')
new_df.to_csv('COMPLETED-Non-std-1NAVAID.csv', index = False)

In [ ]:
####################################################################################################################

In [134]:
# Find the remaining records 
remaining = join_uas_nav[join_uas_nav['NAME_TXT'].isnull()]
remaining = remaining.drop(['NAME_TXT', 'LATITUDE', 'LONGITUDE'], axis=1)
remaining

    IDENT                                            REMARKS
0     A80  Pilot observed a 3 foot diameter Quad-copter o...
1     NCT  Reported observing a UAS 1,000 to 2,000 feet b...
2     P50  Reported observing a UAS while at 3,500 feet, ...
3     S46  Observed a UAS at 5,000 feet, 13 NM SE of Seat...
4     F11  Reported observing a UAS with red and green li...
..    ...                                                ...
143   WOC  A concerned citizen reported two large UAS ove...
144   WOC  Aircraft observed two UAS passing underneath w...
145   PCT  Aircraft (VM374) observed a UAS while E bound ...
146  USSS  USSS notified NCRCC a UAS had been detected at...
147   PCT  N347PD, CJ4, observed a UAS 1/2 NM W of ANP at...

[147 rows x 2 columns]

In [135]:
# Merge the records back with original dataset for further use
df = pd.merge(remaining, nonstd1, on='REMARKS', how='left')
df

,IDENT,REMARKS,dateonly,timeonly,DATE,CALLSIGN,POD,PRIMARYCODE,SECONDARYCODES,REPORTINGFACILITY,...,ACALTITUDE.CEDAR,ACHEADING.CEDAR,RELATIVECLOCKPOSITION.CEDAR,UASLONG.CEDAR,UASLAT.CEDAR,SUMMARY.CEDAR,QAFINDINGS.CEDAR,DATASET,UASLOCATION,RWYLOCATION
0,A80,Pilot observed a 3 foot diameter Quad-copter o...,1/22/2018,1:26,2018-01-22T01:26Z,N31NW,DEN,UAS,NaN,A80,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT(?),24 NM NE of A80,NaN
1,NCT,"Reported observing a UAS 1,000 to 2,000 feet b...",1/28/2018,21:30,2018-01-28T21:30Z,UAL400,DEN,UAS,NaN,NCT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT(?),18 NM SE of NCT,NaN
2,P50,"Reported observing a UAS while at 3,500 feet, ...",2/12/2018,5:15,2018-02-12T05:15Z,N169ME,DEN,UAS,NaN,P50,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT(?),3 NM NE of P50,NaN
3,S46,"Observed a UAS at 5,000 feet, 13 NM SE of Seat...",2/12/2018,7:22,2018-02-12T07:22Z,DAL1838,DEN,UAS,NaN,S46,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT(?),13 NM SE of S46,NaN
4,F11,Reported observing a UAS with red and green li...,2/19/2018,12:05,2018-02-19T12:05Z,N449ND,DEN,UAS,NaN,F11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT(?),17 NM ESE of F11,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142,WOC,A concerned citizen reported two large UAS ove...,2/3/2020,1:20,2020-02-03T01:20Z,NaN,DEN,UAS,NaN,WOC,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT(?),5 NM W of WOC,NaN
143,WOC,Aircraft observed two UAS passing underneath w...,3/23/2020,17:30,2020-03-23T17:30Z,N545AP,DEN,UAS,NaN,WOC,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT(?),17 NM SW of WOC,NaN
144,PCT,Aircraft (VM374) observed a UAS while E bound ...,5/23/2020,22:22,2020-05-23T22:22Z,VM374,NCRCC,UAS,NaN,PCT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT(?),5 NM S of PCT,NaN
145,USSS,USSS notified NCRCC a UAS had been detected at...,8/26/2020,0:15,2020-08-26T00:15Z,NaN,NCRCC,NORAD-COORDINATION,"LAW ENFORCEMENT, UAS",USSS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT(?),2.5 NM NW of USSS,NaN
146,PCT,"N347PD, CJ4, observed a UAS 1/2 NM W of ANP at...",9/21/2020,16:22,2020-09-21T16:22Z,NaN,NCRCC,UAS,NaN,PCT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT(?),1/2 NM W of PCT,NaN

In [137]:
# Export to csv file
df.to_csv('Output_All_Points_Non-Standard_147Remaining.csv', index = False)

In [61]:
# Fine DEsignated point record and save it in csv file
des_point = nonstd[nonstd['DATASET'] == 'DESIGNATED POINT']
des_point

,REMARKS,dateonly,timeonly,DATE,CALLSIGN,POD,PRIMARYCODE,SECONDARYCODES,REPORTINGFACILITY,MORID.CEDAR,...,ACALTITUDE.CEDAR,ACHEADING.CEDAR,RELATIVECLOCKPOSITION.CEDAR,UASLONG.CEDAR,UASLAT.CEDAR,SUMMARY.CEDAR,QAFINDINGS.CEDAR,DATASET,UASLOCATION,RWYLOCATION
263,SEA ATCT advised UAS activity reported by King...,11/20/2018,3:01,2018-11-20T03:01Z,NaN,DEN,UAS,NaN,SEA,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DESIGNATED POINT,.25 NM SW of SEATA,NaN

In [62]:
des_point.to_csv('Non-std-1DesignatedPoint.csv', index = False)