## This notebook explores 60 records that were kicked back from Lex's R code. 
### The output of this notebook is:
#### 1. 45 Lat/Long calculated for FAA Airport Identifier
#### 2. 2 + 9  Lat/Long calculated for NAVAID
#### 3. 3 Fixed Radial to be explored
#### 4. 1 Record (back to Lex)

In [1]:
# Import libraries
import pandas as pd
import numpy as np
import geopy
from geopy.distance import geodesic

In [2]:
# Read in csv file
nonstd = pd.read_csv('C:/Users/Olga/Desktop/GMU/DAEN690/LEGO/Olga_All_Points_Non-Standard_60OUTOF65.csv')
nonstd

,IDENT,REMARKS,OLD_UASLOCATION,dateonly,timeonly,DATE,CALLSIGN,POD,PRIMARYCODE,SECONDARYCODES,...,ACALTITUDE.CEDAR,ACHEADING.CEDAR,RELATIVECLOCKPOSITION.CEDAR,UASLONG.CEDAR,UASLAT.CEDAR,SUMMARY.CEDAR,QAFINDINGS.CEDAR,RWYLOCATION,DATASET,NEW_UASLOCATION
0,NCT,"Reported a uas while NE bound at 4,500 feet 5 ...",5 NM N NCT,1/16/2018,3:14,2018-01-16T03:14Z,N4905S,NCRCC,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NAVAID,5 NM N of SAC
1,N90,Observed a uas off the right side while SW bou...,9 NM ESE N90,1/25/2018,3:44,2018-01-25T03:44Z,RPA5972,NCRCC,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,9 NM ESE LGA
2,A80,"Reported a white quad-copter uas at 1,800 feet...",4 NM N A80,1/26/2018,0:05,2018-01-26T00:05Z,N20HX,NCRCC,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,4 NM N of PDK
3,C90,Reported a small quad-copter uas 200 feet abov...,15 NM E of C90,1/26/2018,22:58,2018-01-26T22:58Z,AWI3872,NCRCC,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,15 NM E of ORD
4,A80,"Reported a uas while at 3,500 feet W bound 8 E...",8 NM E A80,2/18/2018,1:37,2018-02-18T01:37Z,EDV3433,NCRCC,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,8 NM E ATL
5,I90,Reported a red uas onthe left side 200 feet ab...,18 NM E of I90,2/18/2018,3:06,2018-02-18T03:06Z,SWA4136,NCRCC,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,18 NM E of HOU
6,SWL,VACAPES reported SaltyDog25 reported a uas 500...,16 NM SSE of SWL,4/30/2018,23:02,2018-04-30T23:02Z,SDT25,DEN,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NAVAID,16 NM SSE of SWL
7,GGT,"Aircraft W bound at 6,700 feet reported a 3 fo...",12 NM SW GGT,7/1/2018,22:10,2018-07-01T22:10Z,N900PK,DEN,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NAVAID,12 NM SW GGT
8,ZAU,PIC reported flying over a red and white fixed...,4 NM E ZAU,7/7/2018,23:11,2018-07-07T23:11Z,N929TG,DEN,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,4 NM E of C92
9,N90,PIC observed a uas at the 12 o'clock position ...,4 NM NW N90,7/8/2018,5:59,2018-07-08T05:59Z,SWA3085,DEN,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,4 NM NW LGA
10,S56,PIC reported 2 rotor craft uas while N bound a...,8 NM N S56,7/20/2018,1:31,2018-07-20T01:31Z,DAL2846,DEN,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,8 NM N SLC
11,ZSE,"PIC reported a uas 1,000FT below Aircraft at 1...",20 NM ENE ZSE,7/20/2018,6:15,2018-07-20T06:15Z,ASA1080,DEN,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NAVAID,20 NM ENE of SEA
12,F11,"Aircraft at 2,500 feet reported a white uas 1,...",6 NM SSE F11,7/22/2018,22:10,2018-07-22T22:10Z,N13986,DEN,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,6 NM SSE MCO
13,C90,Reported uas approximately 1 foot in diameter ...,6 NM S of C90,7/28/2018,5:52,2018-07-28T05:52Z,NKS948,DEN,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,6 NM S of ORD
14,S46,PIC reported a orange fixed wing uas while in ...,15 NM W of S46,7/29/2018,3:42,2018-07-29T03:42Z,N3506T,DEN,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NAVAID,15 NM W of SEA
15,L30,"Reported a uas while W bound at 8,000 FT 20 E ...",20 NM E L30,7/29/2018,7:20,2018-07-29T07:20Z,FFT765,DEN,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,20 NM E LAS
16,S46,"Aircraft reported A uas 11 N SEA at 3,500 feet...",11 NM N S46,8/13/2018,4:47,2018-08-13T04:47Z,ASA96,DEN,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,11 NM N SEA
17,N90,Reported a white quad copter uas off the left ...,5 NM S of N90,8/25/2018,0:29,2018-08-25T00:29Z,N7166E,DEN,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,5 NM S of SHI
18,SCT,Reported a black quadcopter uas while WSW boun...,9 NM E of SCT,8/26/2018,5:05,2018-08-26T05:05Z,NAX7087,DEN,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,9 NM E of LAX
19,P50,"Reported a uas at 2,000 feet below aircraft wh...",15 NM NNE of P50,8/26/2018,6:10,2018-08-26T06:10Z,AAL686,DEN,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,15 NM NNE of PHX
20,Y90,Reported a uas 100-300 feet above the aircraft...,7 NM SW of Y90,8/31/2018,3:35,2018-08-31T03:35Z,JBU2020,DEN,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,7 NM SW of ORH
21,D01,Reported a uas 600 feet above aircraft while S...,10 NM SW of D01,9/15/2018,8:49,2018-09-15T08:49Z,LYM2116,DEN,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,10 NM SW of APA
22,WOC,Reported a black and yellow quad copter uas ho...,28 NM W of WOC,9/23/2018,22:01,2018-09-23T22:01Z,N2604,DEN,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,28 NM W of ORD
23,A90,Reported observing a large blue and white uas ...,15 NM NE A90,11/7/2018,22:02,2018-11-07T22:02Z,EDV5521,CONR,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,15 NM NE BOS
24,F11,Reported a blue and orange uas below Aircraft ...,24 NM NNW F11,11/18/2018,1:08,2018-11-18T01:08Z,N120PA,CONR,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,24 NM NNW of MLB
25,ZMA,"Observed a uas while E bound at 400 feet, 1 E ...",1 NM E of ZMA,11/20/2018,4:06,2018-11-20T04:06Z,LPE2462,CONR,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,1 NM E of MIA
26,N90,Aircraft reported hitting a uas with the nose ...,8 NM N N90,11/22/2018,8:16,2018-11-22T08:16Z,ASQ4276,DEN,UAS,PAGED,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,8 NM N EWR
27,A80,Reported a gray and white uas 200 feet below a...,11 NM NE A80,11/23/2018,21:44,2018-11-23T21:44Z,LN911VG,CONR,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,11 NM NE of RYY
28,N90,"Reported a yellow uas while S bound at 3,700 f...",5 NM W of N90,12/28/2018,3:50,2018-12-28T03:50Z,UAL1573,DEN,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,5 NM W of LGA
29,NCT,Reported a quad-copter uas 300 feet off the le...,11 NM NW of NCT,12/28/2018,6:38,2018-12-28T06:38Z,CMP384,DEN,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,11 NM NW of SJC
30,ZBW,Reported a green uas while SW bound 200 feet a...,15 NM SW of ZBW,1/1/2019,23:47,2019-01-01T23:47Z,PDT4972,DEN,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,15 NM SW of CCC
31,N90,Reported a uas at the same altitude while NNW ...,6 NM NNW of N90,1/10/2019,8:14,2019-01-10T08:14Z,SWA276,DEN,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,6 NM NNW of LGA
32,RCC,"DCA-1: Incident occurred at 1835 (1335L), firs...",675 NM N NCRCC,2/16/2019,2:36,2019-02-16T02:36Z,NaN,NCRCC,UAS,LAW ENFORCEMENT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FIXED RADIAL DISTANCE,3.5 NM 300 of DCA
33,P50,Reported a uas at same altitude while W bound ...,10 NM WNW of P50,2/25/2019,23:19,2019-02-25T23:19Z,SWA37,DEN,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,10 NM WNW of PHX
34,ZAB,Reported a uas within 100 feet while E bound a...,33 NM NE of ZAB,2/25/2019,23:21,2019-02-25T23:21Z,AAL2025,DEN,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,33 NM NE of PHX
35,D01,"Reported a small silver uas 1,000 feet below a...",4 NM E of D01,3/18/2019,1:26,2019-03-18T01:26Z,RPA3720,DEN,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,4 NM E of DEN
36,D10,Reported a white uas 500 feet below aircraft w...,5 NM E of D10,3/18/2019,3:27,2019-03-18T03:27Z,N56BU,DEN,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,5 NM E of DAL
37,I90,Reported a 6 foot in diameter white quad copte...,15 NM S of I90,3/18/2019,4:23,2019-03-18T04:23Z,N341N,DEN,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,15 NM S of IAH
38,MFH,Reported a white medium sized uas pass 100 fee...,9 NM NW MFH,3/19/2019,5:52,2019-03-19T05:52Z,N621PD,DEN,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NAVAID,9 NM NW of PQF
39,A80,Aircraft observed uas 35 NW of ATL. No evasive...,35 NM NW of A80,3/25/2019,2:02,2019-03-25T02:02Z,SKW3628,DEN,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,35 NM NW of ATL
40,A80,Reported silver uas while Ebound at 8000 feet ...,15 NM NNW A80,4/1/2019,2:54,2019-04-01T02:54Z,N750DV,DEN,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NAVAID,15 NM NNW of AHN
41,I90,"Reported a red uas while N bound at 15,000 fee...",5 NM E of I90,4/1/2019,4:43,2019-04-01T04:43Z,N123HK,DEN,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,5 NM E of IAH
42,S46,Reported a red uas at 3 o'clock 500 feet below...,12 NM SSE of S46,4/1/2019,4:53,2019-04-01T04:53Z,DAL2215,DEN,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,12 NM SSE of SEA
43,SW1,Reported a black quadcopter uas from 10 o'cloc...,10 NM ENE of SW1,4/22/2019,8:51,2019-04-22T08:51Z,DAL574,DEN,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,10 NM ENE of LAX
44,C90,"Reported a fixed wing uas 1,500 feet below air...",10 NM E of C90,5/5/2019,23:09,2019-05-05T23:09Z,SKW2998,DEN,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,10 NM E of ORD
45,I90,Reported a white uas passing below aircraft wh...,35 NM ESE of I90,5/15/2019,6:21,2019-05-15T06:21Z,ASH6036,DEN,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,35 NM ESE of IAH
46,A90,Reported a white and black quadcopter off the ...,13 NM S of A90,5/18/2019,21:05,2019-05-18T21:05Z,FFT1238,DEN,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,13 NM S of BOS
47,N90,Reported a uas at 12 o'clock position at same ...,8 NM NW of N90,5/27/2019,4:50,2019-05-27T04:50Z,UAL1476,DEN,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,8 NM NW of TEB
48,I90,Reported black and white uas while W bound at ...,10 NM N I90,6/8/2019,5:36,2019-06-08T05:36Z,N44411,DEN,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,10 NM N HOU
49,NCT,Reported a shiny uas from the 12 o'clock posit...,6 NM NNE NCT,6/12/2019,21:20,2019-06-12T21:20Z,N86HD,DEN,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,6 NM NNE SFO
50,I90,Reported a uas 50 ft. below the aircraft. Airc...,15 NM W of I90,6/15/2019,5:50,2019-06-15T05:50Z,UAL2111,DEN,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,15 NM W of IAH
51,PCT,"Reported a possible uas 3 NE of BAL at 10,000 ...",3 NM NE of PCT,6/18/2019,20:32,2019-06-18T20:32Z,RPA5915,NCRCC,UAS,OTHER,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,3 NM NE of BAL
52,C90,"Reported a white, rotorcraft uas, operating at...",10 NM NW C90,6/26/2019,21:58,2019-06-26T21:58Z,N4973F,DEN,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NAVAID,10 NM NW of GCO
53,N90,"Reported a uas at 9 o'clock and 1,000 FT below...",5 NM W of N90,6/27/2019,5:16,2019-06-27T05:16Z,UCA4295,DEN,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,5 NM W of LGA
54,POI,Reported a white uas at 3 o'clock 200 FT below...,1 NM NE POI,6/27/2019,6:18,2019-06-27T06:18Z,LIMO82,DEN,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NAVAID,1 NM NE NTD
55,N90,Large black uas pass below aircraft. Aircraft ...,12 NM WSW N90,7/4/2019,23:58,2019-07-04T23:58Z,AAL1608,DEN,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,12 NM WSW LGA
56,C90,PIC reported a uas 100 feet above their aircra...,20 NM ESE of C90,7/11/2019,4:24,2019-07-11T04:24Z,UAL269,DEN,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,20 NM ESE of ORD
57,A80,Aircraft reported blue and white quad-copter u...,12 NM NE A80,3/3/2020,18:31,2020-03-03T18:31Z,EDV5398,DEN,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,12 NM NE ATL
58,USCP,TOI P-56A// DCA-1: USCP reported a MPD officer...,1100 NM N USCP,1/20/2021,15:25,2021-01-20T15:25Z,NaN,NCRCC,TOI-PA-P-56A,UAS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FIXED RADIAL DISTANCE,3 NM 036 of DCA
59,FED,"DCA-1: DCA072008, 1 NW of FEDEX Field, MUSEL18...",1 NM NW of FED,6/21/2021,18:56,2021-06-21T18:56Z,MUSEL18,NCRCC,UAS,"SUSPICIOUS ACTIVITY, TOI-NCR FRZ",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FIXED RADIAL DISTANCE,8 NM 072 of DCA

In [3]:
# Find records that reference airports
nonstd_air = nonstd[(nonstd['DATASET'] == 'AIRPORT')]
nonstd_air

,IDENT,REMARKS,OLD_UASLOCATION,dateonly,timeonly,DATE,CALLSIGN,POD,PRIMARYCODE,SECONDARYCODES,...,ACALTITUDE.CEDAR,ACHEADING.CEDAR,RELATIVECLOCKPOSITION.CEDAR,UASLONG.CEDAR,UASLAT.CEDAR,SUMMARY.CEDAR,QAFINDINGS.CEDAR,RWYLOCATION,DATASET,NEW_UASLOCATION
1,N90,Observed a uas off the right side while SW bou...,9 NM ESE N90,1/25/2018,3:44,2018-01-25T03:44Z,RPA5972,NCRCC,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,9 NM ESE LGA
2,A80,"Reported a white quad-copter uas at 1,800 feet...",4 NM N A80,1/26/2018,0:05,2018-01-26T00:05Z,N20HX,NCRCC,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,4 NM N of PDK
3,C90,Reported a small quad-copter uas 200 feet abov...,15 NM E of C90,1/26/2018,22:58,2018-01-26T22:58Z,AWI3872,NCRCC,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,15 NM E of ORD
4,A80,"Reported a uas while at 3,500 feet W bound 8 E...",8 NM E A80,2/18/2018,1:37,2018-02-18T01:37Z,EDV3433,NCRCC,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,8 NM E ATL
5,I90,Reported a red uas onthe left side 200 feet ab...,18 NM E of I90,2/18/2018,3:06,2018-02-18T03:06Z,SWA4136,NCRCC,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,18 NM E of HOU
8,ZAU,PIC reported flying over a red and white fixed...,4 NM E ZAU,7/7/2018,23:11,2018-07-07T23:11Z,N929TG,DEN,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,4 NM E of C92
9,N90,PIC observed a uas at the 12 o'clock position ...,4 NM NW N90,7/8/2018,5:59,2018-07-08T05:59Z,SWA3085,DEN,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,4 NM NW LGA
10,S56,PIC reported 2 rotor craft uas while N bound a...,8 NM N S56,7/20/2018,1:31,2018-07-20T01:31Z,DAL2846,DEN,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,8 NM N SLC
12,F11,"Aircraft at 2,500 feet reported a white uas 1,...",6 NM SSE F11,7/22/2018,22:10,2018-07-22T22:10Z,N13986,DEN,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,6 NM SSE MCO
13,C90,Reported uas approximately 1 foot in diameter ...,6 NM S of C90,7/28/2018,5:52,2018-07-28T05:52Z,NKS948,DEN,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,6 NM S of ORD
15,L30,"Reported a uas while W bound at 8,000 FT 20 E ...",20 NM E L30,7/29/2018,7:20,2018-07-29T07:20Z,FFT765,DEN,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,20 NM E LAS
16,S46,"Aircraft reported A uas 11 N SEA at 3,500 feet...",11 NM N S46,8/13/2018,4:47,2018-08-13T04:47Z,ASA96,DEN,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,11 NM N SEA
17,N90,Reported a white quad copter uas off the left ...,5 NM S of N90,8/25/2018,0:29,2018-08-25T00:29Z,N7166E,DEN,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,5 NM S of SHI
18,SCT,Reported a black quadcopter uas while WSW boun...,9 NM E of SCT,8/26/2018,5:05,2018-08-26T05:05Z,NAX7087,DEN,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,9 NM E of LAX
19,P50,"Reported a uas at 2,000 feet below aircraft wh...",15 NM NNE of P50,8/26/2018,6:10,2018-08-26T06:10Z,AAL686,DEN,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,15 NM NNE of PHX
20,Y90,Reported a uas 100-300 feet above the aircraft...,7 NM SW of Y90,8/31/2018,3:35,2018-08-31T03:35Z,JBU2020,DEN,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,7 NM SW of ORH
21,D01,Reported a uas 600 feet above aircraft while S...,10 NM SW of D01,9/15/2018,8:49,2018-09-15T08:49Z,LYM2116,DEN,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,10 NM SW of APA
22,WOC,Reported a black and yellow quad copter uas ho...,28 NM W of WOC,9/23/2018,22:01,2018-09-23T22:01Z,N2604,DEN,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,28 NM W of ORD
23,A90,Reported observing a large blue and white uas ...,15 NM NE A90,11/7/2018,22:02,2018-11-07T22:02Z,EDV5521,CONR,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,15 NM NE BOS
24,F11,Reported a blue and orange uas below Aircraft ...,24 NM NNW F11,11/18/2018,1:08,2018-11-18T01:08Z,N120PA,CONR,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,24 NM NNW of MLB
25,ZMA,"Observed a uas while E bound at 400 feet, 1 E ...",1 NM E of ZMA,11/20/2018,4:06,2018-11-20T04:06Z,LPE2462,CONR,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,1 NM E of MIA
26,N90,Aircraft reported hitting a uas with the nose ...,8 NM N N90,11/22/2018,8:16,2018-11-22T08:16Z,ASQ4276,DEN,UAS,PAGED,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,8 NM N EWR
27,A80,Reported a gray and white uas 200 feet below a...,11 NM NE A80,11/23/2018,21:44,2018-11-23T21:44Z,LN911VG,CONR,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,11 NM NE of RYY
28,N90,"Reported a yellow uas while S bound at 3,700 f...",5 NM W of N90,12/28/2018,3:50,2018-12-28T03:50Z,UAL1573,DEN,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,5 NM W of LGA
29,NCT,Reported a quad-copter uas 300 feet off the le...,11 NM NW of NCT,12/28/2018,6:38,2018-12-28T06:38Z,CMP384,DEN,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,11 NM NW of SJC
30,ZBW,Reported a green uas while SW bound 200 feet a...,15 NM SW of ZBW,1/1/2019,23:47,2019-01-01T23:47Z,PDT4972,DEN,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,15 NM SW of CCC
31,N90,Reported a uas at the same altitude while NNW ...,6 NM NNW of N90,1/10/2019,8:14,2019-01-10T08:14Z,SWA276,DEN,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,6 NM NNW of LGA
33,P50,Reported a uas at same altitude while W bound ...,10 NM WNW of P50,2/25/2019,23:19,2019-02-25T23:19Z,SWA37,DEN,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,10 NM WNW of PHX
34,ZAB,Reported a uas within 100 feet while E bound a...,33 NM NE of ZAB,2/25/2019,23:21,2019-02-25T23:21Z,AAL2025,DEN,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,33 NM NE of PHX
35,D01,"Reported a small silver uas 1,000 feet below a...",4 NM E of D01,3/18/2019,1:26,2019-03-18T01:26Z,RPA3720,DEN,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,4 NM E of DEN
36,D10,Reported a white uas 500 feet below aircraft w...,5 NM E of D10,3/18/2019,3:27,2019-03-18T03:27Z,N56BU,DEN,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,5 NM E of DAL
37,I90,Reported a 6 foot in diameter white quad copte...,15 NM S of I90,3/18/2019,4:23,2019-03-18T04:23Z,N341N,DEN,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,15 NM S of IAH
39,A80,Aircraft observed uas 35 NW of ATL. No evasive...,35 NM NW of A80,3/25/2019,2:02,2019-03-25T02:02Z,SKW3628,DEN,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,35 NM NW of ATL
41,I90,"Reported a red uas while N bound at 15,000 fee...",5 NM E of I90,4/1/2019,4:43,2019-04-01T04:43Z,N123HK,DEN,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,5 NM E of IAH
42,S46,Reported a red uas at 3 o'clock 500 feet below...,12 NM SSE of S46,4/1/2019,4:53,2019-04-01T04:53Z,DAL2215,DEN,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,12 NM SSE of SEA
43,SW1,Reported a black quadcopter uas from 10 o'cloc...,10 NM ENE of SW1,4/22/2019,8:51,2019-04-22T08:51Z,DAL574,DEN,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,10 NM ENE of LAX
44,C90,"Reported a fixed wing uas 1,500 feet below air...",10 NM E of C90,5/5/2019,23:09,2019-05-05T23:09Z,SKW2998,DEN,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,10 NM E of ORD
45,I90,Reported a white uas passing below aircraft wh...,35 NM ESE of I90,5/15/2019,6:21,2019-05-15T06:21Z,ASH6036,DEN,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,35 NM ESE of IAH
46,A90,Reported a white and black quadcopter off the ...,13 NM S of A90,5/18/2019,21:05,2019-05-18T21:05Z,FFT1238,DEN,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,13 NM S of BOS
47,N90,Reported a uas at 12 o'clock position at same ...,8 NM NW of N90,5/27/2019,4:50,2019-05-27T04:50Z,UAL1476,DEN,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,8 NM NW of TEB
48,I90,Reported black and white uas while W bound at ...,10 NM N I90,6/8/2019,5:36,2019-06-08T05:36Z,N44411,DEN,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,10 NM N HOU
49,NCT,Reported a shiny uas from the 12 o'clock posit...,6 NM NNE NCT,6/12/2019,21:20,2019-06-12T21:20Z,N86HD,DEN,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,6 NM NNE SFO
50,I90,Reported a uas 50 ft. below the aircraft. Airc...,15 NM W of I90,6/15/2019,5:50,2019-06-15T05:50Z,UAL2111,DEN,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,15 NM W of IAH
51,PCT,"Reported a possible uas 3 NE of BAL at 10,000 ...",3 NM NE of PCT,6/18/2019,20:32,2019-06-18T20:32Z,RPA5915,NCRCC,UAS,OTHER,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,3 NM NE of BAL
53,N90,"Reported a uas at 9 o'clock and 1,000 FT below...",5 NM W of N90,6/27/2019,5:16,2019-06-27T05:16Z,UCA4295,DEN,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,5 NM W of LGA
55,N90,Large black uas pass below aircraft. Aircraft ...,12 NM WSW N90,7/4/2019,23:58,2019-07-04T23:58Z,AAL1608,DEN,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,12 NM WSW LGA
56,C90,PIC reported a uas 100 feet above their aircra...,20 NM ESE of C90,7/11/2019,4:24,2019-07-11T04:24Z,UAL269,DEN,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,20 NM ESE of ORD
57,A80,Aircraft reported blue and white quad-copter u...,12 NM NE A80,3/3/2020,18:31,2020-03-03T18:31Z,EDV5398,DEN,UAS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIRPORT,12 NM NE ATL

In [4]:
# Extract Idents
uas_loc = nonstd_air['NEW_UASLOCATION'].tolist()
uas_airport = []

for i in range(len(uas_loc)):
    airport = uas_loc[i].split(' ')[-1]
    
    if len(airport) <= 4:
        uas_airport.append(airport)
    else:
        trim_air = airport[-3:]
        uas_airport.append(trim_air)
        
uas_airport_df = pd.DataFrame()
uas_airport_df['IDENT'] = uas_airport
uas_airport_df

   IDENT
0    LGA
1    PDK
2    ORD
3    ATL
4    HOU
5    C92
6    LGA
7    SLC
8    MCO
9    ORD
10   LAS
11   SEA
12   SHI
13   LAX
14   PHX
15   ORH
16   APA
17   ORD
18   BOS
19   MLB
20   MIA
21   EWR
22   RYY
23   LGA
24   SJC
25   CCC
26   LGA
27   PHX
28   PHX
29   DEN
30   DAL
31   IAH
32   ATL
33   IAH
34   SEA
35   LAX
36   ORD
37   IAH
38   BOS
39   TEB
40   HOU
41   SFO
42   IAH
43   BAL
44   LGA
45   LGA
46   ORD
47   ATL

In [5]:
# Read in airports dataset
airports = pd.read_csv('C:/Users/Olga/Desktop/GMU/DAEN690/LEGO/airports_cleaned.csv')

# Merge Idents dataframe with ariports dataset
uas_air_loc= pd.merge(uas_airport_df, airports, on='IDENT', how='left')
uas_air_loc

# Add needed columns
add_col = nonstd_air['REMARKS'].tolist()
uas_air_loc['REMARKS'] = add_col
add_col1 = nonstd_air['NEW_UASLOCATION'].tolist()
uas_air_loc['UASLOCATION'] = add_col1
uas_air_loc

,IDENT,NAME,LATITUDE,LONGITUDE,ICAO_ID,REMARKS,UASLOCATION
0,LGA,Laguardia,40.777250,-73.872611,KLGA,Observed a uas off the right side while SW bou...,9 NM ESE LGA
1,PDK,Dekalb-Peachtree,33.876002,-84.302031,KPDK,"Reported a white quad-copter uas at 1,800 feet...",4 NM N of PDK
2,ORD,Chicago O'hare Intl,41.976629,-87.907253,KORD,Reported a small quad-copter uas 200 feet abov...,15 NM E of ORD
3,ATL,Hartsfield - Jackson Atlanta Intl,33.636700,-84.427864,KATL,"Reported a uas while at 3,500 feet W bound 8 E...",8 NM E ATL
4,HOU,William P Hobby,29.645417,-95.278889,KHOU,Reported a red uas onthe left side 200 feet ab...,18 NM E of HOU
5,C92,Mentone,41.150043,-86.062497,NaN,PIC reported flying over a red and white fixed...,4 NM E of C92
6,LGA,Laguardia,40.777250,-73.872611,KLGA,PIC observed a uas at the 12 o'clock position ...,4 NM NW LGA
7,SLC,Salt Lake City Intl,40.788388,-111.977773,KSLC,PIC reported 2 rotor craft uas while N bound a...,8 NM N SLC
8,MCO,Orlando Intl,28.429389,-81.309000,KMCO,"Aircraft at 2,500 feet reported a white uas 1,...",6 NM SSE MCO
9,ORD,Chicago O'hare Intl,41.976629,-87.907253,KORD,Reported uas approximately 1 foot in diameter ...,6 NM S of ORD
10,LAS,Harry Reid Intl,36.080044,-115.152235,KLAS,"Reported a uas while W bound at 8,000 FT 20 E ...",20 NM E LAS
11,SEA,Seattle-Tacoma Intl,47.449889,-122.311778,KSEA,"Aircraft reported A uas 11 N SEA at 3,500 feet...",11 NM N SEA
12,SHI,NaN,NaN,NaN,NaN,Reported a white quad copter uas off the left ...,5 NM S of SHI
13,LAX,Los Angeles Intl,33.942496,-118.408049,KLAX,Reported a black quadcopter uas while WSW boun...,9 NM E of LAX
14,PHX,Phoenix Sky Harbor Intl,33.434278,-112.011583,KPHX,"Reported a uas at 2,000 feet below aircraft wh...",15 NM NNE of PHX
15,ORH,Worcester Rgnl,42.267139,-71.875611,KORH,Reported a uas 100-300 feet above the aircraft...,7 NM SW of ORH
16,APA,Centennial,39.570119,-104.849293,KAPA,Reported a uas 600 feet above aircraft while S...,10 NM SW of APA
17,ORD,Chicago O'hare Intl,41.976629,-87.907253,KORD,Reported a black and yellow quad copter uas ho...,28 NM W of ORD
18,BOS,General Edward Lawrence Logan Intl,42.362944,-71.006389,KBOS,Reported observing a large blue and white uas ...,15 NM NE BOS
19,MLB,Melbourne Orlando Intl,28.102750,-80.645250,KMLB,Reported a blue and orange uas below Aircraft ...,24 NM NNW of MLB
20,MIA,Miami Intl,25.795361,-80.290116,KMIA,"Observed a uas while E bound at 400 feet, 1 E ...",1 NM E of MIA
21,EWR,Newark Liberty Intl,40.692480,-74.168687,KEWR,Aircraft reported hitting a uas with the nose ...,8 NM N EWR
22,RYY,Cobb County Intl-McCollum Fld,34.013167,-84.597028,KRYY,Reported a gray and white uas 200 feet below a...,11 NM NE of RYY
23,LGA,Laguardia,40.777250,-73.872611,KLGA,"Reported a yellow uas while S bound at 3,700 f...",5 NM W of LGA
24,SJC,Norman Y Mineta San Jose Intl,37.362995,-121.928621,KSJC,Reported a quad-copter uas 300 feet off the le...,11 NM NW of SJC
25,CCC,NaN,NaN,NaN,NaN,Reported a green uas while SW bound 200 feet a...,15 NM SW of CCC
26,LGA,Laguardia,40.777250,-73.872611,KLGA,Reported a uas at the same altitude while NNW ...,6 NM NNW of LGA
27,PHX,Phoenix Sky Harbor Intl,33.434278,-112.011583,KPHX,Reported a uas at same altitude while W bound ...,10 NM WNW of PHX
28,PHX,Phoenix Sky Harbor Intl,33.434278,-112.011583,KPHX,Reported a uas within 100 feet while E bound a...,33 NM NE of PHX
29,DEN,Denver Intl,39.861667,-104.673167,KDEN,"Reported a small silver uas 1,000 feet below a...",4 NM E of DEN
30,DAL,Dallas Love Fld,32.845945,-96.850877,KDAL,Reported a white uas 500 feet below aircraft w...,5 NM E of DAL
31,IAH,George Bush Intcntl/Houston,29.984435,-95.341442,KIAH,Reported a 6 foot in diameter white quad copte...,15 NM S of IAH
32,ATL,Hartsfield - Jackson Atlanta Intl,33.636700,-84.427864,KATL,Aircraft observed uas 35 NW of ATL. No evasive...,35 NM NW of ATL
33,IAH,George Bush Intcntl/Houston,29.984435,-95.341442,KIAH,"Reported a red uas while N bound at 15,000 fee...",5 NM E of IAH
34,SEA,Seattle-Tacoma Intl,47.449889,-122.311778,KSEA,Reported a red uas at 3 o'clock 500 feet below...,12 NM SSE of SEA
35,LAX,Los Angeles Intl,33.942496,-118.408049,KLAX,Reported a black quadcopter uas from 10 o'cloc...,10 NM ENE of LAX
36,ORD,Chicago O'hare Intl,41.976629,-87.907253,KORD,"Reported a fixed wing uas 1,500 feet below air...",10 NM E of ORD
37,IAH,George Bush Intcntl/Houston,29.984435,-95.341442,KIAH,Reported a white uas passing below aircraft wh...,35 NM ESE of IAH
38,BOS,General Edward Lawrence Logan Intl,42.362944,-71.006389,KBOS,Reported a white and black quadcopter off the ...,13 NM S of BOS
39,TEB,Teterboro,40.850111,-74.060833,KTEB,Reported a uas at 12 o'clock position at same ...,8 NM NW of TEB
40,HOU,William P Hobby,29.645417,-95.278889,KHOU,Reported black and white uas while W bound at ...,10 NM N HOU
41,SFO,San Francisco Intl,37.618806,-122.375417,KSFO,Reported a shiny uas from the 12 o'clock posit...,6 NM NNE SFO
42,IAH,George Bush Intcntl/Houston,29.984435,-95.341442,KIAH,Reported a uas 50 ft. below the aircraft. Airc...,15 NM W of IAH
43,BAL,NaN,NaN,NaN,NaN,"Reported a possible uas 3 NE of BAL at 10,000 ...",3 NM NE of BAL
44,LGA,Laguardia,40.777250,-73.872611,KLGA,"Reported a uas at 9 o'clock and 1,000 FT below...",5 NM W of LGA
45,LGA,Laguardia,40.777250,-73.872611,KLGA,Large black uas pass below aircraft. Aircraft ...,12 NM WSW LGA
46,ORD,Chicago O'hare Intl,41.976629,-87.907253,KORD,PIC reported a uas 100 feet above their aircra...,20 NM ESE of ORD
47,ATL,Hartsfield - Jackson Atlanta Intl,33.636700,-84.427864,KATL,Aircraft reported blue and white quad-copter u...,12 NM NE ATL

In [6]:
#Create Dictionary for bearings and their degrees
bearing_deg = {
    'N' : 0,
    'NNE' : 23,
    'NE' : 45,
    'ENE' : 68,
    'E' : 90,
    'ESE' : 113,
    'SE' : 135,
    'SSE' : 158,
    'S' : 180,
    'SSW' : 203,
    'SW' : 225,
    'WSW' : 248,
    'W' : 270,
    'WNW' : 293,
    'NW' : 315,
    'NNW' : 338
}

# Separate distance and bearing in two columns
uas_loc = uas_air_loc['UASLOCATION']
distances = []
bearings = []

for i in range(len(uas_loc)):
    split = uas_loc[i].split(' ')[0:3]
    
    if 'NM' in split[0]: #if there is no space between the distance and NM (i.e. 3NM)
        distance_nm = split[0][0:len(split[0]) - 2]
        bearing_abrev = split[1].replace('of', '')
        
    else: 
        distance_nm = split[0]
        bearing_abrev = split[2].replace('of', '')
    
    distances.append(distance_nm[0:])
    bearings.append(bearing_abrev)

# Create DataFrame to store UAS Location Information
new_df = pd.DataFrame(uas_air_loc['REMARKS'])
new_df['UAS_LOC'] = uas_air_loc['UASLOCATION']
new_df['IDENT'] = uas_air_loc['IDENT']
new_df['Distance'] = distances
new_df['Bearing'] = bearings

new_df

,REMARKS,UAS_LOC,IDENT,Distance,Bearing
0,Observed a uas off the right side while SW bou...,9 NM ESE LGA,LGA,9,ESE
1,"Reported a white quad-copter uas at 1,800 feet...",4 NM N of PDK,PDK,4,N
2,Reported a small quad-copter uas 200 feet abov...,15 NM E of ORD,ORD,15,E
3,"Reported a uas while at 3,500 feet W bound 8 E...",8 NM E ATL,ATL,8,E
4,Reported a red uas onthe left side 200 feet ab...,18 NM E of HOU,HOU,18,E
5,PIC reported flying over a red and white fixed...,4 NM E of C92,C92,4,E
6,PIC observed a uas at the 12 o'clock position ...,4 NM NW LGA,LGA,4,NW
7,PIC reported 2 rotor craft uas while N bound a...,8 NM N SLC,SLC,8,N
8,"Aircraft at 2,500 feet reported a white uas 1,...",6 NM SSE MCO,MCO,6,SSE
9,Reported uas approximately 1 foot in diameter ...,6 NM S of ORD,ORD,6,S
10,"Reported a uas while W bound at 8,000 FT 20 E ...",20 NM E LAS,LAS,20,E
11,"Aircraft reported A uas 11 N SEA at 3,500 feet...",11 NM N SEA,SEA,11,N
12,Reported a white quad copter uas off the left ...,5 NM S of SHI,SHI,5,S
13,Reported a black quadcopter uas while WSW boun...,9 NM E of LAX,LAX,9,E
14,"Reported a uas at 2,000 feet below aircraft wh...",15 NM NNE of PHX,PHX,15,NNE
15,Reported a uas 100-300 feet above the aircraft...,7 NM SW of ORH,ORH,7,SW
16,Reported a uas 600 feet above aircraft while S...,10 NM SW of APA,APA,10,SW
17,Reported a black and yellow quad copter uas ho...,28 NM W of ORD,ORD,28,W
18,Reported observing a large blue and white uas ...,15 NM NE BOS,BOS,15,NE
19,Reported a blue and orange uas below Aircraft ...,24 NM NNW of MLB,MLB,24,NNW
20,"Observed a uas while E bound at 400 feet, 1 E ...",1 NM E of MIA,MIA,1,E
21,Aircraft reported hitting a uas with the nose ...,8 NM N EWR,EWR,8,N
22,Reported a gray and white uas 200 feet below a...,11 NM NE of RYY,RYY,11,NE
23,"Reported a yellow uas while S bound at 3,700 f...",5 NM W of LGA,LGA,5,W
24,Reported a quad-copter uas 300 feet off the le...,11 NM NW of SJC,SJC,11,NW
25,Reported a green uas while SW bound 200 feet a...,15 NM SW of CCC,CCC,15,SW
26,Reported a uas at the same altitude while NNW ...,6 NM NNW of LGA,LGA,6,NNW
27,Reported a uas at same altitude while W bound ...,10 NM WNW of PHX,PHX,10,WNW
28,Reported a uas within 100 feet while E bound a...,33 NM NE of PHX,PHX,33,NE
29,"Reported a small silver uas 1,000 feet below a...",4 NM E of DEN,DEN,4,E
30,Reported a white uas 500 feet below aircraft w...,5 NM E of DAL,DAL,5,E
31,Reported a 6 foot in diameter white quad copte...,15 NM S of IAH,IAH,15,S
32,Aircraft observed uas 35 NW of ATL. No evasive...,35 NM NW of ATL,ATL,35,NW
33,"Reported a red uas while N bound at 15,000 fee...",5 NM E of IAH,IAH,5,E
34,Reported a red uas at 3 o'clock 500 feet below...,12 NM SSE of SEA,SEA,12,SSE
35,Reported a black quadcopter uas from 10 o'cloc...,10 NM ENE of LAX,LAX,10,ENE
36,"Reported a fixed wing uas 1,500 feet below air...",10 NM E of ORD,ORD,10,E
37,Reported a white uas passing below aircraft wh...,35 NM ESE of IAH,IAH,35,ESE
38,Reported a white and black quadcopter off the ...,13 NM S of BOS,BOS,13,S
39,Reported a uas at 12 o'clock position at same ...,8 NM NW of TEB,TEB,8,NW
40,Reported black and white uas while W bound at ...,10 NM N HOU,HOU,10,N
41,Reported a shiny uas from the 12 o'clock posit...,6 NM NNE SFO,SFO,6,NNE
42,Reported a uas 50 ft. below the aircraft. Airc...,15 NM W of IAH,IAH,15,W
43,"Reported a possible uas 3 NE of BAL at 10,000 ...",3 NM NE of BAL,BAL,3,NE
44,"Reported a uas at 9 o'clock and 1,000 FT below...",5 NM W of LGA,LGA,5,W
45,Large black uas pass below aircraft. Aircraft ...,12 NM WSW LGA,LGA,12,WSW
46,PIC reported a uas 100 feet above their aircra...,20 NM ESE of ORD,ORD,20,ESE
47,Aircraft reported blue and white quad-copter u...,12 NM NE ATL,ATL,12,NE

In [26]:
# Converts distances from NM to KM and bearing to degrees
new_df['Distance'] = pd.to_numeric(new_df['Distance'],errors = 'coerce')
dist_kilo = []

for i in range(len(new_df)):
    distanceKilo = new_df['Distance'][i] * 1.852 # converting NM to kilometers
    dist_kilo.append(distanceKilo)

bearDegree = pd.DataFrame(new_df['Bearing'])
bearDegree = bearDegree.replace({'Bearing': bearing_deg})

new_df['Distance_Kilometers'] = dist_kilo
new_df['Bearing_Degrees'] = bearDegree
new_df['Airport_Latitude'] = uas_air_loc['LATITUDE']
new_df['Airport_Longitude'] = uas_air_loc['LONGITUDE']
new_df

new_df2 = pd.merge(new_df, airports, on='IDENT', how='left')
new_df2 = new_df2.drop(['Airport_Latitude', 'Airport_Longitude'], 1)
new_df2 = new_df2.rename({'LONGITUDE': 'Airport_Longitude', 'LATITUDE': 'Airport_Latitude'}, axis=1)
new_df2

,REMARKS,UAS_LOC,IDENT,Distance,Bearing,Distance_Kilometers,Bearing_Degrees,NAME,Airport_Latitude,Airport_Longitude,ICAO_ID
0,Observed a uas off the right side while SW bou...,9 NM ESE LGA,LGA,9,ESE,16.668,113,Laguardia,40.777250,-73.872611,KLGA
1,"Reported a white quad-copter uas at 1,800 feet...",4 NM N of PDK,PDK,4,N,7.408,0,Dekalb-Peachtree,33.876002,-84.302031,KPDK
2,Reported a small quad-copter uas 200 feet abov...,15 NM E of ORD,ORD,15,E,27.780,90,Chicago O'hare Intl,41.976629,-87.907253,KORD
3,"Reported a uas while at 3,500 feet W bound 8 E...",8 NM E ATL,ATL,8,E,14.816,90,Hartsfield - Jackson Atlanta Intl,33.636700,-84.427864,KATL
4,Reported a red uas onthe left side 200 feet ab...,18 NM E of HOU,HOU,18,E,33.336,90,William P Hobby,29.645417,-95.278889,KHOU
5,PIC reported flying over a red and white fixed...,4 NM E of C92,C92,4,E,7.408,90,Mentone,41.150043,-86.062497,NaN
6,PIC observed a uas at the 12 o'clock position ...,4 NM NW LGA,LGA,4,NW,7.408,315,Laguardia,40.777250,-73.872611,KLGA
7,PIC reported 2 rotor craft uas while N bound a...,8 NM N SLC,SLC,8,N,14.816,0,Salt Lake City Intl,40.788388,-111.977773,KSLC
8,"Aircraft at 2,500 feet reported a white uas 1,...",6 NM SSE MCO,MCO,6,SSE,11.112,158,Orlando Intl,28.429389,-81.309000,KMCO
9,Reported uas approximately 1 foot in diameter ...,6 NM S of ORD,ORD,6,S,11.112,180,Chicago O'hare Intl,41.976629,-87.907253,KORD
10,"Reported a uas while W bound at 8,000 FT 20 E ...",20 NM E LAS,LAS,20,E,37.040,90,Harry Reid Intl,36.080044,-115.152235,KLAS
11,"Aircraft reported A uas 11 N SEA at 3,500 feet...",11 NM N SEA,SEA,11,N,20.372,0,Seattle-Tacoma Intl,47.449889,-122.311778,KSEA
12,Reported a white quad copter uas off the left ...,5 NM S of SHI,SHI,5,S,9.260,180,NaN,NaN,NaN,NaN
13,Reported a black quadcopter uas while WSW boun...,9 NM E of LAX,LAX,9,E,16.668,90,Los Angeles Intl,33.942496,-118.408049,KLAX
14,"Reported a uas at 2,000 feet below aircraft wh...",15 NM NNE of PHX,PHX,15,NNE,27.780,23,Phoenix Sky Harbor Intl,33.434278,-112.011583,KPHX
15,Reported a uas 100-300 feet above the aircraft...,7 NM SW of ORH,ORH,7,SW,12.964,225,Worcester Rgnl,42.267139,-71.875611,KORH
16,Reported a uas 600 feet above aircraft while S...,10 NM SW of APA,APA,10,SW,18.520,225,Centennial,39.570119,-104.849293,KAPA
17,Reported a black and yellow quad copter uas ho...,28 NM W of ORD,ORD,28,W,51.856,270,Chicago O'hare Intl,41.976629,-87.907253,KORD
18,Reported observing a large blue and white uas ...,15 NM NE BOS,BOS,15,NE,27.780,45,General Edward Lawrence Logan Intl,42.362944,-71.006389,KBOS
19,Reported a blue and orange uas below Aircraft ...,24 NM NNW of MLB,MLB,24,NNW,44.448,338,Melbourne Orlando Intl,28.102750,-80.645250,KMLB
20,"Observed a uas while E bound at 400 feet, 1 E ...",1 NM E of MIA,MIA,1,E,1.852,90,Miami Intl,25.795361,-80.290116,KMIA
21,Aircraft reported hitting a uas with the nose ...,8 NM N EWR,EWR,8,N,14.816,0,Newark Liberty Intl,40.692480,-74.168687,KEWR
22,Reported a gray and white uas 200 feet below a...,11 NM NE of RYY,RYY,11,NE,20.372,45,Cobb County Intl-McCollum Fld,34.013167,-84.597028,KRYY
23,"Reported a yellow uas while S bound at 3,700 f...",5 NM W of LGA,LGA,5,W,9.260,270,Laguardia,40.777250,-73.872611,KLGA
24,Reported a quad-copter uas 300 feet off the le...,11 NM NW of SJC,SJC,11,NW,20.372,315,Norman Y Mineta San Jose Intl,37.362995,-121.928621,KSJC
25,Reported a green uas while SW bound 200 feet a...,15 NM SW of CCC,CCC,15,SW,27.780,225,NaN,NaN,NaN,NaN
26,Reported a uas at the same altitude while NNW ...,6 NM NNW of LGA,LGA,6,NNW,11.112,338,Laguardia,40.777250,-73.872611,KLGA
27,Reported a uas at same altitude while W bound ...,10 NM WNW of PHX,PHX,10,WNW,18.520,293,Phoenix Sky Harbor Intl,33.434278,-112.011583,KPHX
28,Reported a uas within 100 feet while E bound a...,33 NM NE of PHX,PHX,33,NE,61.116,45,Phoenix Sky Harbor Intl,33.434278,-112.011583,KPHX
29,"Reported a small silver uas 1,000 feet below a...",4 NM E of DEN,DEN,4,E,7.408,90,Denver Intl,39.861667,-104.673167,KDEN
30,Reported a white uas 500 feet below aircraft w...,5 NM E of DAL,DAL,5,E,9.260,90,Dallas Love Fld,32.845945,-96.850877,KDAL
31,Reported a 6 foot in diameter white quad copte...,15 NM S of IAH,IAH,15,S,27.780,180,George Bush Intcntl/Houston,29.984435,-95.341442,KIAH
32,Aircraft observed uas 35 NW of ATL. No evasive...,35 NM NW of ATL,ATL,35,NW,64.820,315,Hartsfield - Jackson Atlanta Intl,33.636700,-84.427864,KATL
33,"Reported a red uas while N bound at 15,000 fee...",5 NM E of IAH,IAH,5,E,9.260,90,George Bush Intcntl/Houston,29.984435,-95.341442,KIAH
34,Reported a red uas at 3 o'clock 500 feet below...,12 NM SSE of SEA,SEA,12,SSE,22.224,158,Seattle-Tacoma Intl,47.449889,-122.311778,KSEA
35,Reported a black quadcopter uas from 10 o'cloc...,10 NM ENE of LAX,LAX,10,ENE,18.520,68,Los Angeles Intl,33.942496,-118.408049,KLAX
36,"Reported a fixed wing uas 1,500 feet below air...",10 NM E of ORD,ORD,10,E,18.520,90,Chicago O'hare Intl,41.976629,-87.907253,KORD
37,Reported a white uas passing below aircraft wh...,35 NM ESE of IAH,IAH,35,ESE,64.820,113,George Bush Intcntl/Houston,29.984435,-95.341442,KIAH
38,Reported a white and black quadcopter off the ...,13 NM S of BOS,BOS,13,S,24.076,180,General Edward Lawrence Logan Intl,42.362944,-71.006389,KBOS
39,Reported a uas at 12 o'clock position at same ...,8 NM NW of TEB,TEB,8,NW,14.816,315,Teterboro,40.850111,-74.060833,KTEB
40,Reported black and white uas while W bound at ...,10 NM N HOU,HOU,10,N,18.520,0,William P Hobby,29.645417,-95.278889,KHOU
41,Reported a shiny uas from the 12 o'clock posit...,6 NM NNE SFO,SFO,6,NNE,11.112,23,San Francisco Intl,37.618806,-122.375417,KSFO
42,Reported a uas 50 ft. below the aircraft. Airc...,15 NM W of IAH,IAH,15,W,27.780,270,George Bush Intcntl/Houston,29.984435,-95.341442,KIAH
43,"Reported a possible uas 3 NE of BAL at 10,000 ...",3 NM NE of BAL,BAL,3,NE,5.556,45,NaN,NaN,NaN,NaN
44,"Reported a uas at 9 o'clock and 1,000 FT below...",5 NM W of LGA,LGA,5,W,9.260,270,Laguardia,40.777250,-73.872611,KLGA
45,Large black uas pass below aircraft. Aircraft ...,12 NM WSW LGA,LGA,12,WSW,22.224,248,Laguardia,40.777250,-73.872611,KLGA
46,PIC reported a uas 100 feet above their aircra...,20 NM ESE of ORD,ORD,20,ESE,37.040,113,Chicago O'hare Intl,41.976629,-87.907253,KORD
47,Aircraft reported blue and white quad-copter u...,12 NM NE ATL,ATL,12,NE,22.224,45,Hartsfield - Jackson Atlanta Intl,33.636700,-84.427864,KATL

In [8]:
# Find null values (records do not reference airport and save them in csv file)
not_air = new_df2[new_df2['Airport_Latitude'].isnull()]
not_air = not_air.drop(['NAME', 'Airport_Latitude', 'Airport_Longitude', 'ICAO_ID'], axis=1)

not_air.to_csv('Non-std-3NotAirports.csv', index = False)

In [27]:
# Continue with records that reference airports
new_df2 = new_df2[new_df2['Airport_Latitude'].notnull()]
new_df2.to_csv('Non-std-45Airports.csv', index = False)

new_df2 = pd.read_csv('C:/Users/Olga/Desktop/GMU/DAEN690/LEGO/Non-std-45Airports.csv')
new_df2

,REMARKS,UAS_LOC,IDENT,Distance,Bearing,Distance_Kilometers,Bearing_Degrees,NAME,Airport_Latitude,Airport_Longitude,ICAO_ID
0,Observed a uas off the right side while SW bou...,9 NM ESE LGA,LGA,9,ESE,16.668,113,Laguardia,40.777250,-73.872611,KLGA
1,"Reported a white quad-copter uas at 1,800 feet...",4 NM N of PDK,PDK,4,N,7.408,0,Dekalb-Peachtree,33.876002,-84.302031,KPDK
2,Reported a small quad-copter uas 200 feet abov...,15 NM E of ORD,ORD,15,E,27.780,90,Chicago O'hare Intl,41.976629,-87.907253,KORD
3,"Reported a uas while at 3,500 feet W bound 8 E...",8 NM E ATL,ATL,8,E,14.816,90,Hartsfield - Jackson Atlanta Intl,33.636700,-84.427864,KATL
4,Reported a red uas onthe left side 200 feet ab...,18 NM E of HOU,HOU,18,E,33.336,90,William P Hobby,29.645417,-95.278889,KHOU
5,PIC reported flying over a red and white fixed...,4 NM E of C92,C92,4,E,7.408,90,Mentone,41.150043,-86.062497,NaN
6,PIC observed a uas at the 12 o'clock position ...,4 NM NW LGA,LGA,4,NW,7.408,315,Laguardia,40.777250,-73.872611,KLGA
7,PIC reported 2 rotor craft uas while N bound a...,8 NM N SLC,SLC,8,N,14.816,0,Salt Lake City Intl,40.788388,-111.977773,KSLC
8,"Aircraft at 2,500 feet reported a white uas 1,...",6 NM SSE MCO,MCO,6,SSE,11.112,158,Orlando Intl,28.429389,-81.309000,KMCO
9,Reported uas approximately 1 foot in diameter ...,6 NM S of ORD,ORD,6,S,11.112,180,Chicago O'hare Intl,41.976629,-87.907253,KORD
10,"Reported a uas while W bound at 8,000 FT 20 E ...",20 NM E LAS,LAS,20,E,37.040,90,Harry Reid Intl,36.080044,-115.152235,KLAS
11,"Aircraft reported A uas 11 N SEA at 3,500 feet...",11 NM N SEA,SEA,11,N,20.372,0,Seattle-Tacoma Intl,47.449889,-122.311778,KSEA
12,Reported a black quadcopter uas while WSW boun...,9 NM E of LAX,LAX,9,E,16.668,90,Los Angeles Intl,33.942496,-118.408049,KLAX
13,"Reported a uas at 2,000 feet below aircraft wh...",15 NM NNE of PHX,PHX,15,NNE,27.780,23,Phoenix Sky Harbor Intl,33.434278,-112.011583,KPHX
14,Reported a uas 100-300 feet above the aircraft...,7 NM SW of ORH,ORH,7,SW,12.964,225,Worcester Rgnl,42.267139,-71.875611,KORH
15,Reported a uas 600 feet above aircraft while S...,10 NM SW of APA,APA,10,SW,18.520,225,Centennial,39.570119,-104.849293,KAPA
16,Reported a black and yellow quad copter uas ho...,28 NM W of ORD,ORD,28,W,51.856,270,Chicago O'hare Intl,41.976629,-87.907253,KORD
17,Reported observing a large blue and white uas ...,15 NM NE BOS,BOS,15,NE,27.780,45,General Edward Lawrence Logan Intl,42.362944,-71.006389,KBOS
18,Reported a blue and orange uas below Aircraft ...,24 NM NNW of MLB,MLB,24,NNW,44.448,338,Melbourne Orlando Intl,28.102750,-80.645250,KMLB
19,"Observed a uas while E bound at 400 feet, 1 E ...",1 NM E of MIA,MIA,1,E,1.852,90,Miami Intl,25.795361,-80.290116,KMIA
20,Aircraft reported hitting a uas with the nose ...,8 NM N EWR,EWR,8,N,14.816,0,Newark Liberty Intl,40.692480,-74.168687,KEWR
21,Reported a gray and white uas 200 feet below a...,11 NM NE of RYY,RYY,11,NE,20.372,45,Cobb County Intl-McCollum Fld,34.013167,-84.597028,KRYY
22,"Reported a yellow uas while S bound at 3,700 f...",5 NM W of LGA,LGA,5,W,9.260,270,Laguardia,40.777250,-73.872611,KLGA
23,Reported a quad-copter uas 300 feet off the le...,11 NM NW of SJC,SJC,11,NW,20.372,315,Norman Y Mineta San Jose Intl,37.362995,-121.928621,KSJC
24,Reported a uas at the same altitude while NNW ...,6 NM NNW of LGA,LGA,6,NNW,11.112,338,Laguardia,40.777250,-73.872611,KLGA
25,Reported a uas at same altitude while W bound ...,10 NM WNW of PHX,PHX,10,WNW,18.520,293,Phoenix Sky Harbor Intl,33.434278,-112.011583,KPHX
26,Reported a uas within 100 feet while E bound a...,33 NM NE of PHX,PHX,33,NE,61.116,45,Phoenix Sky Harbor Intl,33.434278,-112.011583,KPHX
27,"Reported a small silver uas 1,000 feet below a...",4 NM E of DEN,DEN,4,E,7.408,90,Denver Intl,39.861667,-104.673167,KDEN
28,Reported a white uas 500 feet below aircraft w...,5 NM E of DAL,DAL,5,E,9.260,90,Dallas Love Fld,32.845945,-96.850877,KDAL
29,Reported a 6 foot in diameter white quad copte...,15 NM S of IAH,IAH,15,S,27.780,180,George Bush Intcntl/Houston,29.984435,-95.341442,KIAH
30,Aircraft observed uas 35 NW of ATL. No evasive...,35 NM NW of ATL,ATL,35,NW,64.820,315,Hartsfield - Jackson Atlanta Intl,33.636700,-84.427864,KATL
31,"Reported a red uas while N bound at 15,000 fee...",5 NM E of IAH,IAH,5,E,9.260,90,George Bush Intcntl/Houston,29.984435,-95.341442,KIAH
32,Reported a red uas at 3 o'clock 500 feet below...,12 NM SSE of SEA,SEA,12,SSE,22.224,158,Seattle-Tacoma Intl,47.449889,-122.311778,KSEA
33,Reported a black quadcopter uas from 10 o'cloc...,10 NM ENE of LAX,LAX,10,ENE,18.520,68,Los Angeles Intl,33.942496,-118.408049,KLAX
34,"Reported a fixed wing uas 1,500 feet below air...",10 NM E of ORD,ORD,10,E,18.520,90,Chicago O'hare Intl,41.976629,-87.907253,KORD
35,Reported a white uas passing below aircraft wh...,35 NM ESE of IAH,IAH,35,ESE,64.820,113,George Bush Intcntl/Houston,29.984435,-95.341442,KIAH
36,Reported a white and black quadcopter off the ...,13 NM S of BOS,BOS,13,S,24.076,180,General Edward Lawrence Logan Intl,42.362944,-71.006389,KBOS
37,Reported a uas at 12 o'clock position at same ...,8 NM NW of TEB,TEB,8,NW,14.816,315,Teterboro,40.850111,-74.060833,KTEB
38,Reported black and white uas while W bound at ...,10 NM N HOU,HOU,10,N,18.520,0,William P Hobby,29.645417,-95.278889,KHOU
39,Reported a shiny uas from the 12 o'clock posit...,6 NM NNE SFO,SFO,6,NNE,11.112,23,San Francisco Intl,37.618806,-122.375417,KSFO
40,Reported a uas 50 ft. below the aircraft. Airc...,15 NM W of IAH,IAH,15,W,27.780,270,George Bush Intcntl/Houston,29.984435,-95.341442,KIAH
41,"Reported a uas at 9 o'clock and 1,000 FT below...",5 NM W of LGA,LGA,5,W,9.260,270,Laguardia,40.777250,-73.872611,KLGA
42,Large black uas pass below aircraft. Aircraft ...,12 NM WSW LGA,LGA,12,WSW,22.224,248,Laguardia,40.777250,-73.872611,KLGA
43,PIC reported a uas 100 feet above their aircra...,20 NM ESE of ORD,ORD,20,ESE,37.040,113,Chicago O'hare Intl,41.976629,-87.907253,KORD
44,Aircraft reported blue and white quad-copter u...,12 NM NE ATL,ATL,12,NE,22.224,45,Hartsfield - Jackson Atlanta Intl,33.636700,-84.427864,KATL

In [28]:
# Calculate UAS lat/long
uas_lat = []
uas_long = []

for i in range(len(new_df2)):
    lat_airport = pd.to_numeric(new_df2['Airport_Latitude'][i])
    long_airport = pd.to_numeric(new_df2['Airport_Longitude'][i])
    b = pd.to_numeric(new_df['Bearing_Degrees'][i])
    d = pd.to_numeric(new_df['Distance_Kilometers'][i])
    
    origin = geopy.Point(lat_airport, long_airport)
    destination = geodesic(kilometers=d).destination(origin,b)
    
    lat2, lon2, = destination.latitude, destination.longitude
    
    uas_lat.append(lat2)
    uas_long.append(lon2)

# Append UAS Lat/Long information to DataFrame
new_df2['UAS_Latitude'] = uas_lat
new_df2['UAS_Longitude'] = uas_long
new_df2

,REMARKS,UAS_LOC,IDENT,Distance,Bearing,Distance_Kilometers,Bearing_Degrees,NAME,Airport_Latitude,Airport_Longitude,ICAO_ID,UAS_Latitude,UAS_Longitude
0,Observed a uas off the right side while SW bou...,9 NM ESE LGA,LGA,9,ESE,16.668,113,Laguardia,40.777250,-73.872611,KLGA,40.718460,-73.691021
1,"Reported a white quad-copter uas at 1,800 feet...",4 NM N of PDK,PDK,4,N,7.408,0,Dekalb-Peachtree,33.876002,-84.302031,KPDK,33.942788,-84.302031
2,Reported a small quad-copter uas 200 feet abov...,15 NM E of ORD,ORD,15,E,27.780,90,Chicago O'hare Intl,41.976629,-87.907253,KORD,41.976140,-87.572076
3,"Reported a uas while at 3,500 feet W bound 8 E...",8 NM E ATL,ATL,8,E,14.816,90,Hartsfield - Jackson Atlanta Intl,33.636700,-84.427864,KATL,33.636596,-84.268168
4,Reported a red uas onthe left side 200 feet ab...,18 NM E of HOU,HOU,18,E,33.336,90,William P Hobby,29.645417,-95.278889,KHOU,29.644970,-94.934607
5,PIC reported flying over a red and white fixed...,4 NM E of C92,C92,4,E,7.408,90,Mentone,41.150043,-86.062497,NaN,41.150010,-85.974247
6,PIC observed a uas at the 12 o'clock position ...,4 NM NW LGA,LGA,4,NW,7.408,315,Laguardia,40.777250,-73.872611,KLGA,40.824403,-73.934706
7,PIC reported 2 rotor craft uas while N bound a...,8 NM N SLC,SLC,8,N,14.816,0,Salt Lake City Intl,40.788388,-111.977773,KSLC,40.921804,-111.977773
8,"Aircraft at 2,500 feet reported a white uas 1,...",6 NM SSE MCO,MCO,6,SSE,11.112,158,Orlando Intl,28.429389,-81.309000,KMCO,28.336418,-81.266548
9,Reported uas approximately 1 foot in diameter ...,6 NM S of ORD,ORD,6,S,11.112,180,Chicago O'hare Intl,41.976629,-87.907253,KORD,41.876586,-87.907253
10,"Reported a uas while W bound at 8,000 FT 20 E ...",20 NM E LAS,LAS,20,E,37.040,90,Harry Reid Intl,36.080044,-115.152235,KLAS,36.079338,-114.741013
11,"Aircraft reported A uas 11 N SEA at 3,500 feet...",11 NM N SEA,SEA,11,N,20.372,0,Seattle-Tacoma Intl,47.449889,-122.311778,KSEA,47.633121,-122.311778
12,Reported a black quadcopter uas while WSW boun...,9 NM E of LAX,LAX,9,E,16.668,90,Los Angeles Intl,33.942496,-118.408049,KLAX,33.859013,-118.408049
13,"Reported a uas at 2,000 feet below aircraft wh...",15 NM NNE of PHX,PHX,15,NNE,27.780,23,Phoenix Sky Harbor Intl,33.434278,-112.011583,KPHX,33.434148,-111.832344
14,Reported a uas 100-300 feet above the aircraft...,7 NM SW of ORH,ORH,7,SW,12.964,225,Worcester Rgnl,42.267139,-71.875611,KORH,42.497271,-71.743566
15,Reported a uas 600 feet above aircraft while S...,10 NM SW of APA,APA,10,SW,18.520,225,Centennial,39.570119,-104.849293,KAPA,39.487504,-104.955850
16,Reported a black and yellow quad copter uas ho...,28 NM W of ORD,ORD,28,W,51.856,270,Chicago O'hare Intl,41.976629,-87.907253,KORD,41.858618,-88.064967
17,Reported observing a large blue and white uas ...,15 NM NE BOS,BOS,15,NE,27.780,45,General Edward Lawrence Logan Intl,42.362944,-71.006389,KBOS,42.361216,-71.635864
18,Reported a blue and orange uas below Aircraft ...,24 NM NNW of MLB,MLB,24,NNW,44.448,338,Melbourne Orlando Intl,28.102750,-80.645250,KMLB,28.279855,-80.445025
19,"Observed a uas while E bound at 400 feet, 1 E ...",1 NM E of MIA,MIA,1,E,1.852,90,Miami Intl,25.795361,-80.290116,KMIA,26.167252,-80.456661
20,Aircraft reported hitting a uas with the nose ...,8 NM N EWR,EWR,8,N,14.816,0,Newark Liberty Intl,40.692480,-74.168687,KEWR,40.692478,-74.146776
21,Reported a gray and white uas 200 feet below a...,11 NM NE of RYY,RYY,11,NE,20.372,45,Cobb County Intl-McCollum Fld,34.013167,-84.597028,KRYY,34.146736,-84.597028
22,"Reported a yellow uas while S bound at 3,700 f...",5 NM W of LGA,LGA,5,W,9.260,270,Laguardia,40.777250,-73.872611,KLGA,40.906840,-73.701637
23,Reported a quad-copter uas 300 feet off the le...,11 NM NW of SJC,SJC,11,NW,20.372,315,Norman Y Mineta San Jose Intl,37.362995,-121.928621,KSJC,37.362949,-122.033151
24,Reported a uas at the same altitude while NNW ...,6 NM NNW of LGA,LGA,6,NNW,11.112,338,Laguardia,40.777250,-73.872611,KLGA,40.906840,-74.043585
25,Reported a uas at same altitude while W bound ...,10 NM WNW of PHX,PHX,10,WNW,18.520,293,Phoenix Sky Harbor Intl,33.434278,-112.011583,KPHX,33.256988,-112.222392
26,Reported a uas within 100 feet while E bound a...,33 NM NE of PHX,PHX,33,NE,61.116,45,Phoenix Sky Harbor Intl,33.434278,-112.011583,KPHX,33.527161,-112.056394
27,"Reported a small silver uas 1,000 feet below a...",4 NM E of DEN,DEN,4,E,7.408,90,Denver Intl,39.861667,-104.673167,KDEN,39.926668,-104.872590
28,Reported a white uas 500 feet below aircraft w...,5 NM E of DAL,DAL,5,E,9.260,90,Dallas Love Fld,32.845945,-96.850877,KDAL,33.234749,-96.387217
29,Reported a 6 foot in diameter white quad copte...,15 NM S of IAH,IAH,15,S,27.780,180,George Bush Intcntl/Houston,29.984435,-95.341442,KIAH,29.984413,-95.264677
30,Aircraft observed uas 35 NW of ATL. No evasive...,35 NM NW of ATL,ATL,35,NW,64.820,315,Hartsfield - Jackson Atlanta Intl,33.636700,-84.427864,KATL,33.636659,-84.328054
31,"Reported a red uas while N bound at 15,000 fee...",5 NM E of IAH,IAH,5,E,9.260,90,George Bush Intcntl/Houston,29.984435,-95.341442,KIAH,29.733827,-95.341442
32,Reported a red uas at 3 o'clock 500 feet below...,12 NM SSE of SEA,SEA,12,SSE,22.224,158,Seattle-Tacoma Intl,47.449889,-122.311778,KSEA,47.860505,-122.924326
33,Reported a black quadcopter uas from 10 o'cloc...,10 NM ENE of LAX,LAX,10,ENE,18.520,68,Los Angeles Intl,33.942496,-118.408049,KLAX,33.942456,-118.307883
34,"Reported a fixed wing uas 1,500 feet below air...",10 NM E of ORD,ORD,10,E,18.520,90,Chicago O'hare Intl,41.976629,-87.907253,KORD,41.791067,-87.807095
35,Reported a white uas passing below aircraft wh...,35 NM ESE of IAH,IAH,35,ESE,64.820,113,George Bush Intcntl/Houston,29.984435,-95.341442,KIAH,30.046900,-95.163391
36,Reported a white and black quadcopter off the ...,13 NM S of BOS,BOS,13,S,24.076,180,General Edward Lawrence Logan Intl,42.362944,-71.006389,KBOS,42.362724,-70.781573
37,Reported a uas at 12 o'clock position at same ...,8 NM NW of TEB,TEB,8,NW,14.816,315,Teterboro,40.850111,-74.060833,KTEB,40.619879,-73.355682
38,Reported black and white uas while W bound at ...,10 NM N HOU,HOU,10,N,18.520,0,William P Hobby,29.645417,-95.278889,KHOU,29.428212,-95.278889
39,Reported a shiny uas from the 12 o'clock posit...,6 NM NNE SFO,SFO,6,NNE,11.112,23,San Francisco Intl,37.618806,-122.375417,KSFO,37.713137,-122.494233
40,Reported a uas 50 ft. below the aircraft. Airc...,15 NM W of IAH,IAH,15,W,27.780,270,George Bush Intcntl/Houston,29.984435,-95.341442,KIAH,30.151502,-95.341442
41,"Reported a uas at 9 o'clock and 1,000 FT below...",5 NM W of LGA,LGA,5,W,9.260,270,Laguardia,40.777250,-73.872611,KLGA,40.869347,-73.821108
42,Large black uas pass below aircraft. Aircraft ...,12 NM WSW LGA,LGA,12,WSW,22.224,248,Laguardia,40.777250,-73.872611,KLGA,40.776781,-74.201687
43,PIC reported a uas 100 feet above their aircra...,20 NM ESE of ORD,ORD,20,ESE,37.040,113,Chicago O'hare Intl,41.976629,-87.907253,KORD,42.011989,-87.859825
44,Aircraft reported blue and white quad-copter u...,12 NM NE ATL,ATL,12,NE,22.224,45,Hartsfield - Jackson Atlanta Intl,33.636700,-84.427864,KATL,33.636659,-84.527674

In [29]:
# Export to csv file
new_df2 = new_df2.drop(['Distance','Bearing','Distance_Kilometers','Bearing_Degrees','ICAO_ID'], 1)
new_df2 = new_df2.rename({'Airport_Longitude': 'Origin_Longitude', 'Airport_Latitude': 'Origin_Latitude'}, axis=1)
new_df2 = pd.merge(new_df2, nonstd, left_on=['REMARKS','UAS_LOC'], right_on = ['REMARKS','NEW_UASLOCATION'] , how='left')
new_df2 = new_df2.drop(['IDENT_y','OLD_UASLOCATION'], 1)
new_df2 = new_df2.rename({'IDENT_x': 'IDENT'}, axis=1)
new_df2.to_csv('COMPLETED-Non-std-45Airports.csv', index = False)

In [ ]:
####################################################################################################

In [49]:
# Read in NAVAID dataset
navaid = pd.read_csv('C:/Users/Olga/Desktop/GMU/DAEN690/LEGO/NAVAID_Cleaned.csv')

# Check the 3 records that did not reference airports
new_df3 = pd.read_csv('C:/Users/Olga/Desktop/GMU/DAEN690/LEGO/Non-std-3NotAirports.csv')
new_df3

,REMARKS,UAS_LOC,IDENT,Distance,Bearing,Distance_Kilometers,Bearing_Degrees
0,Reported a white quad copter uas off the left ...,5 NM S of SHI,SHI,5,S,9.260,180
1,Reported a green uas while SW bound 200 feet a...,15 NM SW of CCC,CCC,15,SW,27.780,225
2,"Reported a possible uas 3 NE of BAL at 10,000 ...",3 NM NE of BAL,BAL,3,NE,5.556,45

In [50]:
# Merge dataframe with NAVAID
join_uas_nav1 = pd.merge(new_df3, navaid, on='IDENT', how='left')
join_uas_nav1

,REMARKS,UAS_LOC,IDENT,Distance,Bearing,Distance_Kilometers,Bearing_Degrees,LONGITUDE,LATITUDE,NAME_TXT
0,Reported a white quad copter uas off the left ...,5 NM S of SHI,SHI,5,S,9.260,180,NaN,NaN,NaN
1,Reported a green uas while SW bound 200 feet a...,15 NM SW of CCC,CCC,15,SW,27.780,225,-72.798860,40.929626,CALVERTON
2,"Reported a possible uas 3 NE of BAL at 10,000 ...",3 NM NE of BAL,BAL,3,NE,5.556,45,-76.661258,39.171071,BALTIMORE

In [51]:
# 2 recrods reference NAVAID. The remaining record is saved for further investigation
join_uas_nav = join_uas_nav1[join_uas_nav1['NAME_TXT'].isnull()]
join_uas_nav = join_uas_nav.drop(['NAME_TXT', 'LATITUDE', 'LONGITUDE'], axis=1)
join_uas_nav = pd.merge(join_uas_nav, nonstd, on='REMARKS', how='left')
join_uas_nav.to_csv('Non-std-1Remaining.csv', index = False)

In [52]:
# Extract the 2 NAVIAD records
join_uas_nav1 = join_uas_nav1[join_uas_nav1['NAME_TXT'].notnull()]
join_uas_nav1

,REMARKS,UAS_LOC,IDENT,Distance,Bearing,Distance_Kilometers,Bearing_Degrees,LONGITUDE,LATITUDE,NAME_TXT
1,Reported a green uas while SW bound 200 feet a...,15 NM SW of CCC,CCC,15,SW,27.780,225,-72.798860,40.929626,CALVERTON
2,"Reported a possible uas 3 NE of BAL at 10,000 ...",3 NM NE of BAL,BAL,3,NE,5.556,45,-76.661258,39.171071,BALTIMORE

In [53]:
join_uas_nav1.to_csv('Non-std-2NAVAID.csv', index = False)

join_uas_nav1 = pd.read_csv('C:/Users/Olga/Desktop/GMU/DAEN690/LEGO/Non-std-2NAVAID.csv')
join_uas_nav1

,REMARKS,UAS_LOC,IDENT,Distance,Bearing,Distance_Kilometers,Bearing_Degrees,LONGITUDE,LATITUDE,NAME_TXT
0,Reported a green uas while SW bound 200 feet a...,15 NM SW of CCC,CCC,15,SW,27.780,225,-72.798860,40.929626,CALVERTON
1,"Reported a possible uas 3 NE of BAL at 10,000 ...",3 NM NE of BAL,BAL,3,NE,5.556,45,-76.661258,39.171071,BALTIMORE

In [54]:
# Calculate UAS lat/long
uas_lat = []
uas_long = []


for i in range(len(join_uas_nav1)):
    lat_nav = pd.to_numeric(join_uas_nav1['LATITUDE'][i])
    long_nav = pd.to_numeric(join_uas_nav1['LONGITUDE'][i])
    b = pd.to_numeric(join_uas_nav1['Bearing_Degrees'][i])
    d = pd.to_numeric(join_uas_nav1['Distance_Kilometers'][i])
    
    origin = geopy.Point(lat_nav, long_nav)
    destination = geodesic(kilometers=d).destination(origin,b)
    
    lat2, lon2, = destination.latitude, destination.longitude
    
    uas_lat.append(lat2)
    uas_long.append(lon2)
    
# Append UAS Lat/Long information to DataFrame
join_uas_nav1['UAS_Latitude'] = uas_lat
join_uas_nav1['UAS_Longitude'] = uas_long


join_uas_nav1

,REMARKS,UAS_LOC,IDENT,Distance,Bearing,Distance_Kilometers,Bearing_Degrees,LONGITUDE,LATITUDE,NAME_TXT,UAS_Latitude,UAS_Longitude
0,Reported a green uas while SW bound 200 feet a...,15 NM SW of CCC,CCC,15,SW,27.780,225,-72.798860,40.929626,CALVERTON,40.752505,-73.031467
1,"Reported a possible uas 3 NE of BAL at 10,000 ...",3 NM NE of BAL,BAL,3,NE,5.556,45,-76.661258,39.171071,BALTIMORE,39.206450,-76.615774

In [55]:
# Rename columns
join_uas_nav1 = join_uas_nav1.rename({'LONGITUDE': 'Origing_Longitude', 'LATITUDE': 'Origin_Latitude'}, axis=1)
join_uas_nav1

,REMARKS,UAS_LOC,IDENT,Distance,Bearing,Distance_Kilometers,Bearing_Degrees,Origing_Longitude,Origin_Latitude,NAME_TXT,UAS_Latitude,UAS_Longitude
0,Reported a green uas while SW bound 200 feet a...,15 NM SW of CCC,CCC,15,SW,27.780,225,-72.798860,40.929626,CALVERTON,40.752505,-73.031467
1,"Reported a possible uas 3 NE of BAL at 10,000 ...",3 NM NE of BAL,BAL,3,NE,5.556,45,-76.661258,39.171071,BALTIMORE,39.206450,-76.615774

In [56]:
join_uas_nav1 = join_uas_nav1.drop(['Distance','Bearing','Distance_Kilometers','Bearing_Degrees'], 1)
join_uas_nav1 = join_uas_nav1.rename({'NAME_TXT': 'NAME'}, axis=1)
join_uas_nav1 = pd.merge(join_uas_nav1, nonstd, on='REMARKS', how='left')
join_uas_nav1 = join_uas_nav1.drop(['IDENT_y','OLD_UASLOCATION'], 1)
join_uas_nav1 = join_uas_nav1.rename({'IDENT_x': 'IDENT'}, axis=1)
join_uas_nav1.to_csv('COMPLETED-Non-std-2NAVAID.csv', index = False)

In [ ]:
##################################################################################################################

In [57]:
# Extract the records labeled "NAVAID"
nonstd_nav = nonstd[(nonstd['DATASET'] == 'NAVAID')]
nonstd_nav = nonstd_nav.drop(['IDENT'], 1)
nonstd_nav

,REMARKS,OLD_UASLOCATION,dateonly,timeonly,DATE,CALLSIGN,POD,PRIMARYCODE,SECONDARYCODES,REPORTINGFACILITY,...,ACALTITUDE.CEDAR,ACHEADING.CEDAR,RELATIVECLOCKPOSITION.CEDAR,UASLONG.CEDAR,UASLAT.CEDAR,SUMMARY.CEDAR,QAFINDINGS.CEDAR,RWYLOCATION,DATASET,NEW_UASLOCATION
0,"Reported a uas while NE bound at 4,500 feet 5 ...",5 NM N NCT,1/16/2018,3:14,2018-01-16T03:14Z,N4905S,NCRCC,UAS,NaN,NCT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NAVAID,5 NM N of SAC
6,VACAPES reported SaltyDog25 reported a uas 500...,16 NM SSE of SWL,4/30/2018,23:02,2018-04-30T23:02Z,SDT25,DEN,UAS,NaN,NTU,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NAVAID,16 NM SSE of SWL
7,"Aircraft W bound at 6,700 feet reported a 3 fo...",12 NM SW GGT,7/1/2018,22:10,2018-07-01T22:10Z,N900PK,DEN,UAS,NaN,SYR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NAVAID,12 NM SW GGT
11,"PIC reported a uas 1,000FT below Aircraft at 1...",20 NM ENE ZSE,7/20/2018,6:15,2018-07-20T06:15Z,ASA1080,DEN,UAS,NaN,ZSE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NAVAID,20 NM ENE of SEA
14,PIC reported a orange fixed wing uas while in ...,15 NM W of S46,7/29/2018,3:42,2018-07-29T03:42Z,N3506T,DEN,UAS,NaN,S46,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NAVAID,15 NM W of SEA
38,Reported a white medium sized uas pass 100 fee...,9 NM NW MFH,3/19/2019,5:52,2019-03-19T05:52Z,N621PD,DEN,UAS,NaN,MFH,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NAVAID,9 NM NW of PQF
40,Reported silver uas while Ebound at 8000 feet ...,15 NM NNW A80,4/1/2019,2:54,2019-04-01T02:54Z,N750DV,DEN,UAS,NaN,A80,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NAVAID,15 NM NNW of AHN
52,"Reported a white, rotorcraft uas, operating at...",10 NM NW C90,6/26/2019,21:58,2019-06-26T21:58Z,N4973F,DEN,UAS,NaN,C90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NAVAID,10 NM NW of GCO
54,Reported a white uas at 3 o'clock 200 FT below...,1 NM NE POI,6/27/2019,6:18,2019-06-27T06:18Z,LIMO82,DEN,UAS,NaN,OXR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NAVAID,1 NM NE NTD

In [58]:
# Save them in csv file
nonstd_nav.to_csv('Non-std-9NAVAID.csv', index = False)

nonstd_nav = pd.read_csv('C:/Users/Olga/Desktop/GMU/DAEN690/LEGO/Non-std-9NAVAID.csv')
nonstd_nav

,REMARKS,OLD_UASLOCATION,dateonly,timeonly,DATE,CALLSIGN,POD,PRIMARYCODE,SECONDARYCODES,REPORTINGFACILITY,...,ACALTITUDE.CEDAR,ACHEADING.CEDAR,RELATIVECLOCKPOSITION.CEDAR,UASLONG.CEDAR,UASLAT.CEDAR,SUMMARY.CEDAR,QAFINDINGS.CEDAR,RWYLOCATION,DATASET,NEW_UASLOCATION
0,"Reported a uas while NE bound at 4,500 feet 5 ...",5 NM N NCT,1/16/2018,3:14,2018-01-16T03:14Z,N4905S,NCRCC,UAS,NaN,NCT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NAVAID,5 NM N of SAC
1,VACAPES reported SaltyDog25 reported a uas 500...,16 NM SSE of SWL,4/30/2018,23:02,2018-04-30T23:02Z,SDT25,DEN,UAS,NaN,NTU,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NAVAID,16 NM SSE of SWL
2,"Aircraft W bound at 6,700 feet reported a 3 fo...",12 NM SW GGT,7/1/2018,22:10,2018-07-01T22:10Z,N900PK,DEN,UAS,NaN,SYR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NAVAID,12 NM SW GGT
3,"PIC reported a uas 1,000FT below Aircraft at 1...",20 NM ENE ZSE,7/20/2018,6:15,2018-07-20T06:15Z,ASA1080,DEN,UAS,NaN,ZSE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NAVAID,20 NM ENE of SEA
4,PIC reported a orange fixed wing uas while in ...,15 NM W of S46,7/29/2018,3:42,2018-07-29T03:42Z,N3506T,DEN,UAS,NaN,S46,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NAVAID,15 NM W of SEA
5,Reported a white medium sized uas pass 100 fee...,9 NM NW MFH,3/19/2019,5:52,2019-03-19T05:52Z,N621PD,DEN,UAS,NaN,MFH,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NAVAID,9 NM NW of PQF
6,Reported silver uas while Ebound at 8000 feet ...,15 NM NNW A80,4/1/2019,2:54,2019-04-01T02:54Z,N750DV,DEN,UAS,NaN,A80,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NAVAID,15 NM NNW of AHN
7,"Reported a white, rotorcraft uas, operating at...",10 NM NW C90,6/26/2019,21:58,2019-06-26T21:58Z,N4973F,DEN,UAS,NaN,C90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NAVAID,10 NM NW of GCO
8,Reported a white uas at 3 o'clock 200 FT below...,1 NM NE POI,6/27/2019,6:18,2019-06-27T06:18Z,LIMO82,DEN,UAS,NaN,OXR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NAVAID,1 NM NE NTD

In [59]:
# Extract IDENTs
uas_loc = nonstd_nav['NEW_UASLOCATION'].tolist()
uas_airport = []

for i in range(len(uas_loc)):
    airport = uas_loc[i].split(' ')[-1]
    
    if len(airport) <= 4:
        uas_airport.append(airport)
    else:
        trim_air = airport[-3:]
        uas_airport.append(trim_air)
        
uas_nav_df = pd.DataFrame()
uas_nav_df['IDENT'] = uas_airport
uas_nav_df

  IDENT
0   SAC
1   SWL
2   GGT
3   SEA
4   SEA
5   PQF
6   AHN
7   GCO
8   NTD

In [60]:
# Merge idents with NAVAID dataset
uas_nav_df = pd.merge(uas_nav_df, navaid, on='IDENT', how='left')
uas_nav_df

  IDENT   LONGITUDE   LATITUDE    NAME_TXT
0   SAC -121.551663  38.443750  SACRAMENTO
1   SWL  -75.463903  38.056602   SNOW HILL
2   GGT  -75.826749  42.788964  GEORGETOWN
3   SEA -122.309632  47.435379     SEATTLE
4   SEA -122.309632  47.435379     SEATTLE
5   PQF  -96.529127  32.809373    MESQUITE
6   AHN  -83.324763  33.947600      ATHENS
7   GCO  -87.902334  41.994097     CHICAGO
8   NTD -119.121987  34.123288  POINT MUGU

In [61]:
# Create Dictionary of Bearings and Respective Degrees
bearing_deg = {
    'N' : 0,
    'NNE' : 23,
    'NE' : 45,
    'ENE' : 68,
    'E' : 90,
    'ESE' : 113,
    'SE' : 135,
    'SSE' : 158,
    'S' : 180,
    'SSW' : 203,
    'SW' : 225,
    'WSW' : 248,
    'W' : 270,
    'WNW' : 293,
    'NW' : 315,
    'NNW' : 338
}

# Separate distances and bearings into two columns
uas_loc = nonstd_nav['NEW_UASLOCATION']
distances = []
bearings = []

for i in range(len(uas_loc)):
    split = uas_loc[i].split(' ')[0:3]
    
    if 'NM' in split[0]: #if there is no space between the distance and NM (i.e. 3NM)
        distance_nm = split[0][0:len(split[0]) - 2]
        bearing_abrev = split[1].replace('of', '')
        
    else: 
        distance_nm = split[0]
        bearing_abrev = split[2].replace('of', '')
    
    distances.append(distance_nm[0:])
    bearings.append(bearing_abrev)

# Create DataFrame to store UAS Location Information
new_df = pd.DataFrame(nonstd_nav['REMARKS'])
new_df['UAS_LOC'] = nonstd_nav['NEW_UASLOCATION']
new_df['IDENT'] = uas_nav_df['IDENT']
new_df['Distance'] = distances
new_df['Bearing'] = bearings

new_df

,REMARKS,UAS_LOC,IDENT,Distance,Bearing
0,"Reported a uas while NE bound at 4,500 feet 5 ...",5 NM N of SAC,SAC,5,N
1,VACAPES reported SaltyDog25 reported a uas 500...,16 NM SSE of SWL,SWL,16,SSE
2,"Aircraft W bound at 6,700 feet reported a 3 fo...",12 NM SW GGT,GGT,12,SW
3,"PIC reported a uas 1,000FT below Aircraft at 1...",20 NM ENE of SEA,SEA,20,ENE
4,PIC reported a orange fixed wing uas while in ...,15 NM W of SEA,SEA,15,W
5,Reported a white medium sized uas pass 100 fee...,9 NM NW of PQF,PQF,9,NW
6,Reported silver uas while Ebound at 8000 feet ...,15 NM NNW of AHN,AHN,15,NNW
7,"Reported a white, rotorcraft uas, operating at...",10 NM NW of GCO,GCO,10,NW
8,Reported a white uas at 3 o'clock 200 FT below...,1 NM NE NTD,NTD,1,NE

In [62]:
# Convert distances from NM to KM and bearing to degrees
new_df['Distance'] = pd.to_numeric(new_df['Distance'],errors = 'coerce')
dist_kilo = []

for i in range(len(new_df)):
    distanceKilo = new_df['Distance'][i] * 1.852 # converting NM to kilometers
    dist_kilo.append(distanceKilo)

bearDegree = pd.DataFrame(new_df['Bearing'])
bearDegree = bearDegree.replace({'Bearing': bearing_deg})

new_df['Distance_Kilometers'] = dist_kilo
new_df['Bearing_Degrees'] = bearDegree
new_df['NAVAID_Latitude'] = uas_nav_df['LATITUDE']
new_df['NAVAID_Longitude'] = uas_nav_df['LONGITUDE']
new_df

,REMARKS,UAS_LOC,IDENT,Distance,Bearing,Distance_Kilometers,Bearing_Degrees,NAVAID_Latitude,NAVAID_Longitude
0,"Reported a uas while NE bound at 4,500 feet 5 ...",5 NM N of SAC,SAC,5,N,9.260,0,38.443750,-121.551663
1,VACAPES reported SaltyDog25 reported a uas 500...,16 NM SSE of SWL,SWL,16,SSE,29.632,158,38.056602,-75.463903
2,"Aircraft W bound at 6,700 feet reported a 3 fo...",12 NM SW GGT,GGT,12,SW,22.224,225,42.788964,-75.826749
3,"PIC reported a uas 1,000FT below Aircraft at 1...",20 NM ENE of SEA,SEA,20,ENE,37.040,68,47.435379,-122.309632
4,PIC reported a orange fixed wing uas while in ...,15 NM W of SEA,SEA,15,W,27.780,270,47.435379,-122.309632
5,Reported a white medium sized uas pass 100 fee...,9 NM NW of PQF,PQF,9,NW,16.668,315,32.809373,-96.529127
6,Reported silver uas while Ebound at 8000 feet ...,15 NM NNW of AHN,AHN,15,NNW,27.780,338,33.947600,-83.324763
7,"Reported a white, rotorcraft uas, operating at...",10 NM NW of GCO,GCO,10,NW,18.520,315,41.994097,-87.902334
8,Reported a white uas at 3 o'clock 200 FT below...,1 NM NE NTD,NTD,1,NE,1.852,45,34.123288,-119.121987

In [63]:
# Merge, drop and rename columns
new_df2 = pd.merge(new_df, navaid, on='IDENT', how='left')
new_df2 = new_df2.drop(['NAVAID_Latitude', 'NAVAID_Longitude'], 1)
new_df2 = new_df2.rename({'LONGITUDE': 'NAVAID_Longitude', 'LATITUDE': 'NAVAID_Latitude'}, axis=1)
new_df2

,REMARKS,UAS_LOC,IDENT,Distance,Bearing,Distance_Kilometers,Bearing_Degrees,NAVAID_Longitude,NAVAID_Latitude,NAME_TXT
0,"Reported a uas while NE bound at 4,500 feet 5 ...",5 NM N of SAC,SAC,5,N,9.260,0,-121.551663,38.443750,SACRAMENTO
1,VACAPES reported SaltyDog25 reported a uas 500...,16 NM SSE of SWL,SWL,16,SSE,29.632,158,-75.463903,38.056602,SNOW HILL
2,"Aircraft W bound at 6,700 feet reported a 3 fo...",12 NM SW GGT,GGT,12,SW,22.224,225,-75.826749,42.788964,GEORGETOWN
3,"PIC reported a uas 1,000FT below Aircraft at 1...",20 NM ENE of SEA,SEA,20,ENE,37.040,68,-122.309632,47.435379,SEATTLE
4,PIC reported a orange fixed wing uas while in ...,15 NM W of SEA,SEA,15,W,27.780,270,-122.309632,47.435379,SEATTLE
5,Reported a white medium sized uas pass 100 fee...,9 NM NW of PQF,PQF,9,NW,16.668,315,-96.529127,32.809373,MESQUITE
6,Reported silver uas while Ebound at 8000 feet ...,15 NM NNW of AHN,AHN,15,NNW,27.780,338,-83.324763,33.947600,ATHENS
7,"Reported a white, rotorcraft uas, operating at...",10 NM NW of GCO,GCO,10,NW,18.520,315,-87.902334,41.994097,CHICAGO
8,Reported a white uas at 3 o'clock 200 FT below...,1 NM NE NTD,NTD,1,NE,1.852,45,-119.121987,34.123288,POINT MUGU

In [64]:
# Calculate UAS lat/long
uas_lat = []
uas_long = []

for i in range(len(new_df)):
    lat_nav = pd.to_numeric(new_df2['NAVAID_Latitude'][i])
    long_nav = pd.to_numeric(new_df2['NAVAID_Longitude'][i])
    b = pd.to_numeric(new_df['Bearing_Degrees'][i])
    d = pd.to_numeric(new_df['Distance_Kilometers'][i])
    
    origin = geopy.Point(lat_nav, long_nav)
    destination = geodesic(kilometers=d).destination(origin,b)
    
    lat2, lon2, = destination.latitude, destination.longitude
    
    uas_lat.append(lat2)
    uas_long.append(lon2)

# Append UAS Lat/Long information to DataFrame
new_df2['UAS_Latitude'] = uas_lat
new_df2['UAS_Longitude'] = uas_long
new_df2

,REMARKS,UAS_LOC,IDENT,Distance,Bearing,Distance_Kilometers,Bearing_Degrees,NAVAID_Longitude,NAVAID_Latitude,NAME_TXT,UAS_Latitude,UAS_Longitude
0,"Reported a uas while NE bound at 4,500 feet 5 ...",5 NM N of SAC,SAC,5,N,9.260,0,-121.551663,38.443750,SACRAMENTO,38.527169,-121.551663
1,VACAPES reported SaltyDog25 reported a uas 500...,16 NM SSE of SWL,SWL,16,SSE,29.632,158,-75.463903,38.056602,SNOW HILL,37.809007,-75.337849
2,"Aircraft W bound at 6,700 feet reported a 3 fo...",12 NM SW GGT,GGT,12,SW,22.224,225,-75.826749,42.788964,GEORGETOWN,42.647341,-76.018379
3,"PIC reported a uas 1,000FT below Aircraft at 1...",20 NM ENE of SEA,SEA,20,ENE,37.040,68,-122.309632,47.435379,SEATTLE,47.559273,-121.853299
4,PIC reported a orange fixed wing uas while in ...,15 NM W of SEA,SEA,15,W,27.780,270,-122.309632,47.435379,SEATTLE,47.434788,-122.677889
5,Reported a white medium sized uas pass 100 fee...,9 NM NW of PQF,PQF,9,NW,16.668,315,-96.529127,32.809373,MESQUITE,32.915584,-96.655124
6,Reported silver uas while Ebound at 8000 feet ...,15 NM NNW of AHN,AHN,15,NNW,27.780,338,-83.324763,33.947600,ATHENS,34.179755,-83.437645
7,"Reported a white, rotorcraft uas, operating at...",10 NM NW of GCO,GCO,10,NW,18.520,315,-87.902334,41.994097,CHICAGO,42.111887,-88.060674
8,Reported a white uas at 3 o'clock 200 FT below...,1 NM NE NTD,NTD,1,NE,1.852,45,-119.121987,34.123288,POINT MUGU,34.135093,-119.107790

In [65]:
new_df2 = new_df2.drop(['Distance','Bearing','Distance_Kilometers','Bearing_Degrees'], 1)
new_df2 = new_df2.rename({'NAME_TXT': 'NAME'}, axis=1)
new_df2 = pd.merge(new_df2, nonstd, on='REMARKS', how='left')
new_df2 = new_df2.drop(['IDENT_y','OLD_UASLOCATION'], 1)
new_df2 = new_df2.rename({'IDENT_x': 'IDENT'}, axis=1)
new_df2.to_csv('COMPLETED-Non-std-9NAVAID.csv', index = False)

In [ ]:
#################################################################################################################

In [66]:
# Extract Fixed Radial records to be explored later
nonstd_fixd = nonstd[(nonstd['DATASET'] == 'FIXED RADIAL DISTANCE')]
nonstd_fixd

,IDENT,REMARKS,OLD_UASLOCATION,dateonly,timeonly,DATE,CALLSIGN,POD,PRIMARYCODE,SECONDARYCODES,...,ACALTITUDE.CEDAR,ACHEADING.CEDAR,RELATIVECLOCKPOSITION.CEDAR,UASLONG.CEDAR,UASLAT.CEDAR,SUMMARY.CEDAR,QAFINDINGS.CEDAR,RWYLOCATION,DATASET,NEW_UASLOCATION
32,RCC,"DCA-1: Incident occurred at 1835 (1335L), firs...",675 NM N NCRCC,2/16/2019,2:36,2019-02-16T02:36Z,NaN,NCRCC,UAS,LAW ENFORCEMENT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FIXED RADIAL DISTANCE,3.5 NM 300 of DCA
58,USCP,TOI P-56A// DCA-1: USCP reported a MPD officer...,1100 NM N USCP,1/20/2021,15:25,2021-01-20T15:25Z,NaN,NCRCC,TOI-PA-P-56A,UAS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FIXED RADIAL DISTANCE,3 NM 036 of DCA
59,FED,"DCA-1: DCA072008, 1 NW of FEDEX Field, MUSEL18...",1 NM NW of FED,6/21/2021,18:56,2021-06-21T18:56Z,MUSEL18,NCRCC,UAS,"SUSPICIOUS ACTIVITY, TOI-NCR FRZ",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FIXED RADIAL DISTANCE,8 NM 072 of DCA

In [67]:
nonstd_fixd.to_csv('Non-std-3FixedRadial.csv', index = False)